import {useState} from "react";
import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {useApi} from "../../api/ApiProvider";
import {decodeOrderPage} from "../../api/decoders";
import {EmptyState} from "../../components/EmptyState";
import {ErrorBlock, LoadingBlock} from "../../components/ApiState";
import {StatusBadge} from "../../components/StatusBadge";
import {ServerDataGrid} from "../../components/ServerDataGrid";
import {navigate} from "../../shell/useLocationPath";
import {Drawer} from "../../components/Drawer";
import {useToast} from "../../components/Toast";
import {Icon} from "../../components/Icon";

function money(minor: number, currency: string): string {return new Intl.NumberFormat("ru-RU", {style: "currency", currency}).format(minor / 100)}
export function OrderList({initialId}:{initialId?:string}) {
  const api = useApi(),toast=useToast();const [selected,setSelected]=useState<string|undefined>(initialId),[q,setQ]=useState(""),[status,setStatus]=useState(""),[cursor,setCursor]=useState(""),[history,setHistory]=useState<string[]>([]);const queryClient=useQueryClient();
  const demo=useMutation({mutationFn:async()=>{await api.createDemoOrders({idempotencyKey:"demo-dataset:create"})},onSuccess:async()=>{toast.push({kind:"success",title:"Демо-набор создан",body:"Заказы, товары и остатки появились в рабочем контуре."});await Promise.all([queryClient.invalidateQueries({queryKey:["orders"]}),queryClient.invalidateQueries({queryKey:["inventory"]}),queryClient.invalidateQueries({queryKey:["products"]})])},onError:()=>toast.push({kind:"error",title:"Не удалось создать демо-данные"})});
  const query=useQuery({queryKey:["orders","shell",q,status,cursor],queryFn:async()=>decodeOrderPage((await api.listOrders({limit:25,q:q||undefined,status:status||undefined,cursor:cursor||undefined})).body),staleTime:20_000});
  const detail=useQuery({queryKey:["orders","detail",selected],queryFn:async()=>(await api.getOrder({orderId:selected!})).body as any,enabled:!!selected});
  if(query.isPending&&!query.data)return <LoadingBlock/>;if(query.isError&&!query.data)return <ErrorBlock>Не удалось загрузить заказы.</ErrorBlock>;const page=query.data??{items:[]};if(page.items.length===0&&!q&&!status&&!history.length)return <EmptyState title="Создайте демонстрационные данные" text="Добавьте заказы, товар и остатки, чтобы посмотреть рабочий поток."><button className="button primary" disabled={demo.isPending} onClick={()=>demo.mutate()}>{demo.isPending?"Создаём…":"Создать демо-набор"}</button></EmptyState>;
  const reset=(kind:"q"|"status",value:string)=>{if(kind==="q")setQ(value);else setStatus(value);setCursor("");setHistory([])};const columns=[{key:"number",label:"Номер",render:(v:any)=><span className="mono table-primary">{v.order_number}</span>},{key:"status",label:"Статус",render:(v:any)=><StatusBadge value={v.status}/>},{key:"amount",label:"Сумма",render:(v:any)=><strong>{money(v.grand_minor_units,v.currency)}</strong>,align:"end" as const},{key:"created",label:"Создан",render:(v:any)=><time>{new Date(v.placed_at).toLocaleString("ru-RU")}</time>}];
  return <><ServerDataGrid rows={page.items as any[]} columns={columns} rowKey={v=>v.id} query={q} onQuery={v=>reset("q",v)} filter={status} filterOptions={[{value:"pending",label:"Ожидают"},{value:"confirmed",label:"Подтверждены"},{value:"processing",label:"В работе"},{value:"fulfilled",label:"Выполнены"},{value:"cancelled",label:"Отменены"}]} onFilter={v=>reset("status",v)} loading={query.isFetching} hasPrevious={history.length>0} hasNext={!!page.next_cursor} onPrevious={()=>{const prev=[...history];setCursor(prev.pop()??"");setHistory(prev)}} onNext={()=>{if(page.next_cursor){setHistory(v=>[...v,cursor]);setCursor(page.next_cursor)}}} onOpen={v=>{setSelected(v.id);navigate(`/orders/${encodeURIComponent(v.id)}`)}}/><Drawer open={!!selected} onClose={()=>{setSelected(undefined);navigate("/orders")}} title={detail.data?.order_number??"Заказ"} subtitle="Карточка заказа и fulfillment"><>{detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock>Не удалось открыть заказ.</ErrorBlock>:detail.data?<><div className="drawer-kpis"><div><small>Итого</small><strong>{money(detail.data.grand_minor_units,detail.data.currency)}</strong></div><div><small>Статус</small><StatusBadge value={detail.data.status}/></div><div><small>Канал</small><strong>{detail.data.sources[0]?.provider??"TORGNEXA"}</strong></div></div><section className="drawer-section"><h3>Позиции заказа</h3><div className="line-items">{detail.data.items.map((line:any,index:number)=><div className="line-item" key={`${line.sku}-${index}`}><span className="line-icon"><Icon name="catalog"/></span><div><strong>{line.sku}</strong><small>{line.quantity_coefficient/(10**line.quantity_scale)} {line.unit}</small></div><div className="line-price"><strong>{money(line.line_total_minor_units,detail.data.currency)}</strong><small>{money(line.unit_price_minor_units,detail.data.currency)} / ед.</small></div></div>)}</div></section><section className="drawer-section"><h3>Контекст</h3><dl className="detail-list"><div><dt>Создан</dt><dd>{new Date(detail.data.placed_at).toLocaleString("ru-RU")}</dd></div><div><dt>Доставка</dt><dd>{money(detail.data.shipping_minor_units,detail.data.currency)}</dd></div><div><dt>Remote ID</dt><dd className="mono">{detail.data.sources[0]?.remote_id??"—"}</dd></div></dl></section></>:null}</></Drawer></>;
}
