import {useMemo,useState} from "react";
import type {ReactNode} from "react";
import {Icon} from "./Icon";

export type DataColumn<T>={key:string;label:string;value:(row:T)=>string|number;render?:(row:T)=>ReactNode;sortable?:boolean;hideable?:boolean;align?:"start"|"end"};
export function DataTable<T>({rows,columns,rowKey,searchPlaceholder="Поиск…",empty="Нет данных",pageSize=15,onOpen,bulkActions}: {rows:T[];columns:DataColumn<T>[];rowKey:(row:T)=>string;searchPlaceholder?:string;empty?:string;pageSize?:number;onOpen?:(row:T)=>void;bulkActions?:Array<{label:string;run:(rows:T[])=>void}>}){
 const initial=new URL(window.location.href);
 const [search,setSearch]=useState(initial.searchParams.get("q")??""),[sort,setSort]=useState<{key:string;dir:1|-1}|null>(()=>{const key=initial.searchParams.get("sort");return key?{key,dir:initial.searchParams.get("dir")==="desc"?-1:1}:null}),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]),[hidden,setHidden]=useState<string[]>(()=>initial.searchParams.get("cols")?.split(",").filter(Boolean)??[]),[columnsOpen,setColumnsOpen]=useState(false);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();let out=q?rows.filter(row=>columns.some(col=>String(col.value(row)).toLowerCase().includes(q))):[...rows];if(sort){const col=columns.find(v=>v.key===sort.key);if(col)out.sort((a,b)=>String(col.value(a)).localeCompare(String(col.value(b)),"ru",{numeric:true})*sort.dir)}return out},[rows,columns,search,sort]);
 const selectable=Boolean(bulkActions?.length),visible=columns.filter(c=>!hidden.includes(c.key)),pages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pages-1),slice=filtered.slice(safePage*pageSize,(safePage+1)*pageSize),selectedRows=rows.filter(r=>selected.includes(rowKey(r)));
 const toggleAll=()=>{const ids=slice.map(rowKey);setSelected(current=>ids.every(id=>current.includes(id))?current.filter(id=>!ids.includes(id)):Array.from(new Set([...current,...ids])))};
 const sortBy=(key:string)=>{setPage(0);setSort(current=>current?.key===key?{key,dir:current.dir===1?-1:1}:{key,dir:1})};
 const saveView=async()=>{const url=new URL(window.location.href);if(search)url.searchParams.set("q",search);else url.searchParams.delete("q");if(sort){url.searchParams.set("sort",sort.key);url.searchParams.set("dir",sort.dir===1?"asc":"desc")}else{url.searchParams.delete("sort");url.searchParams.delete("dir")}if(hidden.length)url.searchParams.set("cols",hidden.join(","));else url.searchParams.delete("cols");window.history.replaceState(window.history.state,"",url);await navigator.clipboard?.writeText(url.toString())};
 return <section className="data-table"><div className="data-toolbar"><label className="table-search"><Icon name="search"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder={searchPlaceholder}/></label><div className="data-toolbar-actions">{selectedRows.length>0?<span className="selection-pill">Выбрано: {selectedRows.length}</span>:null}{bulkActions?.map(action=><button type="button" key={action.label} className="button ghost" disabled={!selectedRows.length} onClick={()=>action.run(selectedRows)}>{action.label}</button>)}<button type="button" className="button ghost compact-action" onClick={()=>void saveView()} title="Сохранить фильтры в ссылке и скопировать её"><Icon name="more"/> Сохранить вид</button><div className="column-control"><button type="button" className="button ghost compact-action" onClick={()=>setColumnsOpen(v=>!v)}><Icon name="columns"/> Колонки</button>{columnsOpen?<div className="column-menu">{columns.filter(c=>c.hideable!==false).map(c=><label key={c.key}><input type="checkbox" checked={!hidden.includes(c.key)} onChange={event=>setHidden(current=>event.target.checked?current.filter(k=>k!==c.key):[...current,c.key])}/>{c.label}</label>)}</div>:null}</div></div></div><div className="table-wrap"><table><thead><tr>{selectable?<th className="select-cell"><input type="checkbox" checked={slice.length>0&&slice.every(r=>selected.includes(rowKey(r)))} onChange={toggleAll} aria-label="Выбрать строки"/></th>:null}{visible.map(col=><th key={col.key} className={col.align==="end"?"text-end":""}>{col.sortable===false?col.label:<button type="button" className="sort-button" onClick={()=>sortBy(col.key)}>{col.label}<Icon name="sort" size={14}/>{sort?.key===col.key?<span>{sort.dir===1?"↑":"↓"}</span>:null}</button>}</th>)}{onOpen?<th/>:null}</tr></thead><tbody>{slice.map(row=>{const id=rowKey(row);return <tr key={id} className={selected.includes(id)?"row-selected":""}>{selectable?<td className="select-cell"><input type="checkbox" checked={selected.includes(id)} onChange={event=>setSelected(current=>event.target.checked?[...current,id]:current.filter(v=>v!==id))}/></td>:null}{visible.map(col=><td key={col.key} className={col.align==="end"?"text-end":""}>{col.render?col.render(row):String(col.value(row))}</td>)}{onOpen?<td className="row-action"><button type="button" className="icon-button" onClick={()=>onOpen(row)} aria-label="Открыть"><Icon name="chevron"/></button></td>:null}</tr>})}</tbody></table>{slice.length===0?<div className="table-empty">{empty}</div>:null}</div><footer className="table-footer"><span>{filtered.length} записей · страница {safePage+1} из {pages}</span><div><button type="button" className="button ghost" disabled={safePage===0} onClick={()=>setPage(v=>Math.max(0,v-1))}>Назад</button><button type="button" className="button ghost" disabled={safePage>=pages-1} onClick={()=>setPage(v=>Math.min(pages-1,v+1))}>Далее</button></div></footer></section>
}
