export const capabilityLabels: Readonly<Record<string, string>> = {
  "ai.analyze": "Аналитические запросы ИИ",
  "ai.completion.generate": "Генерация ответов ИИ",
  "approvals.read": "Просмотр согласований",
  "approvals.write": "Управление согласованиями",
  "audit.read": "Просмотр аудита",
  "ads.read": "Просмотр рекламы",
  "ads.manage": "Управление рекламой",
  "cloud.subscription.read": "Просмотр подписки",
  "compliance.read": "Просмотр соответствия",
  "connectors.accounts.read": "Просмотр кабинетов интеграций",
  "connectors.accounts.write": "Управление кабинетами интеграций",
  "connectors.read": "Просмотр интеграций",
  "connectors.replay.run": "Запуск проверки интеграций",
  "counterparties.read": "Просмотр контрагентов",
  "classified.leads.read": "Просмотр обращений",
  "classified.listings.read": "Просмотр объявлений",
  "classified.messages.read": "Просмотр сообщений",
  "classified.messages.reply": "Ответы на сообщения",
  "classified.publications.status.read": "Просмотр статусов публикаций",
  "classified.publications.write": "Управление публикациями",
  "classified.stats.read": "Просмотр статистики объявлений",
  "crm.entities.read": "Просмотр сделок CRM",
  "crm.entities.write": "Управление сделками CRM",
  "crm.productrows.read": "Просмотр товарных строк CRM",
  "crm.productrows.write": "Управление товарными строками CRM",
  "edo.documents.read": "Просмотр документов ЭДО",
  "edo.documents.send": "Отправка документов ЭДО",
  "edo.documents.sign_request": "Запрос подписи документов ЭДО",
  "erp.catalog.read": "Просмотр каталога ERP",
  "erp.inventory.read": "Просмотр остатков ERP",
  "erp.orders.read": "Просмотр заказов ERP",
  "fx.read": "Просмотр курсов валют",
  "fx.rates.read": "Просмотр курсов валют",
  "government.documents.read": "Просмотр документов госсистем",
  "government.documents.write": "Управление документами госсистем",
  "government.inventory.read": "Просмотр остатков госсистем",
  "government.reconciliation.run": "Запуск сверки госсистем",
  "government.references.read": "Просмотр справочников госсистем",
  "inventory.read": "Просмотр остатков",
  "inventory.write": "Управление остатками",
	"logistics.batches.create": "Формирование партий доставки",
	"logistics.batches.cancel": "Отмена партий доставки",
	"logistics.batches.submit": "Передача партий в работу",
	"logistics.batches.archive": "Перемещение партий в архив",
	"logistics.batches.archive.read": "Просмотр партий в архиве",
	"logistics.batches.unarchive": "Возврат партий из архива",
	"logistics.batches.sending_date.write": "Изменение даты передачи партии",
	"logistics.label.read": "Просмотр транспортных этикеток",
  "logistics.rates.read": "Просмотр тарифов доставки",
	"logistics.return.create": "Создание возвратов доставки",
	"logistics.return.separate.create": "Создание отдельной возвратной отправки",
	"logistics.return.separate.delete": "Удаление отдельной возвратной отправки",
	"logistics.return.separate.edit": "Редактирование отдельной возвратной отправки",
  "logistics.shipment.cancel": "Отмена отправлений",
  "logistics.shipment.create": "Создание отправлений",
  "logistics.track.read": "Отслеживание отправлений",
  "logistics.webhooks.verify": "Проверка уведомлений доставки",
  "marking.status.read": "Просмотр статусов маркировки",
  "notifications.read": "Просмотр уведомлений",
  "notifications.receive": "Получение уведомлений",
  "lineage.read": "Просмотр происхождения данных",
  "operations.realtime.read": "Просмотр оперативных обновлений",
  "orders.read": "Просмотр заказов",
  "orders.status.write": "Изменение статусов заказов",
  "payments.create": "Создание платежей",
  "payments.reconcile": "Сверка платежей",
  "payments.refund": "Возврат платежей",
  "payments.status.read": "Просмотр статусов платежей",
  "payments.webhooks": "Получение уведомлений о платежах",
  "pickup.points.read": "Просмотр пунктов выдачи",
  "prices.read": "Просмотр цен",
  "prices.write": "Управление ценами",
  "plugins.read": "Просмотр плагинов",
  "privacy.requests.write": "Управление запросами приватности",
  "products.read": "Просмотр товаров",
  "products.write": "Управление товарами",
  "profitability.scenarios.write": "Запуск сценариев прибыльности",
  "returns.read": "Просмотр возвратов",
  "reports.read": "Просмотр отчётов",
  "settings.ai_governance.read": "Просмотр политик ИИ",
  "settings.ai_governance.write": "Управление политиками ИИ",
  "settings.ai_providers.read": "Просмотр провайдеров ИИ",
  "settings.ai_providers.write": "Управление провайдерами ИИ",
  "settings.identity_providers.read": "Просмотр провайдеров входа",
  "settings.identity_providers.write": "Управление провайдерами входа",
  "settings.mcp_accounts.read": "Просмотр MCP-аккаунтов",
  "settings.mcp_accounts.write": "Управление MCP-аккаунтами",
  "settings.members.read": "Просмотр участников рабочего пространства",
  "settings.members.write": "Управление участниками рабочего пространства",
  "settings.profile.read": "Просмотр личного профиля",
  "settings.profile.write": "Редактирование личного профиля",
  "settings.read": "Просмотр настроек",
  "settings.security.read": "Просмотр безопасности",
  "settings.security.evidence.read": "Просмотр свидетельств безопасности",
  "settings.security.posture.read": "Просмотр состояния безопасности",
  "settings.security.write": "Управление безопасностью",
  "settlements.read": "Просмотр расчётов",
  "social.analytics.read": "Просмотр аналитики социальных сетей",
  "social.comments.read": "Просмотр комментариев",
  "social.comments.reply": "Ответы на комментарии",
  "social.post.buttons": "Интерактивные кнопки публикаций",
  "social.post.delete": "Удаление публикаций",
  "social.post.edit": "Редактирование публикаций",
  "social.post.media": "Публикация медиафайлов",
  "social.post.text": "Текстовые публикации",
  "social.post.video": "Видео-публикации",
  "social.webhooks": "Получение уведомлений социальных сетей",
  "stock.read": "Просмотр остатков",
  "stock.write": "Управление остатками",
  "sync.read": "Просмотр синхронизации",
  "sync.write": "Управление синхронизацией",
  "webhooks.read": "Просмотр вебхуков",
  "webhooks.write": "Управление вебхуками",
  "vetis.documents.read": "Просмотр документов ВетИС",
  "vetis.documents.write": "Управление документами ВетИС",
};

const capabilityActionLabels: Readonly<Record<string, string>> = {
  cancel: "Отмена",
  create: "Создание",
  delete: "Удаление",
  edit: "Редактирование",
  generate: "Генерация",
  read: "Просмотр",
  receive: "Получение",
  reconcile: "Сверка",
  refund: "Возврат",
  reply: "Ответы",
  run: "Запуск",
  send: "Отправка",
  sign_request: "Запрос подписи",
  status: "Статусы",
  verify: "Проверка",
  webhooks: "Уведомления",
  write: "Управление",
};

const capabilityAreaLabels: Readonly<Record<string, string>> = {
  analytics: "аналитики социальных сетей",
  buttons: "публикаций",
  comments: "комментариев",
  completion: "ответов ИИ",
  documents: "документов",
  entities: "сделок CRM",
  inventory: "остатков",
  label: "транспортных этикеток",
  leads: "обращений",
  listings: "объявлений",
  media: "медиафайлов",
  messages: "сообщений",
  points: "пунктов выдачи",
  post: "публикаций",
  productrows: "товарных строк CRM",
  publications: "публикаций",
  rates: "курсов и тарифов",
  reconciliation: "сверки",
  references: "справочников",
  shipment: "отправлений",
  stats: "статистики",
  status: "статусов",
  track: "отслеживания отправлений",
  webhooks: "уведомлений",
};

export function capabilityLabelFor(value: string): string {
  if (capabilityLabels[value]) return capabilityLabels[value];
  const parts = value.split(".");
  const action = parts.at(-1) ?? value;
  const area = parts.at(-2) ?? parts[0] ?? value;
  return `${capabilityActionLabels[action] ?? "Возможность"} · ${capabilityAreaLabels[area] ?? area.replaceAll("_", " ")}`;
}

export const auditActionLabels: Readonly<Record<string, string>> = {
  "ai_provider_account.analyze": "Запрос к провайдеру ИИ",
  "ai_provider_account.create": "Провайдер ИИ добавлен",
  "ai_provider_account.disable": "Провайдер ИИ отключён",
  "catalog.product.update": "Товар изменён",
  "connector.account.capabilities_changed": "Возможности кабинета изменены",
  "connector.account.initial_import_queued": "Первичная загрузка кабинета поставлена в очередь",
  "connector.account.runtime_config_updated": "Параметры кабинета изменены",
  "connector.account.schedule_updated": "Расписание кабинета изменено",
  "demo.catalog.publish": "Демо-каталог опубликован",
  "demo.dataset.created": "Демо-набор создан",
  "inventory.position.created": "Позиция остатков создана",
  "inventory.warehouse.created": "Склад создан",
  "inventory.warehouse.status_changed": "Состояние склада изменено",
  "mcp_agent_kill_switch.set": "Аварийный выключатель агентов изменён",
  "mcp_agent_policy.install": "Политика агента установлена",
  "mcp_client_account.create": "MCP-аккаунт создан",
  "mcp_client_account.disable": "MCP-аккаунт отозван",
  "mcp_client_account.rotate": "Токен MCP-аккаунта ротирован",
  "privacy.legal_hold.placed": "Юридическое удержание включено",
  "privacy.legal_hold.released": "Юридическое удержание снято",
  "resource.read": "Ресурс просмотрен",
  "settings.identity_provider.activate": "Провайдер входа активирован",
  "settings.identity_provider.disable": "Провайдер входа отключён",
  "settings.identity_provider.draft_saved": "Черновик провайдера входа сохранён",
  "settings.identity_provider.rollback": "Конфигурация провайдера входа откачена",
  "settings.identity_provider.validate": "Провайдер входа проверен",
  "settings.identity_provider.validation_failed": "Проверка провайдера входа отклонена",
  "settings.member.invited": "Участник приглашён",
  "settings.member.updated": "Доступ участника изменён",
  "settings.profile.avatar_removed": "Фото профиля удалено",
  "settings.profile.updated": "Профиль пользователя изменён",
  "settings.security.session_revoked": "Сессия отозвана",
  "settings.workspace.updated": "Профиль рабочего пространства изменён",
  "sync.run": "Синхронизация запущена",
};

export const auditResourceLabels: Readonly<Record<string, string>> = {
  ai_egress_policy: "Политика передачи данных ИИ",
  ai_provider_account: "Аккаунт провайдера ИИ",
  connector_account: "Кабинет интеграции",
  connector_replay: "Проверка интеграции",
  demo_dataset: "Демо-набор",
  iam_mapping: "Правило доступа",
  identity_provider: "Провайдер входа",
  mcp_agent_kill_switch: "Аварийный выключатель агентов",
  mcp_agent_policy: "Политика агента",
  mcp_client_account: "MCP-аккаунт",
  mcp_tool: "Инструмент MCP",
  order: "Заказ",
  price: "Цена",
  privacy_job: "Задание приватности",
  privacy_legal_hold: "Юридическое удержание",
  product: "Товар",
  profitability_scenario: "Сценарий прибыльности",
  resource: "Ресурс",
  warehouse: "Склад",
  workspace: "Рабочее пространство",
  workspace_member: "Участник рабочего пространства",
  user_profile: "Профиль пользователя",
};

export const auditSourceLabels: Readonly<Record<string, string>> = {
  api: "Интерфейс приложения",
  "api.payments": "Платёжный контур",
  "api.social": "Контур публикаций",
  catalog: "Каталог",
  clickhouse: "Аналитическое хранилище",
  "demo.seed": "Демо-наполнение",
  import_export: "Импорт и экспорт",
  manual: "Действие оператора",
  mcp: "MCP-контур",
  notifications: "Центр уведомлений",
  operator: "Оператор",
  postgresql: "Операционная база данных",
  privacy: "Контур приватности",
  reference: "Справочные данные",
  security_pipeline: "Контур безопасности",
  system: "Система",
  test: "Тестовый контур",
  web_ui: "Веб-интерфейс",
  webhook: "Вебхук",
  worker: "Фоновый процесс",
  "worker.reconciliation": "Фоновая сверка",
  "worker.social": "Фоновая публикация",
  "worker.upload": "Фоновая обработка загрузки",
};

const auditWordLabels: Readonly<Record<string, string>> = {
  activate: "активирован",
  account: "аккаунт",
  ai: "ИИ",
  authorized: "разрешено",
  changed: "изменено",
  connector: "интеграция",
  create: "создано",
  created: "создано",
  denied: "отклонено",
  delete: "удаление",
  disable: "отключение",
  egress: "передача данных",
  evidence: "свидетельства",
  import: "импорт",
  initial: "первичный",
  install: "установка",
  policy: "политика",
  queued: "поставлено в очередь",
  read: "просмотр",
  replay: "проверка",
  runtime: "среда",
  security: "безопасность",
  succeeded: "успешно",
  tool: "инструмент",
  workspace: "рабочее пространство",
  config: "параметры",
  configuration: "конфигурация",
  capabilities: "возможности",
  rotate: "ротация",
  run: "запуск",
  session: "сессия",
  set: "изменено",
  updated: "изменено",
  update: "изменение",
  validate: "проверка",
};

export function humanizeTechnicalValue(value: string): string {
  return value.split(/[._-]/).filter(Boolean).map(part => auditWordLabels[part] ?? part).join(" · ");
}

export function auditActionLabel(value: string): string { return auditActionLabels[value] ?? humanizeTechnicalValue(value); }
export function auditResourceLabel(value: string): string { return auditResourceLabels[value] ?? humanizeTechnicalValue(value); }
export function auditSourceLabel(value: string): string { return auditSourceLabels[value] ?? humanizeTechnicalValue(value); }

export const roleLabels: Readonly<Record<string, string>> = {
  admin: "Администратор",
  manager: "Менеджер",
  operator: "Оператор",
  viewer: "Наблюдатель",
  "default-roles-torgnexa": "Базовые роли TORGNEXA",
  offline_access: "Автономный доступ",
  uma_authorization: "Авторизация доступа",
};

export type CapabilityGroupID = "commerce" | "integrations" | "control" | "workspace" | "other";

export function capabilityGroupFor(value: string): CapabilityGroupID {
  if (/^(products|orders|stock|settlements|fx|reports|profitability|counterparties|ads)(\.|$)/.test(value)) return "commerce";
  if (/^(connectors|sync|webhooks|operations|plugins|cloud)(\.|$)/.test(value)) return "integrations";
  if (/^(approvals|audit|compliance|privacy|notifications|lineage)(\.|$)/.test(value) || value.startsWith("settings.security")) return "control";
  if (value.startsWith("ai.") || /^settings\.(ai_|mcp_|identity_|members|read)/.test(value)) return "workspace";
  return "other";
}

export const syncModeLabels: Readonly<Record<string, string>> = {
  incremental: "Инкрементальная",
  scheduled_full: "Полная сверка",
  on_demand: "По запросу",
};

export const syncActionLabels: Readonly<Record<string, string>> = {
  apply_local: "Применить локальное состояние",
  apply_remote: "Применить состояние кабинета",
  ignore: "Игнорировать",
  manual: "Проверить вручную",
};

export const connectorHealthLabels: Readonly<Record<string, string>> = {
  healthy: "Работает",
  degraded: "Ограничен",
  unavailable: "Недоступен",
  unknown: "Неизвестно",
};

export const workspaceStatusLabels: Readonly<Record<string, string>> = {
  active: "Активно",
  disabled: "Отключено",
  suspended: "Приостановлено",
  archived: "Архивировано",
};

export const bootstrapJobStatusLabels: Readonly<Record<string, string>> = {
  pending: "В очереди",
  running: "Выполняется",
  retry_wait: "Ожидает повтора",
  completed: "Завершена",
  failed: "Ошибка",
};

export function labelFor(value: string | undefined, labels: Readonly<Record<string, string>>): string {
  if (!value) return "—";
  return labels[value] ?? value;
}
