const statusLabels: Readonly<Record<string, string>> = {
  active: "Активен",
  approved: "Согласован",
  authorized: "Авторизован",
  allowed: "Разрешено",
  allocations: "Резервы исполнения",
  archived: "Архив",
  cancelled: "Отменён",
  closed: "Закрыт",
  completed: "Завершён",
  confirmed: "Подтверждён",
  critical: "Критический",
  "default-deny": "Запрет по умолчанию",
  degraded: "Ограничен",
  denied: "Отклонено",
  disabled: "Отключён",
  disputed: "Оспорен",
  draft: "Черновик",
  error: "Ошибка",
  executing: "Выполняется",
  fail: "Проверка не пройдена",
  expired: "Срок истёк",
  failed: "Ошибка",
  fulfilled: "Выполнен",
  in_transit: "В пути",
  inspecting: "На проверке",
  failover: "Переключение",
  healthy: "Работает",
  info: "Информация",
  live: "Подключено",
  lost: "Потерян",
  needs_attention: "Требует внимания",
  open: "Открыт",
  offline: "Недоступен",
  operational_state: "Операционное состояние",
  pending: "Ожидает",
  partially_accepted: "Принят частично",
  pass: "Проверка пройдена",
  planned: "Запланировано",
  processing: "В работе",
  rejected: "Отклонён",
  quarantine: "Карантин",
  restock: "На склад",
  scrap: "Утилизация",
  replace: "Замена",
  resolved: "Решён",
  revoked: "Отозван",
  succeeded: "Успешно",
  "server-side": "На сервере",
  unknown: "Неизвестно",
  unavailable: "Недоступен",
  warning: "Предупреждение",
};

export function StatusBadge({value}: {value: string}) {
  const normalized = value.trim().toLowerCase();
  return <span className={`status status-${normalized.replace(/[^a-z0-9]+/g, "-")}`}>{statusLabels[normalized] ?? value}</span>;
}
