const statusLabels: Readonly<Record<string, string>> = {
  active: "Активен",
  approval_required: "Требуется согласование",
  approved: "Согласован",
  blocked: "Заблокировано",
  authorized: "Авторизован",
  allowed: "Разрешено",
  allocations: "Резервы исполнения",
  archived: "Архив",
  cancelled: "Отменён",
  cancellation_pending: "Отмена на согласовании",
  canceled: "Отменён",
  closed: "Закрыт",
  completed: "Завершён",
  confirmed: "Подтверждён",
  created: "Создан",
  critical: "Критический",
  "default-deny": "Запрет по умолчанию",
  degraded: "Ограничен",
  denied: "Отклонено",
  disabled: "Отключён",
  delivered: "Доставлен",
  disputed: "Оспорен",
  draft: "Черновик",
  error: "Ошибка",
  executing: "Выполняется",
  fail: "Проверка не пройдена",
  expired: "Срок истёк",
  failed: "Ошибка",
  fulfilled: "Выполнен",
  integrated: "Интегрировано",
  in_transit: "В пути",
  on_delivery: "На доставке",
  inspecting: "На проверке",
  failover: "Переключение",
  healthy: "Работает",
  info: "Информация",
  live: "Подключено",
  lost: "Потерян",
  needs_attention: "Требует внимания",
  open: "Открыт",
  offline: "Недоступен",
  operational_state: "Операционное состояние",
  pending: "Ожидает",
  partially_accepted: "Принят частично",
  pass: "Проверка пройдена",
  planned: "Запланировано",
  ready: "Готово",
  ready_onboarding: "Готово",
  ready_for_shipment: "Готово к отправке",
  ready_with_warnings: "Готово с предупреждениями",
  stale: "Устарело",
  unsupported: "Не поддерживается",
  not_configured: "Не настроено",
  not_available: "Недоступно",
  read_only: "Только чтение",
  partially_supported: "Частично",
  qualified: "Квалифицировано",
  processing: "В работе",
  received_at_shipment_warehouse: "Принят на складе отправления",
  rejected: "Отклонён",
  returned: "Возвращён",
  returned_to_sender: "Возвращён отправителю",
  quarantine: "Карантин",
  restock: "На склад",
  scrap: "Утилизация",
  replace: "Замена",
  resolved: "Решён",
  revoked: "Отозван",
  running_onboarding: "Проверяется",
  blocked_onboarding: "Заблокировано",
  rolled_back_onboarding: "Откат выполнен",
  supported: "Поддерживается",
  verified: "Проверено",
  succeeded: "Успешно",
  "server-side": "На сервере",
  unknown: "Неизвестно",
  unavailable: "Недоступен",
  warning: "Предупреждение",
};

export function StatusBadge({value}: {value: string}) {
  const normalized = value.trim().toLowerCase();
  return <span className={`status status-${normalized.replace(/[^a-z0-9]+/g, "-")}`}>{statusLabels[normalized] ?? value}</span>;
}
