import {useEffect,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../../api/ApiProvider";
import {decodeItems as decode} from "../../api/decoders";
import {useAuth} from "../../auth/AuthProvider";
import {ErrorBlock,LoadingBlock} from "../../components/ApiState";
import {EmptyState} from "../../components/EmptyState";
import {StatusBadge} from "../../components/StatusBadge";

interface Member{id:string;email:string;display_name:string;oidc_subject?:string;role:"admin"|"manager"|"operator"|"viewer";status:"invited"|"active"|"disabled";version:number;invited_at:string;updated_at:string}
interface MemberProfile{username:string;email:string;given_name:string;family_name:string;birthdate?:string;job_title?:string;department?:string;phone_number?:string;picture_source:"none"|"identity_provider"|"uploaded";version:number}
const roles={admin:"Администратор",manager:"Менеджер",operator:"Оператор",viewer:"Наблюдатель"};
const statuses={invited:"Приглашён",active:"Активен",disabled:"Заблокирован"};

export function MemberSettings(){
 const api=useApi(),auth=useAuth(),cache=useQueryClient(),canWrite=auth.session?.capabilities.includes("settings.members.write")??false;
 const [email,setEmail]=useState(""),[name,setName]=useState(""),[role,setRole]=useState<keyof typeof roles>("viewer");
 const [selectedProfileID,setSelectedProfileID]=useState<string>();
 const [profileDraft,setProfileDraft]=useState({given_name:"",family_name:"",birthdate:"",job_title:"",department:"",phone_number:""});
 const query=useQuery({queryKey:["settings","members"],queryFn:async()=>decode((await api.listWorkspaceMembers({limit:100})).body),enabled:auth.session?.capabilities.includes("settings.members.read")??false});
 const profileQuery=useQuery({queryKey:["settings","member-profile",selectedProfileID],queryFn:async()=>{if(!selectedProfileID)throw new Error("member profile is not selected");const body=(await api.getWorkspaceMemberProfile({memberId:selectedProfileID})).body as unknown;return body as MemberProfile},enabled:Boolean(selectedProfileID)});
 const invite=useMutation({mutationFn:()=>api.inviteWorkspaceMember({idempotencyKey:crypto.randomUUID(),body:{email,display_name:name,role}}),onSuccess:async()=>{setEmail("");setName("");await cache.invalidateQueries({queryKey:["settings","members"]})}});
 const update=useMutation({mutationFn:({member,changes}:{member:Member;changes:Partial<Pick<Member,"role"|"status">>})=>api.updateWorkspaceMember({memberId:member.id,idempotencyKey:crypto.randomUUID(),body:{role:changes.role??member.role,status:changes.status??member.status,expected_version:member.version}}),onSuccess:async()=>cache.invalidateQueries({queryKey:["settings","members"]})});
 const updateProfile=useMutation({mutationFn:async()=>{if(!selectedProfileID||!profileQuery.data)throw new Error("Профиль участника ещё загружается");return api.updateWorkspaceMemberProfile({memberId:selectedProfileID,idempotencyKey:crypto.randomUUID(),body:{...profileDraft,version:profileQuery.data.version}})},onSuccess:async(response)=>{cache.setQueryData(["settings","member-profile",selectedProfileID],response.body);}});
 useEffect(()=>{if(profileQuery.data)setProfileDraft({given_name:profileQuery.data.given_name,family_name:profileQuery.data.family_name,birthdate:profileQuery.data.birthdate??"",job_title:profileQuery.data.job_title??"",department:profileQuery.data.department??"",phone_number:profileQuery.data.phone_number??""})},[profileQuery.data]);
 if(!(auth.session?.capabilities.includes("settings.members.read")??false))return null;
 return <section className="panel settings-card member-settings"><div className="settings-card-heading"><div><p className="eyebrow">Команда</p><h2>Пользователи и роли</h2><p className="settings-copy">Локальные роли workspace выдаются явно и не наследуются автоматически из внешних групп.</p></div></div>
 {canWrite?<form className="member-invite" onSubmit={event=>{event.preventDefault();invite.mutate()}}><label className="field"><span>Email</span><input required type="email" maxLength={254} value={email} onChange={event=>setEmail(event.target.value)} placeholder="user@example.com"/></label><label className="field"><span>Имя</span><input maxLength={160} value={name} onChange={event=>setName(event.target.value)} placeholder="Имя пользователя"/></label><label className="field"><span>Роль</span><select value={role} onChange={event=>setRole(event.target.value as keyof typeof roles)}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="button primary" disabled={invite.isPending}>{invite.isPending?"Приглашаем…":"Пригласить"}</button></form>:null}
 {invite.isError?<ErrorBlock>Не удалось пригласить: email уже используется или данные некорректны.</ErrorBlock>:null}{update.isError?<ErrorBlock>Не удалось изменить участника. Нельзя заблокировать или понизить последнего активного администратора.</ErrorBlock>:null}
 {query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить пользователей workspace.</ErrorBlock>:query.data.length===0?<EmptyState title="Пользователей пока нет" text="Пригласите первого участника и назначьте минимально необходимую роль."/>:<div className="table-wrap"><table><thead><tr><th>Пользователь</th><th>Роль</th><th>Статус</th><th>Приглашён</th><th>Действия</th></tr></thead><tbody>{query.data.map(member=><tr key={member.id}><td><strong>{member.display_name||member.email}</strong><br/><span>{member.email}</span>{member.oidc_subject?<><br/><span className="mono">{member.oidc_subject}</span></>:null}</td><td>{canWrite?<select disabled={update.isPending} value={member.role} onChange={event=>update.mutate({member,changes:{role:event.target.value as Member["role"]}})}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>:roles[member.role as keyof typeof roles]}</td><td><StatusBadge value={statuses[member.status as keyof typeof statuses]}/></td><td>{new Date(member.invited_at).toLocaleString("ru-RU")}</td><td><button className="button ghost compact" onClick={()=>setSelectedProfileID(member.id)}>{selectedProfileID===member.id?"Выбран":"Профиль"}</button>{canWrite?<button className={member.status==="disabled"?"button primary":"button danger"} disabled={update.isPending} onClick={()=>update.mutate({member,changes:{status:member.status==="disabled"?"active":"disabled"}})}>{member.status==="disabled"?"Разблокировать":"Заблокировать"}</button>:null}</td></tr>)}</tbody></table></div>}
 {selectedProfileID?<section className="member-profile-editor"><div className="settings-card-heading"><div><p className="eyebrow">Профиль участника</p><h3>Данные пользователя</h3><p className="settings-copy">Провайдерские имя пользователя и email доступны только для чтения. Остальные поля можно изменить администратору.</p></div><button type="button" className="button ghost compact" onClick={()=>setSelectedProfileID(undefined)}>Закрыть</button></div>{profileQuery.isPending?<LoadingBlock/>:profileQuery.isError?<ErrorBlock retry={()=>void profileQuery.refetch()}>Не удалось загрузить профиль участника.</ErrorBlock>:profileQuery.data?<form onSubmit={event=>{event.preventDefault();updateProfile.mutate()}}><div className="settings-form"><label className="field"><span>Имя</span><input value={profileDraft.given_name} maxLength={160} onChange={event=>setProfileDraft(current=>({...current,given_name:event.target.value}))}/></label><label className="field"><span>Фамилия</span><input value={profileDraft.family_name} maxLength={160} onChange={event=>setProfileDraft(current=>({...current,family_name:event.target.value}))}/></label><label className="field"><span>Дата рождения</span><input type="date" value={profileDraft.birthdate} onChange={event=>setProfileDraft(current=>({...current,birthdate:event.target.value}))}/></label><label className="field"><span>Должность</span><input value={profileDraft.job_title} maxLength={160} onChange={event=>setProfileDraft(current=>({...current,job_title:event.target.value}))}/></label><label className="field"><span>Отдел</span><input value={profileDraft.department} maxLength={160} onChange={event=>setProfileDraft(current=>({...current,department:event.target.value}))}/></label><label className="field"><span>Телефон</span><input value={profileDraft.phone_number} maxLength={64} onChange={event=>setProfileDraft(current=>({...current,phone_number:event.target.value}))}/></label></div><div className="member-profile-meta"><span>{profileQuery.data.email||"Email не указан"}</span><span>Версия {profileQuery.data.version}</span></div>{updateProfile.isError?<ErrorBlock retry={()=>updateProfile.reset()}>Не удалось сохранить профиль участника. Повторите попытку.</ErrorBlock>:null}<div className="profile-editor-actions"><button type="submit" className="button primary" disabled={updateProfile.isPending}>{updateProfile.isPending?"Сохраняем…":"Сохранить профиль"}</button></div></form>:null}</section>:null}</section>
}
