// Code generated by torgnexa-sdkgen/v1; DO NOT EDIT.
// Source: contracts/openapi/torgnexa-v1.yaml sha256=97cd3d29d0c53cd6394a7d4a2280242ee816d2611ee52a8cf9500032be9ca770

export const API_VERSION = "0.21.2";
export const OPENAPI_VERSION = "3.1.0";
export const DEFAULT_SERVER_PATH = "/api/v1";
export const GENERATOR_VERSION = "torgnexa-sdkgen/v1";

export class APIError extends Error {
  constructor(statusCode, body) {
    super(`TORGNEXA API returned HTTP ${statusCode}`);
    this.name = "APIError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export class TorgnexaClient {
  constructor(config) {
    if (!config || typeof config.baseURL !== "string" || config.baseURL.trim() === "") throw new TypeError("baseURL is required");
    const parsed = new URL(config.baseURL);
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") throw new TypeError("baseURL must use http or https");
    parsed.search = "";
    parsed.hash = "";
    this.baseURL = parsed.toString().replace(/\/$/, "");
    this.bearerToken = config.bearerToken || "";
    this.fetchImpl = config.fetch || globalThis.fetch;
    if (typeof this.fetchImpl !== "function") throw new TypeError("fetch implementation is required");
    this.userAgent = config.userAgent || ("torgnexa-typescript-sdk/" + API_VERSION);
  }

  async _request(method, path, query, body, options = {}) {
    const endpoint = new URL(this.baseURL + path);
    for (const [key, value] of Object.entries(query || {})) {
      if (value !== undefined && value !== null && value !== "" && value !== 0 && value !== false) endpoint.searchParams.set(key, String(value));
    }
    const headers = { Accept: "application/json", ...(options.headers || {}) };
    if (body !== undefined && body !== null) headers["Content-Type"] = "application/json";
    if (this.bearerToken) headers.Authorization = "Bearer " + this.bearerToken;
    const raw = await this.fetchImpl(endpoint, { method, headers, body: body === undefined || body === null ? undefined : JSON.stringify(body), signal: options.signal });
    let payload = null;
    const contentType = (raw.headers.get("content-type") || "").split(";", 1)[0].trim().toLowerCase();
    const binary = contentType !== "" && !contentType.startsWith("text/") && !contentType.includes("json") && !contentType.includes("xml");
    if (binary) {
      payload = await raw.arrayBuffer();
    } else {
      const text = await raw.text();
      if (text !== "") { try { payload = JSON.parse(text); } catch { payload = text; } }
    }
    const response = { statusCode: raw.status, headers: raw.headers, body: payload };
    if (raw.status < 200 || raw.status >= 300) throw new APIError(raw.status, payload);
    return response;
  }

  async activateSettingsIdentityProvider(input = {}, options = {}) {
    let path = "/settings/identity-providers/{provider_id}:activate";
    if (typeof input.providerId !== "string" || input.providerId.trim() === "") throw new TypeError("provider_id is required");
    path = path.replace("{provider_id}", encodeURIComponent(input.providerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async adjustInventoryPosition(input = {}, options = {}) {
    let path = "/inventory/positions/{position_id}/adjustments";
    if (typeof input.positionId !== "string" || input.positionId.trim() === "") throw new TypeError("position_id is required");
    path = path.replace("{position_id}", encodeURIComponent(input.positionId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async analyzeWithAIProvider(input = {}, options = {}) {
    let path = "/settings/ai-providers:analyze";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async archiveWorkflow(input = {}, options = {}) {
    let path = "/workflow-commands/archive";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async assignProductCategory(input = {}, options = {}) {
    let path = "/products/{product_id}/categories/{category_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.categoryId !== "string" || input.categoryId.trim() === "") throw new TypeError("category_id is required");
    path = path.replace("{category_id}", encodeURIComponent(input.categoryId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async cancelWorkflowRun(input = {}, options = {}) {
    let path = "/workflow-run-commands/cancel";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async changeOrderStatus(input = {}, options = {}) {
    let path = "/orders/{order_id}/status";
    if (typeof input.orderId !== "string" || input.orderId.trim() === "") throw new TypeError("order_id is required");
    path = path.replace("{order_id}", encodeURIComponent(input.orderId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async checkConnectorAccount(input = {}, options = {}) {
    let path = "/connector-accounts:check";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async completeConnectorOAuth(input = {}, options = {}) {
    let path = "/connector-accounts:oauth-callback";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createAIProviderAccount(input = {}, options = {}) {
    let path = "/settings/ai-providers";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createApprovalPolicy(input = {}, options = {}) {
    let path = "/approval-policies";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createApprovalRequest(input = {}, options = {}) {
    let path = "/approvals/requests";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createCatalogCategory(input = {}, options = {}) {
    let path = "/catalog/categories";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createConnectorAccount(input = {}, options = {}) {
    let path = "/connector-accounts";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createCurrentUserProfilePrivacyRequest(input = {}, options = {}) {
    let path = "/me/profile/privacy-requests";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createDemoApproval(input = {}, options = {}) {
    let path = "/approvals/demo";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async createDemoOrders(input = {}, options = {}) {
    let path = "/orders/demo";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async createInventoryWarehouse(input = {}, options = {}) {
    let path = "/inventory/warehouses";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createMCPAccount(input = {}, options = {}) {
    let path = "/settings/mcp-accounts";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createOfferPrice(input = {}, options = {}) {
    let path = "/products/{product_id}/prices/{offer_or_price_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.offerOrPriceId !== "string" || input.offerOrPriceId.trim() === "") throw new TypeError("offer_or_price_id is required");
    path = path.replace("{offer_or_price_id}", encodeURIComponent(input.offerOrPriceId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createPayment(input = {}, options = {}) {
    let path = "/payments";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createPrivacyRequest(input = {}, options = {}) {
    let path = "/privacy/requests";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createProduct(input = {}, options = {}) {
    let path = "/products";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createProductImage(input = {}, options = {}) {
    let path = "/products/{product_id}/images";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createProductOffer(input = {}, options = {}) {
    let path = "/products/{product_id}/offers";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createProfitabilityScenario(input = {}, options = {}) {
    let path = "/profitability/scenarios";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createReconciliationJob(input = {}, options = {}) {
    let path = "/reconciliation/jobs";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createSocialChannel(input = {}, options = {}) {
    let path = "/social/channels";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createSocialPublication(input = {}, options = {}) {
    let path = "/social/publications";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createSyncPolicy(input = {}, options = {}) {
    let path = "/sync/policies";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createUpload(input = {}, options = {}) {
    let path = "/uploads";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createWebhookSubscription(input = {}, options = {}) {
    let path = "/webhook-subscriptions";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async createWorkflow(input = {}, options = {}) {
    let path = "/workflows";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async decideApproval(input = {}, options = {}) {
    let path = "/approvals/{request_id}/decision";
    if (typeof input.requestId !== "string" || input.requestId.trim() === "") throw new TypeError("request_id is required");
    path = path.replace("{request_id}", encodeURIComponent(input.requestId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async deleteCurrentUserAvatar(input = {}, options = {}) {
    let path = "/me/profile/avatar";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("DELETE", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async deleteDemoOrders(input = {}, options = {}) {
    let path = "/orders/demo";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("DELETE", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async deleteProductImage(input = {}, options = {}) {
    let path = "/products/{product_id}/images/{image_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.imageId !== "string" || input.imageId.trim() === "") throw new TypeError("image_id is required");
    path = path.replace("{image_id}", encodeURIComponent(input.imageId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("DELETE", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async disableAIProviderAccount(input = {}, options = {}) {
    let path = "/settings/ai-providers:disable";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async disableConnectorAccount(input = {}, options = {}) {
    let path = "/connector-accounts:disable";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async disableMCPAccount(input = {}, options = {}) {
    let path = "/settings/mcp-accounts:disable";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async disableSettingsIdentityProvider(input = {}, options = {}) {
    let path = "/settings/identity-providers/{provider_id}:disable";
    if (typeof input.providerId !== "string" || input.providerId.trim() === "") throw new TypeError("provider_id is required");
    path = path.replace("{provider_id}", encodeURIComponent(input.providerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async disableWebhookSubscription(input = {}, options = {}) {
    let path = "/webhook-subscriptions/{subscription_id}";
    if (typeof input.subscriptionId !== "string" || input.subscriptionId.trim() === "") throw new TypeError("subscription_id is required");
    path = path.replace("{subscription_id}", encodeURIComponent(input.subscriptionId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("DELETE", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async enableConnectorAccount(input = {}, options = {}) {
    let path = "/connector-accounts:enable";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async enrollConnectorCredentials(input = {}, options = {}) {
    let path = "/connector-accounts:credentials";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async evaluateEntitlement(input = {}, options = {}) {
    let path = "/entitlements/evaluate";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async evaluateProductCompliance(input = {}, options = {}) {
    let path = "/compliance/evaluate";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async executeApproval(input = {}, options = {}) {
    let path = "/approvals/{request_id}/execute";
    if (typeof input.requestId !== "string" || input.requestId.trim() === "") throw new TypeError("request_id is required");
    path = path.replace("{request_id}", encodeURIComponent(input.requestId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getAIEgressPolicy(options = {}) {
    let path = "/settings/ai-egress-policy";
    return this._request("GET", path, {}, undefined, options);
  }

  async getCloudSubscription(options = {}) {
    let path = "/cloud/subscription";
    return this._request("GET", path, {}, undefined, options);
  }

  async getConnectorBootstrapState(options = {}) {
    let path = "/connector-accounts:bootstrap";
    return this._request("GET", path, {}, undefined, options);
  }

  async getConnectorRuntimeConfig(input = {}, options = {}) {
    let path = "/connector-accounts:runtime-config";
    const query = {};
    if (typeof input.accountId !== "string" || input.accountId.trim() === "") throw new TypeError("account_id is required");
    if (input.accountId !== undefined) query["account_id"] = input.accountId;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getCurrentUserProfile(options = {}) {
    let path = "/me/profile";
    return this._request("GET", path, {}, undefined, options);
  }

  async getFulfillmentAllocation(input = {}, options = {}) {
    let path = "/inventory/fulfillment-allocations/{allocation_id}";
    if (typeof input.allocationId !== "string" || input.allocationId.trim() === "") throw new TypeError("allocation_id is required");
    path = path.replace("{allocation_id}", encodeURIComponent(input.allocationId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getHealth(options = {}) {
    let path = "/health";
    return this._request("GET", path, {}, undefined, options);
  }

  async getInventoryPosition(input = {}, options = {}) {
    let path = "/inventory/positions/{position_id}";
    if (typeof input.positionId !== "string" || input.positionId.trim() === "") throw new TypeError("position_id is required");
    path = path.replace("{position_id}", encodeURIComponent(input.positionId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getLineageTimeline(input = {}, options = {}) {
    let path = "/lineage/timeline";
    const query = {};
    if (typeof input.system !== "string" || input.system.trim() === "") throw new TypeError("system is required");
    if (input.system !== undefined) query["system"] = input.system;
    if (typeof input.entityType !== "string" || input.entityType.trim() === "") throw new TypeError("entity_type is required");
    if (input.entityType !== undefined) query["entity_type"] = input.entityType;
    if (typeof input.entityId !== "string" || input.entityId.trim() === "") throw new TypeError("entity_id is required");
    if (input.entityId !== undefined) query["entity_id"] = input.entityId;
    if (input.field !== undefined) query["field"] = input.field;
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.beforeAt !== undefined) query["before_at"] = input.beforeAt;
    if (input.beforeId !== undefined) query["before_id"] = input.beforeId;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getMCPAccountPolicy(input = {}, options = {}) {
    let path = "/settings/mcp-accounts/{account_id}:policy";
    if (typeof input.accountId !== "string" || input.accountId.trim() === "") throw new TypeError("account_id is required");
    path = path.replace("{account_id}", encodeURIComponent(input.accountId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getMCPAgentKillSwitch(options = {}) {
    let path = "/settings/mcp-agents:kill-switch";
    return this._request("GET", path, {}, undefined, options);
  }

  async getNotificationPreference(input = {}, options = {}) {
    let path = "/notification-preferences/{channel}";
    if (typeof input.channel !== "string" || input.channel.trim() === "") throw new TypeError("channel is required");
    path = path.replace("{channel}", encodeURIComponent(input.channel));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getOrder(input = {}, options = {}) {
    let path = "/orders/{order_id}";
    if (typeof input.orderId !== "string" || input.orderId.trim() === "") throw new TypeError("order_id is required");
    path = path.replace("{order_id}", encodeURIComponent(input.orderId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getPayment(input = {}, options = {}) {
    let path = "/payments/{payment_id}";
    if (typeof input.paymentId !== "string" || input.paymentId.trim() === "") throw new TypeError("payment_id is required");
    path = path.replace("{payment_id}", encodeURIComponent(input.paymentId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getProduct(input = {}, options = {}) {
    let path = "/products/{product_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getReportData(input = {}, options = {}) {
    let path = "/reports/{report_id}";
    if (typeof input.reportId !== "string" || input.reportId.trim() === "") throw new TypeError("report_id is required");
    path = path.replace("{report_id}", encodeURIComponent(input.reportId));
    const query = {};
    if (input.from !== undefined) query["from"] = input.from;
    if (input.to !== undefined) query["to"] = input.to;
    if (input.q !== undefined) query["q"] = input.q;
    if (input.currency !== undefined) query["currency"] = input.currency;
    if (input.status !== undefined) query["status"] = input.status;
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.format !== undefined) query["format"] = input.format;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getRuntimeSecurityPosture(options = {}) {
    let path = "/settings/security/posture";
    return this._request("GET", path, {}, undefined, options);
  }

  async getSettingsSecurityConfiguration(options = {}) {
    let path = "/settings/security/configuration";
    return this._request("GET", path, {}, undefined, options);
  }

  async getSyncStatus(options = {}) {
    let path = "/sync/status";
    return this._request("GET", path, {}, undefined, options);
  }

  async getUpload(input = {}, options = {}) {
    let path = "/uploads/{upload_id}";
    if (typeof input.uploadId !== "string" || input.uploadId.trim() === "") throw new TypeError("upload_id is required");
    path = path.replace("{upload_id}", encodeURIComponent(input.uploadId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getUploadContent(input = {}, options = {}) {
    let path = "/uploads/{upload_id}/content";
    if (typeof input.uploadId !== "string" || input.uploadId.trim() === "") throw new TypeError("upload_id is required");
    path = path.replace("{upload_id}", encodeURIComponent(input.uploadId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWarehouseIncident(input = {}, options = {}) {
    let path = "/inventory/warehouse-incidents/{incident_id}";
    if (typeof input.incidentId !== "string" || input.incidentId.trim() === "") throw new TypeError("incident_id is required");
    path = path.replace("{incident_id}", encodeURIComponent(input.incidentId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWarehouseOperationalState(input = {}, options = {}) {
    let path = "/inventory/warehouses/{warehouse_id}/operational-state";
    if (typeof input.warehouseId !== "string" || input.warehouseId.trim() === "") throw new TypeError("warehouse_id is required");
    path = path.replace("{warehouse_id}", encodeURIComponent(input.warehouseId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWebhookDeliveryHistory(input = {}, options = {}) {
    let path = "/webhook-deliveries/{delivery_id}/history";
    if (typeof input.deliveryId !== "string" || input.deliveryId.trim() === "") throw new TypeError("delivery_id is required");
    path = path.replace("{delivery_id}", encodeURIComponent(input.deliveryId));
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWorkflow(input = {}, options = {}) {
    let path = "/workflows/{workflow_id}";
    if (typeof input.workflowId !== "string" || input.workflowId.trim() === "") throw new TypeError("workflow_id is required");
    path = path.replace("{workflow_id}", encodeURIComponent(input.workflowId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWorkflowRun(input = {}, options = {}) {
    let path = "/workflow-runs/{run_id}";
    if (typeof input.runId !== "string" || input.runId.trim() === "") throw new TypeError("run_id is required");
    path = path.replace("{run_id}", encodeURIComponent(input.runId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWorkspaceMemberProfile(input = {}, options = {}) {
    let path = "/settings/members/{member_id}/profile";
    if (typeof input.memberId !== "string" || input.memberId.trim() === "") throw new TypeError("member_id is required");
    path = path.replace("{member_id}", encodeURIComponent(input.memberId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async getWorkspaceSettings(options = {}) {
    let path = "/settings/workspace";
    return this._request("GET", path, {}, undefined, options);
  }

  async importInventory(input = {}, options = {}) {
    let path = "/inventory/import";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async installMCPAccountPolicy(input = {}, options = {}) {
    let path = "/settings/mcp-accounts/{account_id}:install-policy";
    if (typeof input.accountId !== "string" || input.accountId.trim() === "") throw new TypeError("account_id is required");
    path = path.replace("{account_id}", encodeURIComponent(input.accountId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async inviteWorkspaceMember(input = {}, options = {}) {
    let path = "/settings/members";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async listAIProviderAccounts(options = {}) {
    let path = "/settings/ai-providers";
    return this._request("GET", path, {}, undefined, options);
  }

  async listApprovalPolicies(options = {}) {
    let path = "/approval-policies";
    return this._request("GET", path, {}, undefined, options);
  }

  async listApprovals(options = {}) {
    let path = "/approvals";
    return this._request("GET", path, {}, undefined, options);
  }

  async listAuditRecords(input = {}, options = {}) {
    let path = "/audit";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listCatalogCategories(options = {}) {
    let path = "/catalog/categories";
    return this._request("GET", path, {}, undefined, options);
  }

  async listComplianceDocuments(options = {}) {
    let path = "/compliance/documents";
    return this._request("GET", path, {}, undefined, options);
  }

  async listConnectorAccountHealthHistory(input = {}, options = {}) {
    let path = "/connector-accounts:health-history";
    const query = {};
    if (typeof input.accountId !== "string" || input.accountId.trim() === "") throw new TypeError("account_id is required");
    if (input.accountId !== undefined) query["account_id"] = input.accountId;
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listConnectorAccounts(input = {}, options = {}) {
    let path = "/connector-accounts";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listConnectors(options = {}) {
    let path = "/connectors";
    return this._request("GET", path, {}, undefined, options);
  }

  async listCounterparties(input = {}, options = {}) {
    let path = "/counterparties";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listFXRates(input = {}, options = {}) {
    let path = "/fx/rates";
    const query = {};
    if (input.base !== undefined) query["base"] = input.base;
    if (input.quote !== undefined) query["quote"] = input.quote;
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listFulfillmentAllocations(options = {}) {
    let path = "/inventory/fulfillment-allocations";
    return this._request("GET", path, {}, undefined, options);
  }

  async listInventoryPositions(options = {}) {
    let path = "/inventory/positions";
    return this._request("GET", path, {}, undefined, options);
  }

  async listInventoryWarehouses(options = {}) {
    let path = "/inventory/warehouses";
    return this._request("GET", path, {}, undefined, options);
  }

  async listLogisticsPickupPoints(input = {}, options = {}) {
    let path = "/logistics/pickup-points";
    const query = {};
    if (typeof input.connectorAccountId !== "string" || input.connectorAccountId.trim() === "") throw new TypeError("connector_account_id is required");
    if (input.connectorAccountId !== undefined) query["connector_account_id"] = input.connectorAccountId;
    if (typeof input.country !== "string" || input.country.trim() === "") throw new TypeError("country is required");
    if (input.country !== undefined) query["country"] = input.country;
    if (typeof input.city !== "string" || input.city.trim() === "") throw new TypeError("city is required");
    if (input.city !== undefined) query["city"] = input.city;
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listMCPAccounts(options = {}) {
    let path = "/settings/mcp-accounts";
    return this._request("GET", path, {}, undefined, options);
  }

  async listNotificationDeliveries(input = {}, options = {}) {
    let path = "/notifications/{notification_id}/deliveries";
    if (typeof input.notificationId !== "string" || input.notificationId.trim() === "") throw new TypeError("notification_id is required");
    path = path.replace("{notification_id}", encodeURIComponent(input.notificationId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listNotifications(input = {}, options = {}) {
    let path = "/notifications";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listOrders(input = {}, options = {}) {
    let path = "/orders";
    const query = {};
    if (input.q !== undefined) query["q"] = input.q;
    if (input.status !== undefined) query["status"] = input.status;
    if (input.placedFrom !== undefined) query["placed_from"] = input.placedFrom;
    if (input.placedTo !== undefined) query["placed_to"] = input.placedTo;
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listPayments(input = {}, options = {}) {
    let path = "/payments";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listPlugins(input = {}, options = {}) {
    let path = "/plugins";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listProducts(input = {}, options = {}) {
    let path = "/products";
    const query = {};
    if (input.q !== undefined) query["q"] = input.q;
    if (input.status !== undefined) query["status"] = input.status;
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listReports(options = {}) {
    let path = "/reports";
    return this._request("GET", path, {}, undefined, options);
  }

  async listSecurityEvidence(input = {}, options = {}) {
    let path = "/settings/security/evidence";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.before !== undefined) query["before"] = input.before;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSettingsIdentityProviders(options = {}) {
    let path = "/settings/identity-providers";
    return this._request("GET", path, {}, undefined, options);
  }

  async listSettingsSecurityAudit(input = {}, options = {}) {
    let path = "/settings/security/audit";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSettingsSecurityLogins(input = {}, options = {}) {
    let path = "/settings/security/logins";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSettingsSecuritySessions(input = {}, options = {}) {
    let path = "/settings/security/sessions";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSettlementEntries(input = {}, options = {}) {
    let path = "/settlements";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSocialChannels(input = {}, options = {}) {
    let path = "/social/channels";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listSocialPublications(input = {}, options = {}) {
    let path = "/social/publications";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listWarehouseIncidents(options = {}) {
    let path = "/inventory/warehouse-incidents";
    return this._request("GET", path, {}, undefined, options);
  }

  async listWebhookSubscriptions(options = {}) {
    let path = "/webhook-subscriptions";
    return this._request("GET", path, {}, undefined, options);
  }

  async listWorkflowRunEvidence(input = {}, options = {}) {
    let path = "/workflow-runs/{run_id}/evidence";
    if (typeof input.runId !== "string" || input.runId.trim() === "") throw new TypeError("run_id is required");
    path = path.replace("{run_id}", encodeURIComponent(input.runId));
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listWorkflowRunSteps(input = {}, options = {}) {
    let path = "/workflow-runs/{run_id}/steps";
    if (typeof input.runId !== "string" || input.runId.trim() === "") throw new TypeError("run_id is required");
    path = path.replace("{run_id}", encodeURIComponent(input.runId));
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listWorkflowRuns(input = {}, options = {}) {
    let path = "/workflow-runs";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listWorkflows(input = {}, options = {}) {
    let path = "/workflows";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async listWorkspaceMembers(input = {}, options = {}) {
    let path = "/settings/members";
    const query = {};
    if (input.limit !== undefined) query["limit"] = input.limit;
    if (input.cursor !== undefined) query["cursor"] = input.cursor;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async markNotificationRead(input = {}, options = {}) {
    let path = "/notifications/{notification_id}/read";
    if (typeof input.notificationId !== "string" || input.notificationId.trim() === "") throw new TypeError("notification_id is required");
    path = path.replace("{notification_id}", encodeURIComponent(input.notificationId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async pauseWorkflow(input = {}, options = {}) {
    let path = "/workflow-commands/pause";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async previewAIEgress(input = {}, options = {}) {
    let path = "/settings/ai-egress-policy:preview";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async previewConnectorBootstrap(input = {}, options = {}) {
    let path = "/connector-accounts:bootstrap-preview";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async publishWorkflow(input = {}, options = {}) {
    let path = "/workflow-commands/publish";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async putAIEgressPolicy(input = {}, options = {}) {
    let path = "/settings/ai-egress-policy";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async putConnectorRuntimeConfig(input = {}, options = {}) {
    let path = "/connector-accounts:runtime-config";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async putConnectorSyncSchedule(input = {}, options = {}) {
    let path = "/connector-accounts:schedule";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async putNotificationPreference(input = {}, options = {}) {
    let path = "/notification-preferences/{channel}";
    if (typeof input.channel !== "string" || input.channel.trim() === "") throw new TypeError("channel is required");
    path = path.replace("{channel}", encodeURIComponent(input.channel));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async putWarehouseFailoverRoute(input = {}, options = {}) {
    let path = "/inventory/warehouses/{warehouse_id}/failover-routes/{destination_warehouse_id}";
    if (typeof input.warehouseId !== "string" || input.warehouseId.trim() === "") throw new TypeError("warehouse_id is required");
    path = path.replace("{warehouse_id}", encodeURIComponent(input.warehouseId));
    if (typeof input.destinationWarehouseId !== "string" || input.destinationWarehouseId.trim() === "") throw new TypeError("destination_warehouse_id is required");
    path = path.replace("{destination_warehouse_id}", encodeURIComponent(input.destinationWarehouseId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async refundPayment(input = {}, options = {}) {
    let path = "/payments/{payment_id}/refund";
    if (typeof input.paymentId !== "string" || input.paymentId.trim() === "") throw new TypeError("payment_id is required");
    path = path.replace("{payment_id}", encodeURIComponent(input.paymentId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async replaceConnectorAccountCapabilities(input = {}, options = {}) {
    let path = "/connector-accounts:capabilities";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async replayWebhookDelivery(input = {}, options = {}) {
    let path = "/webhook-deliveries/{delivery_id}/replay";
    if (typeof input.deliveryId !== "string" || input.deliveryId.trim() === "") throw new TypeError("delivery_id is required");
    path = path.replace("{delivery_id}", encodeURIComponent(input.deliveryId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async reserveFulfillmentAllocation(input = {}, options = {}) {
    let path = "/inventory/fulfillment-allocations";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async resolveSyncDrift(input = {}, options = {}) {
    let path = "/sync/drifts/{drift_id}/actions";
    if (typeof input.driftId !== "string" || input.driftId.trim() === "") throw new TypeError("drift_id is required");
    path = path.replace("{drift_id}", encodeURIComponent(input.driftId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async retireApprovalPolicy(input = {}, options = {}) {
    let path = "/approval-policies/{policy_id}";
    if (typeof input.policyId !== "string" || input.policyId.trim() === "") throw new TypeError("policy_id is required");
    path = path.replace("{policy_id}", encodeURIComponent(input.policyId));
    const query = {};
    if (input.expectedVersion !== undefined) query["expected_version"] = input.expectedVersion;
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("DELETE", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async retryWorkflowRun(input = {}, options = {}) {
    let path = "/workflow-run-commands/retry";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async revokeSettingsSecuritySession(input = {}, options = {}) {
    let path = "/settings/security/sessions/{session_ref}:revoke";
    if (typeof input.sessionRef !== "string" || input.sessionRef.trim() === "") throw new TypeError("session_ref is required");
    path = path.replace("{session_ref}", encodeURIComponent(input.sessionRef));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async rollbackSettingsIdentityProvider(input = {}, options = {}) {
    let path = "/settings/identity-providers/{provider_id}:rollback";
    if (typeof input.providerId !== "string" || input.providerId.trim() === "") throw new TypeError("provider_id is required");
    path = path.replace("{provider_id}", encodeURIComponent(input.providerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async rotateMCPAccount(input = {}, options = {}) {
    let path = "/settings/mcp-accounts:rotate";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async rotateWebhookSigningSecret(input = {}, options = {}) {
    let path = "/webhook-subscriptions/{subscription_id}/rotate-secret";
    if (typeof input.subscriptionId !== "string" || input.subscriptionId.trim() === "") throw new TypeError("subscription_id is required");
    path = path.replace("{subscription_id}", encodeURIComponent(input.subscriptionId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async runConnectorReplay(input = {}, options = {}) {
    let path = "/settings/connector-replay:run";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async runSyncPolicy(input = {}, options = {}) {
    let path = "/sync/policies/{policy_id}/run";
    if (typeof input.policyId !== "string" || input.policyId.trim() === "") throw new TypeError("policy_id is required");
    path = path.replace("{policy_id}", encodeURIComponent(input.policyId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async runWorkflow(input = {}, options = {}) {
    let path = "/workflow-commands/run";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async saveSettingsIdentityProviderDraft(input = {}, options = {}) {
    let path = "/settings/identity-providers/{provider_id}";
    if (typeof input.providerId !== "string" || input.providerId.trim() === "") throw new TypeError("provider_id is required");
    path = path.replace("{provider_id}", encodeURIComponent(input.providerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async searchLegalParties(input = {}, options = {}) {
    let path = "/counterparties/search";
    const query = {};
    if (input.q !== undefined) query["q"] = input.q;
    if (input.inn !== undefined) query["inn"] = input.inn;
    if (input.registrationId !== undefined) query["registration_id"] = input.registrationId;
    if (input.partyType !== undefined) query["party_type"] = input.partyType;
    if (input.limit !== undefined) query["limit"] = input.limit;
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("GET", path, query, undefined, { ...options, headers: requestHeaders });
  }

  async setMCPAgentKillSwitch(input = {}, options = {}) {
    let path = "/settings/mcp-agents:kill-switch";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async startConnectorBootstrap(input = {}, options = {}) {
    let path = "/connector-accounts:bootstrap";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async startConnectorOAuth(input = {}, options = {}) {
    let path = "/connector-accounts:oauth-start";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async streamRealtimeInvalidations(options = {}) {
    let path = "/realtime";
    return this._request("GET", path, {}, undefined, options);
  }

  async syncConnectorAccount(input = {}, options = {}) {
    let path = "/connector-accounts:sync";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateCurrentUserProfile(input = {}, options = {}) {
    let path = "/me/profile";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateInventoryWarehouse(input = {}, options = {}) {
    let path = "/inventory/warehouses/{warehouse_id}";
    if (typeof input.warehouseId !== "string" || input.warehouseId.trim() === "") throw new TypeError("warehouse_id is required");
    path = path.replace("{warehouse_id}", encodeURIComponent(input.warehouseId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateOfferPrice(input = {}, options = {}) {
    let path = "/products/{product_id}/prices/{offer_or_price_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.offerOrPriceId !== "string" || input.offerOrPriceId.trim() === "") throw new TypeError("offer_or_price_id is required");
    path = path.replace("{offer_or_price_id}", encodeURIComponent(input.offerOrPriceId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateProduct(input = {}, options = {}) {
    let path = "/products/{product_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateProductImage(input = {}, options = {}) {
    let path = "/products/{product_id}/images/{image_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.imageId !== "string" || input.imageId.trim() === "") throw new TypeError("image_id is required");
    path = path.replace("{image_id}", encodeURIComponent(input.imageId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateProductOffer(input = {}, options = {}) {
    let path = "/products/{product_id}/offers/{offer_id}";
    if (typeof input.productId !== "string" || input.productId.trim() === "") throw new TypeError("product_id is required");
    path = path.replace("{product_id}", encodeURIComponent(input.productId));
    if (typeof input.offerId !== "string" || input.offerId.trim() === "") throw new TypeError("offer_id is required");
    path = path.replace("{offer_id}", encodeURIComponent(input.offerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateSocialChannel(input = {}, options = {}) {
    let path = "/social/channels/{channel_id}";
    if (typeof input.channelId !== "string" || input.channelId.trim() === "") throw new TypeError("channel_id is required");
    path = path.replace("{channel_id}", encodeURIComponent(input.channelId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateSyncPolicy(input = {}, options = {}) {
    let path = "/sync/policies/{policy_id}";
    if (typeof input.policyId !== "string" || input.policyId.trim() === "") throw new TypeError("policy_id is required");
    path = path.replace("{policy_id}", encodeURIComponent(input.policyId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateWarehouseOperationalState(input = {}, options = {}) {
    let path = "/inventory/warehouses/{warehouse_id}/operational-state";
    if (typeof input.warehouseId !== "string" || input.warehouseId.trim() === "") throw new TypeError("warehouse_id is required");
    path = path.replace("{warehouse_id}", encodeURIComponent(input.warehouseId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateWorkspaceMember(input = {}, options = {}) {
    let path = "/settings/members/{member_id}";
    if (typeof input.memberId !== "string" || input.memberId.trim() === "") throw new TypeError("member_id is required");
    path = path.replace("{member_id}", encodeURIComponent(input.memberId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateWorkspaceMemberProfile(input = {}, options = {}) {
    let path = "/settings/members/{member_id}/profile";
    if (typeof input.memberId !== "string" || input.memberId.trim() === "") throw new TypeError("member_id is required");
    path = path.replace("{member_id}", encodeURIComponent(input.memberId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PATCH", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async updateWorkspaceSettings(input = {}, options = {}) {
    let path = "/settings/workspace";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("PUT", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async uploadCurrentUserAvatar(input = {}, options = {}) {
    let path = "/me/profile/avatar";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async validateSettingsIdentityProvider(input = {}, options = {}) {
    let path = "/settings/identity-providers/{provider_id}:validate";
    if (typeof input.providerId !== "string" || input.providerId.trim() === "") throw new TypeError("provider_id is required");
    path = path.replace("{provider_id}", encodeURIComponent(input.providerId));
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    if (typeof input.idempotencyKey !== "string" || input.idempotencyKey.trim() === "") throw new TypeError("Idempotency-Key is required");
    if (input.idempotencyKey !== undefined) requestHeaders["Idempotency-Key"] = input.idempotencyKey;
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }

  async validateWorkflow(input = {}, options = {}) {
    let path = "/workflow-commands/validate";
    const query = {};
    const requestHeaders = { ...(options.headers || {}) };
    return this._request("POST", path, query, input.body, { ...options, headers: requestHeaders });
  }
}
