// Code generated by torgnexa-sdkgen/v1; DO NOT EDIT.
// Source: contracts/openapi/torgnexa-v1.yaml sha256=28a3456f8045536742ba829482a7a14008839b1c4f994bfcb9f70a984d81bc94

export const API_VERSION: string;
export const OPENAPI_VERSION: string;
export const DEFAULT_SERVER_PATH: string;
export const GENERATOR_VERSION: string;
export interface APIResponse<T = unknown> { statusCode: number; headers: Headers; body: T; }
export interface RequestOptions { signal?: AbortSignal; headers?: Record<string, string>; }
export interface ClientConfig { baseURL: string; bearerToken?: string; userAgent?: string; fetch?: typeof fetch; }
export class APIError extends Error { statusCode: number; body: unknown; constructor(statusCode: number, body: unknown); }
export interface ActivateSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface AdjustInventoryPositionRequest {
  positionId: string;
  body: unknown;
}
export interface AnalyzeWithAIProviderRequest {
  body: unknown;
}
export interface AssignProductCategoryRequest {
  productId: string;
  categoryId: string;
}
export interface CheckConnectorAccountRequest {
  body: unknown;
}
export interface CompleteConnectorOAuthRequest {
  body: unknown;
}
export interface CreateAIProviderAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateApprovalPolicyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateApprovalRequestRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateCatalogCategoryRequest {
  body: unknown;
}
export interface CreateConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateDemoApprovalRequest {
  idempotencyKey: string;
}
export interface CreateDemoOrdersRequest {
  idempotencyKey?: string;
}
export interface CreateInventoryWarehouseRequest {
  body: unknown;
}
export interface CreateOfferPriceRequest {
  productId: string;
  offerOrPriceId: string;
  body: unknown;
}
export interface CreatePrivacyRequestRequest {
  body: unknown;
}
export interface CreateProductRequest {
  body: unknown;
}
export interface CreateProductImageRequest {
  productId: string;
  body: unknown;
}
export interface CreateProductOfferRequest {
  productId: string;
  body: unknown;
}
export interface CreateReconciliationJobRequest {
  body: unknown;
}
export interface CreateSyncPolicyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateUploadRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWebhookSubscriptionRequest {
  body: unknown;
}
export interface DecideApprovalRequest {
  requestId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface DeleteDemoOrdersRequest {
  idempotencyKey?: string;
}
export interface DisableAIProviderAccountRequest {
  body: unknown;
}
export interface DisableConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DisableSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface DisableWebhookSubscriptionRequest {
  subscriptionId: string;
}
export interface EnableConnectorAccountRequest {
  body: unknown;
}
export interface EnrollConnectorCredentialsRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface EvaluateEntitlementRequest {
  body: unknown;
}
export interface EvaluateProductComplianceRequest {
  body: unknown;
}
export interface ExecuteApprovalRequest {
  requestId: string;
  idempotencyKey: string;
}
export interface GetConnectorRuntimeConfigRequest {
  accountId: string;
}
export interface GetFulfillmentAllocationRequest {
  allocationId: string;
}
export interface GetInventoryPositionRequest {
  positionId: string;
}
export interface GetLineageTimelineRequest {
  system: string;
  entityType: string;
  entityId: string;
  field?: string;
  limit?: number;
  beforeAt?: string;
  beforeId?: string;
}
export interface GetNotificationPreferenceRequest {
  channel: string;
}
export interface GetOrderRequest {
  orderId: string;
}
export interface GetProductRequest {
  productId: string;
}
export interface GetReportDataRequest {
  reportId: string;
  from?: string;
  to?: string;
  q?: string;
  currency?: string;
  status?: string;
  limit?: number;
  format?: string;
}
export interface GetWarehouseIncidentRequest {
  incidentId: string;
}
export interface GetWarehouseOperationalStateRequest {
  warehouseId: string;
}
export interface GetWebhookDeliveryHistoryRequest {
  deliveryId: string;
  limit?: number;
}
export interface ImportInventoryRequest {
  body: unknown;
}
export interface InviteWorkspaceMemberRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ListAuditRecordsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListConnectorAccountHealthHistoryRequest {
  accountId: string;
  limit?: number;
}
export interface ListConnectorAccountsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListNotificationDeliveriesRequest {
  notificationId: string;
}
export interface ListNotificationsRequest {
  limit?: number;
}
export interface ListOrdersRequest {
  q?: string;
  status?: string;
  placedFrom?: string;
  placedTo?: string;
  limit?: number;
  cursor?: string;
}
export interface ListProductsRequest {
  q?: string;
  status?: string;
  limit?: number;
  cursor?: string;
}
export interface ListSettingsSecurityAuditRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettingsSecurityLoginsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettingsSecuritySessionsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettlementEntriesRequest {
  cursor?: string;
}
export interface ListWorkspaceMembersRequest {
  limit?: number;
  cursor?: string;
}
export interface MarkNotificationReadRequest {
  notificationId: string;
}
export interface PreviewConnectorBootstrapRequest {
  body: unknown;
}
export interface PutConnectorRuntimeConfigRequest {
  body: unknown;
}
export interface PutConnectorSyncScheduleRequest {
  body: unknown;
}
export interface PutNotificationPreferenceRequest {
  channel: string;
  body: unknown;
}
export interface PutWarehouseFailoverRouteRequest {
  warehouseId: string;
  destinationWarehouseId: string;
  body: unknown;
}
export interface ReplaceConnectorAccountCapabilitiesRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ReplayWebhookDeliveryRequest {
  deliveryId: string;
}
export interface ReserveFulfillmentAllocationRequest {
  body: unknown;
}
export interface ResolveSyncDriftRequest {
  driftId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RetireApprovalPolicyRequest {
  policyId: string;
  expectedVersion: number;
  idempotencyKey: string;
}
export interface RevokeSettingsSecuritySessionRequest {
  sessionRef: string;
  idempotencyKey: string;
}
export interface RollbackSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RotateWebhookSigningSecretRequest {
  subscriptionId: string;
  body: unknown;
}
export interface RunSyncPolicyRequest {
  policyId: string;
  idempotencyKey: string;
}
export interface SaveSettingsIdentityProviderDraftRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface SearchLegalPartiesRequest {
  q?: string;
  inn?: string;
  registrationId?: string;
  partyType?: string;
  limit?: number;
}
export interface StartConnectorBootstrapRequest {
  body: unknown;
}
export interface StartConnectorOAuthRequest {
  body: unknown;
}
export interface SyncConnectorAccountRequest {
  body: unknown;
}
export interface UpdateInventoryWarehouseRequest {
  warehouseId: string;
  body: unknown;
}
export interface UpdateOfferPriceRequest {
  productId: string;
  offerOrPriceId: string;
  body: unknown;
}
export interface UpdateProductRequest {
  productId: string;
  body: unknown;
}
export interface UpdateProductImageRequest {
  productId: string;
  imageId: string;
  body: unknown;
}
export interface UpdateProductOfferRequest {
  productId: string;
  offerId: string;
  body: unknown;
}
export interface UpdateSyncPolicyRequest {
  policyId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateWarehouseOperationalStateRequest {
  warehouseId: string;
  body: unknown;
}
export interface UpdateWorkspaceMemberRequest {
  memberId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateWorkspaceSettingsRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ValidateSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export class TorgnexaClient {
  constructor(config: ClientConfig);
  activateSettingsIdentityProvider(input: ActivateSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  adjustInventoryPosition(input: AdjustInventoryPositionRequest, options?: RequestOptions): Promise<APIResponse>;
  analyzeWithAIProvider(input: AnalyzeWithAIProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  assignProductCategory(input: AssignProductCategoryRequest, options?: RequestOptions): Promise<APIResponse>;
  checkConnectorAccount(input: CheckConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  completeConnectorOAuth(input: CompleteConnectorOAuthRequest, options?: RequestOptions): Promise<APIResponse>;
  createAIProviderAccount(input: CreateAIProviderAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  createApprovalPolicy(input: CreateApprovalPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  createApprovalRequest(input: CreateApprovalRequestRequest, options?: RequestOptions): Promise<APIResponse>;
  createCatalogCategory(input: CreateCatalogCategoryRequest, options?: RequestOptions): Promise<APIResponse>;
  createConnectorAccount(input: CreateConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  createDemoApproval(input: CreateDemoApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  createDemoOrders(input: CreateDemoOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  createInventoryWarehouse(input: CreateInventoryWarehouseRequest, options?: RequestOptions): Promise<APIResponse>;
  createOfferPrice(input: CreateOfferPriceRequest, options?: RequestOptions): Promise<APIResponse>;
  createPrivacyRequest(input: CreatePrivacyRequestRequest, options?: RequestOptions): Promise<APIResponse>;
  createProduct(input: CreateProductRequest, options?: RequestOptions): Promise<APIResponse>;
  createProductImage(input: CreateProductImageRequest, options?: RequestOptions): Promise<APIResponse>;
  createProductOffer(input: CreateProductOfferRequest, options?: RequestOptions): Promise<APIResponse>;
  createReconciliationJob(input: CreateReconciliationJobRequest, options?: RequestOptions): Promise<APIResponse>;
  createSyncPolicy(input: CreateSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  createUpload(input: CreateUploadRequest, options?: RequestOptions): Promise<APIResponse>;
  createWebhookSubscription(input: CreateWebhookSubscriptionRequest, options?: RequestOptions): Promise<APIResponse>;
  decideApproval(input: DecideApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteDemoOrders(input: DeleteDemoOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  disableAIProviderAccount(input: DisableAIProviderAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  disableConnectorAccount(input: DisableConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  disableSettingsIdentityProvider(input: DisableSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  disableWebhookSubscription(input: DisableWebhookSubscriptionRequest, options?: RequestOptions): Promise<APIResponse>;
  enableConnectorAccount(input: EnableConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  enrollConnectorCredentials(input: EnrollConnectorCredentialsRequest, options?: RequestOptions): Promise<APIResponse>;
  evaluateEntitlement(input: EvaluateEntitlementRequest, options?: RequestOptions): Promise<APIResponse>;
  evaluateProductCompliance(input: EvaluateProductComplianceRequest, options?: RequestOptions): Promise<APIResponse>;
  executeApproval(input: ExecuteApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  getCloudSubscription(options?: RequestOptions): Promise<APIResponse>;
  getConnectorBootstrapState(options?: RequestOptions): Promise<APIResponse>;
  getConnectorRuntimeConfig(input: GetConnectorRuntimeConfigRequest, options?: RequestOptions): Promise<APIResponse>;
  getFulfillmentAllocation(input: GetFulfillmentAllocationRequest, options?: RequestOptions): Promise<APIResponse>;
  getHealth(options?: RequestOptions): Promise<APIResponse>;
  getInventoryPosition(input: GetInventoryPositionRequest, options?: RequestOptions): Promise<APIResponse>;
  getLineageTimeline(input: GetLineageTimelineRequest, options?: RequestOptions): Promise<APIResponse>;
  getNotificationPreference(input: GetNotificationPreferenceRequest, options?: RequestOptions): Promise<APIResponse>;
  getOrder(input: GetOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  getProduct(input: GetProductRequest, options?: RequestOptions): Promise<APIResponse>;
  getReportData(input: GetReportDataRequest, options?: RequestOptions): Promise<APIResponse>;
  getSettingsSecurityConfiguration(options?: RequestOptions): Promise<APIResponse>;
  getSyncStatus(options?: RequestOptions): Promise<APIResponse>;
  getWarehouseIncident(input: GetWarehouseIncidentRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseOperationalState(input: GetWarehouseOperationalStateRequest, options?: RequestOptions): Promise<APIResponse>;
  getWebhookDeliveryHistory(input: GetWebhookDeliveryHistoryRequest, options?: RequestOptions): Promise<APIResponse>;
  getWorkspaceSettings(options?: RequestOptions): Promise<APIResponse>;
  importInventory(input: ImportInventoryRequest, options?: RequestOptions): Promise<APIResponse>;
  inviteWorkspaceMember(input: InviteWorkspaceMemberRequest, options?: RequestOptions): Promise<APIResponse>;
  listAIProviderAccounts(options?: RequestOptions): Promise<APIResponse>;
  listApprovalPolicies(options?: RequestOptions): Promise<APIResponse>;
  listApprovals(options?: RequestOptions): Promise<APIResponse>;
  listAuditRecords(input: ListAuditRecordsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCatalogCategories(options?: RequestOptions): Promise<APIResponse>;
  listComplianceDocuments(options?: RequestOptions): Promise<APIResponse>;
  listConnectorAccountHealthHistory(input: ListConnectorAccountHealthHistoryRequest, options?: RequestOptions): Promise<APIResponse>;
  listConnectorAccounts(input: ListConnectorAccountsRequest, options?: RequestOptions): Promise<APIResponse>;
  listConnectors(options?: RequestOptions): Promise<APIResponse>;
  listCounterparties(options?: RequestOptions): Promise<APIResponse>;
  listFXRates(options?: RequestOptions): Promise<APIResponse>;
  listFulfillmentAllocations(options?: RequestOptions): Promise<APIResponse>;
  listInventoryPositions(options?: RequestOptions): Promise<APIResponse>;
  listInventoryWarehouses(options?: RequestOptions): Promise<APIResponse>;
  listNotificationDeliveries(input: ListNotificationDeliveriesRequest, options?: RequestOptions): Promise<APIResponse>;
  listNotifications(input: ListNotificationsRequest, options?: RequestOptions): Promise<APIResponse>;
  listOrders(input: ListOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  listPlugins(options?: RequestOptions): Promise<APIResponse>;
  listProducts(input: ListProductsRequest, options?: RequestOptions): Promise<APIResponse>;
  listReports(options?: RequestOptions): Promise<APIResponse>;
  listSettingsIdentityProviders(options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecurityAudit(input: ListSettingsSecurityAuditRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecurityLogins(input: ListSettingsSecurityLoginsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecuritySessions(input: ListSettingsSecuritySessionsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettlementEntries(input: ListSettlementEntriesRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseIncidents(options?: RequestOptions): Promise<APIResponse>;
  listWebhookSubscriptions(options?: RequestOptions): Promise<APIResponse>;
  listWorkspaceMembers(input: ListWorkspaceMembersRequest, options?: RequestOptions): Promise<APIResponse>;
  markNotificationRead(input: MarkNotificationReadRequest, options?: RequestOptions): Promise<APIResponse>;
  previewConnectorBootstrap(input: PreviewConnectorBootstrapRequest, options?: RequestOptions): Promise<APIResponse>;
  putConnectorRuntimeConfig(input: PutConnectorRuntimeConfigRequest, options?: RequestOptions): Promise<APIResponse>;
  putConnectorSyncSchedule(input: PutConnectorSyncScheduleRequest, options?: RequestOptions): Promise<APIResponse>;
  putNotificationPreference(input: PutNotificationPreferenceRequest, options?: RequestOptions): Promise<APIResponse>;
  putWarehouseFailoverRoute(input: PutWarehouseFailoverRouteRequest, options?: RequestOptions): Promise<APIResponse>;
  replaceConnectorAccountCapabilities(input: ReplaceConnectorAccountCapabilitiesRequest, options?: RequestOptions): Promise<APIResponse>;
  replayWebhookDelivery(input: ReplayWebhookDeliveryRequest, options?: RequestOptions): Promise<APIResponse>;
  reserveFulfillmentAllocation(input: ReserveFulfillmentAllocationRequest, options?: RequestOptions): Promise<APIResponse>;
  resolveSyncDrift(input: ResolveSyncDriftRequest, options?: RequestOptions): Promise<APIResponse>;
  retireApprovalPolicy(input: RetireApprovalPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  revokeSettingsSecuritySession(input: RevokeSettingsSecuritySessionRequest, options?: RequestOptions): Promise<APIResponse>;
  rollbackSettingsIdentityProvider(input: RollbackSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  rotateWebhookSigningSecret(input: RotateWebhookSigningSecretRequest, options?: RequestOptions): Promise<APIResponse>;
  runSyncPolicy(input: RunSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  saveSettingsIdentityProviderDraft(input: SaveSettingsIdentityProviderDraftRequest, options?: RequestOptions): Promise<APIResponse>;
  searchLegalParties(input: SearchLegalPartiesRequest, options?: RequestOptions): Promise<APIResponse>;
  startConnectorBootstrap(input: StartConnectorBootstrapRequest, options?: RequestOptions): Promise<APIResponse>;
  startConnectorOAuth(input: StartConnectorOAuthRequest, options?: RequestOptions): Promise<APIResponse>;
  streamRealtimeInvalidations(options?: RequestOptions): Promise<APIResponse>;
  syncConnectorAccount(input: SyncConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  updateInventoryWarehouse(input: UpdateInventoryWarehouseRequest, options?: RequestOptions): Promise<APIResponse>;
  updateOfferPrice(input: UpdateOfferPriceRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProduct(input: UpdateProductRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProductImage(input: UpdateProductImageRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProductOffer(input: UpdateProductOfferRequest, options?: RequestOptions): Promise<APIResponse>;
  updateSyncPolicy(input: UpdateSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWarehouseOperationalState(input: UpdateWarehouseOperationalStateRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWorkspaceMember(input: UpdateWorkspaceMemberRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWorkspaceSettings(input: UpdateWorkspaceSettingsRequest, options?: RequestOptions): Promise<APIResponse>;
  validateSettingsIdentityProvider(input: ValidateSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
}
