// Code generated by torgnexa-sdkgen/v1; DO NOT EDIT.
// Source: contracts/openapi/torgnexa-v1.yaml sha256=54d2d0f004cd79085ecb8e2dd19a0545f7dfaf0cfc77f50957752c9c6dd4a294

export const API_VERSION: string;
export const OPENAPI_VERSION: string;
export const DEFAULT_SERVER_PATH: string;
export const GENERATOR_VERSION: string;
export interface APIResponse<T = unknown> { statusCode: number; headers: Headers; body: T; }
export interface RequestOptions { signal?: AbortSignal; headers?: Record<string, string>; }
export interface ClientConfig { baseURL: string; bearerToken?: string; userAgent?: string; fetch?: typeof fetch; }
export class APIError extends Error { statusCode: number; body: unknown; constructor(statusCode: number, body: unknown); }
export interface ActivateSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface AdjustInventoryPositionRequest {
  positionId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface AdvanceWarehouseMobilePlanRequest {
  planId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface AnalyzeWithAIProviderRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AppendFinancialBankAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AppendFinancialBankStatementRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AppendFinancialCOGSBackfillRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AppendFinancialSourceRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ApplyCatalogBulkRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface ApplyMarketplaceGrowthOperationRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface ApplyMarketplaceListingBatchRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface ApplyMarketplaceOperationFindingActionRequest {
  findingId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ApplyMarketplaceOperationFlowCommandRequest {
  flowId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ApproveAssistantActionPreviewRequest {
  previewId: string;
  idempotencyKey: string;
}
export interface ApproveProcurementPurchaseOrderRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
  approvalRequestID: string;
}
export interface ArchiveLogisticsBatchRequest {
  batchId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface ArchiveWorkflowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AssignCustomerServiceConversationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface AssignProductCategoryRequest {
  productId: string;
  categoryId: string;
  idempotencyKey: string;
}
export interface CalculateLogisticsRatesRequest {
  body: unknown;
}
export interface CancelAssistantRunRequest {
  runId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CancelLogisticsBatchRequest {
  batchId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface CancelLogisticsShipmentRequest {
  shipmentId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface CancelProcurementPurchaseOrderRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
}
export interface CancelWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CancelWorkflowRunRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ChangeOrderCancellationStatusRequest {
  cancellationId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ChangeOrderStatusRequest {
  orderId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ChangeReturnStatusRequest {
  returnId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CheckConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ClaimWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CloseWarehouseMobilePackRequest {
  packId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CommitProcurementPriceListRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CompleteConnectorOAuthRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CompleteWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateAIProviderAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateApprovalPolicyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateApprovalRequestRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateAssistantSessionRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateCatalogCategoryRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateCounterpartyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateCurrentUserProfilePrivacyRequestRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateDemoApprovalRequest {
  idempotencyKey: string;
}
export interface CreateDemoOrdersRequest {
  idempotencyKey?: string;
}
export interface CreateInventoryWarehouseRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateLegalPartyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateLogisticsBatchRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface CreateLogisticsSeparateReturnRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface CreateLogisticsShipmentRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface CreateMCPAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateMarketplaceGrowthPreviewRequest {
  body: unknown;
}
export interface CreateMarketplaceOperationFlowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateOfferPriceRequest {
  productId: string;
  offerOrPriceId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateOrderCancellationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreatePaymentRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreatePrivacyRequestRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProcurementOfferRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProcurementPurchaseOrderRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProcurementPurchaseOrderFromRecommendationsRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProcurementSupplierRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProductRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProductImageRequest {
  productId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProductOfferRequest {
  productId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateProfitabilityScenarioRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateReconciliationJobRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateRefundAllocationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateReplenishmentRunRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateReturnRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateReturnItemRequest {
  returnId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateReturnLogisticsRequest {
  returnId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateSellerFinancialCalculationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateSocialChannelRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateSocialPublicationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateSyncPolicyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateUploadRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseMobilePackRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseMobilePickBatchRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseMobilePickBatchForPlanRequest {
  planId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseMobilePlanRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseTaskRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseTaskBatchRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWarehouseTasksFromOrderRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface CreateWebhookSubscriptionRequest {
  body: unknown;
}
export interface CreateWorkflowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DecideApprovalRequest {
  requestId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface DeleteCurrentUserAvatarRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DeleteDemoOrdersRequest {
  idempotencyKey?: string;
}
export interface DeleteLogisticsSeparateReturnRequest {
  returnId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface DeleteProductImageRequest {
  productId: string;
  imageId: string;
  idempotencyKey: string;
}
export interface DeleteSocialPublicationRequest {
  publicationId: string;
  idempotencyKey: string;
  approvalRequestID: string;
}
export interface DisableAIProviderAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DisableConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DisableMCPAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface DisableSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface DisableWebhookSubscriptionRequest {
  subscriptionId: string;
}
export interface EditLogisticsSeparateReturnRequest {
  returnId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface EditSocialPublicationRequest {
  publicationId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface EnableConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface EnqueueMarketplacePublicationRequest {
  idempotencyKey: string;
  approvalRequestID?: string;
  body: unknown;
}
export interface EnrollConnectorCredentialsRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface EvaluateEntitlementRequest {
  body: unknown;
}
export interface EvaluateProductComplianceRequest {
  body: unknown;
}
export interface ExceptionWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ExecuteApprovalRequest {
  requestId: string;
  idempotencyKey: string;
}
export interface GetAssistantRunRequest {
  runId: string;
}
export interface GetAssistantSessionRequest {
  sessionId: string;
}
export interface GetCatalogBulkPreviewRequest {
  previewId: string;
}
export interface GetCatalogBulkRunRequest {
  runId: string;
}
export interface GetConnectorReadinessRequest {
  connectorId: string;
}
export interface GetConnectorRuntimeConfigRequest {
  accountId: string;
}
export interface GetCustomerServiceCustomerTimelineRequest {
  customerRefId: string;
}
export interface GetCustomerServiceThreadRequest {
  conversationId: string;
}
export interface GetFinancialCompletenessRequest {
  basis?: string;
  from?: string;
  to?: string;
  currency?: string;
}
export interface GetFulfillmentAllocationRequest {
  allocationId: string;
}
export interface GetIntegrationCenterRequest {
  limit?: number;
  cursor?: string;
  family?: string;
  surface?: string;
  overall?: string;
  health?: string;
  sync?: string;
  capability?: string;
  issue?: string;
  stale?: boolean;
  accountId?: string;
}
export interface GetIntegrationCenterAccountRequest {
  accountId: string;
}
export interface GetInventoryPositionRequest {
  positionId: string;
}
export interface GetLineageTimelineRequest {
  system: string;
  entityType: string;
  entityId: string;
  field?: string;
  limit?: number;
  beforeAt?: string;
  beforeId?: string;
}
export interface GetLogisticsBatchRequest {
  batchId: string;
  connectorAccountId: string;
}
export interface GetLogisticsOrderRequest {
  orderId: string;
  connectorAccountId: string;
}
export interface GetMCPAccountPolicyRequest {
  accountId: string;
}
export interface GetMarketplaceGrowthOperationRequest {
  operationId: string;
}
export interface GetMarketplaceGrowthPreviewRequest {
  previewId: string;
}
export interface GetMarketplaceListingBatchRequest {
  batchId: string;
}
export interface GetMarketplaceListingTaxonomyRequest {
  taxonomyId?: string;
  connectorId?: string;
  locale?: string;
  jurisdiction?: string;
}
export interface GetMarketplaceOperationFlowRequest {
  flowId: string;
}
export interface GetMarketplaceOperationsRequest {
  accountId: string;
}
export interface GetMarketplacePublicationRequest {
  operationId: string;
}
export interface GetMarkingOverviewRequest {
  limit?: number;
}
export interface GetNotificationPreferenceRequest {
  channel: string;
}
export interface GetOrderRequest {
  orderId: string;
}
export interface GetOrderCancellationRequest {
  cancellationId: string;
}
export interface GetPaymentRequest {
  paymentId: string;
}
export interface GetProcurementPurchaseOrderRequest {
  purchaseOrderId: string;
}
export interface GetProcurementSupplierRequest {
  supplierId: string;
}
export interface GetProductRequest {
  productId: string;
}
export interface GetPublicationQualityReceiptRequest {
  receiptId: string;
}
export interface GetPublicationQualityRunRequest {
  runId: string;
}
export interface GetReportDataRequest {
  reportId: string;
  from?: string;
  to?: string;
  q?: string;
  currency?: string;
  status?: string;
  completeness?: string;
  basis?: string;
  channelRef?: string;
  limit?: number;
  format?: string;
}
export interface GetReturnRequest {
  returnId: string;
}
export interface GetReturnLogisticsRequest {
  operationId: string;
}
export interface GetSellerCashFlowRequest {
  from?: string;
  to?: string;
  runId?: string;
  currency?: string;
  channelRef?: string;
  q?: string;
  limit?: number;
  cursor?: string;
  format?: string;
}
export interface GetSellerFinancialQualityRequest {
  from?: string;
  to?: string;
  runId?: string;
  currency?: string;
  channelRef?: string;
  q?: string;
  limit?: number;
  cursor?: string;
  format?: string;
}
export interface GetSellerProfitAndLossRequest {
  from?: string;
  to?: string;
  runId?: string;
  currency?: string;
  channelRef?: string;
  q?: string;
  limit?: number;
  cursor?: string;
  format?: string;
}
export interface GetSellerProfitAndLossDetailsRequest {
  from?: string;
  to?: string;
  runId?: string;
  currency?: string;
  channelRef?: string;
  sku?: string;
  orderId?: string;
  q?: string;
  limit?: number;
  cursor?: string;
  format?: string;
}
export interface GetSellerUnitEconomicsRequest {
  from?: string;
  to?: string;
  runId?: string;
  currency?: string;
  channelRef?: string;
  q?: string;
  limit?: number;
  cursor?: string;
  format?: string;
}
export interface GetUploadRequest {
  uploadId: string;
}
export interface GetUploadContentRequest {
  uploadId: string;
}
export interface GetWarehouseIncidentRequest {
  incidentId: string;
}
export interface GetWarehouseMobilePlanRequest {
  planId: string;
}
export interface GetWarehouseOperationalStateRequest {
  warehouseId: string;
}
export interface GetWarehouseTaskRequest {
  taskId: string;
}
export interface GetWarehouseTaskBatchRequest {
  batchId: string;
}
export interface GetWebhookDeliveryHistoryRequest {
  deliveryId: string;
  limit?: number;
}
export interface GetWorkflowRequest {
  workflowId: string;
}
export interface GetWorkflowRunRequest {
  runId: string;
}
export interface GetWorkspaceMemberProfileRequest {
  memberId: string;
}
export interface HandoffWarehouseTaskBatchRequest {
  batchId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ImportInventoryRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface IngestCustomerServiceInboundRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface InstallMCPAccountPolicyRequest {
  accountId: string;
  body: unknown;
}
export interface InviteWorkspaceMemberRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ListAdvertisingCampaignsRequest {
  channel?: string;
  campaignId?: string;
  limit?: number;
}
export interface ListAdvertisingMetricsRequest {
  from?: string;
  to?: string;
  channel?: string;
  campaignId?: string;
  sku?: string;
  limit?: number;
}
export interface ListAdvertisingPerformanceRequest {
  from?: string;
  to?: string;
  channel?: string;
  campaignId?: string;
  sku?: string;
  limit?: number;
}
export interface ListAdvertisingReconciliationFindingsRequest {
  limit?: number;
}
export interface ListAdvertisingSpendRequest {
  from?: string;
  to?: string;
  channel?: string;
  campaignId?: string;
  sku?: string;
  limit?: number;
}
export interface ListAdvertisingSyncRunsRequest {
  accountId?: string;
  limit?: number;
}
export interface ListArchivedLogisticsBatchesRequest {
  connectorAccountId: string;
  limit?: number;
}
export interface ListAssistantSessionsRequest {
  limit?: number;
}
export interface ListAuditRecordsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListCatalogBulkPreviewsRequest {
  cursor?: string;
  limit?: number;
}
export interface ListCatalogBulkRunsRequest {
  cursor?: string;
  limit?: number;
}
export interface ListConnectorAccountHealthHistoryRequest {
  accountId: string;
  limit?: number;
}
export interface ListConnectorAccountsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListConnectorReadinessRequest {
  limit?: number;
  cursor?: string;
  family?: string;
  surface?: string;
  status?: string;
  priority?: string;
}
export interface ListCounterpartiesRequest {
  limit?: number;
}
export interface ListCustomerServiceFindingsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListCustomerServiceInboxRequest {
  state?: string;
  type?: string;
  priority?: string;
  slaState?: string;
  assigneeId?: string;
  teamId?: string;
  customerRefId?: string;
  unresolved?: boolean;
  search?: string;
  limit?: number;
  cursor?: string;
}
export interface ListCustomerServiceQuestionsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListCustomerServiceReviewsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListFXRatesRequest {
  base?: string;
  quote?: string;
  limit?: number;
}
export interface ListFinancialCOGSBackfillsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListFinancialCompletenessFindingsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListFinancialSourcesRequest {
  kind?: string;
  quality?: string;
  from?: string;
  to?: string;
  basis?: string;
  limit?: number;
  cursor?: string;
}
export interface ListLogisticsBatchOrdersRequest {
  connectorAccountId: string;
  batchId: string;
  limit?: number;
  page?: number;
}
export interface ListLogisticsBatchesRequest {
  connectorAccountId: string;
  mailType?: string;
  mailCategory?: string;
  limit?: number;
  page?: number;
}
export interface ListLogisticsPickupPointsRequest {
  connectorAccountId: string;
  country: string;
  city: string;
  limit?: number;
}
export interface ListMarketplaceGrowthDriftsRequest {
  limit?: number;
}
export interface ListMarketplaceGrowthOperationsRequest {
  limit?: number;
}
export interface ListMarketplaceGrowthRulesRequest {
  channelId?: string;
  limit?: number;
}
export interface ListMarketplaceOperationFindingsRequest {
  limit?: number;
  cursor?: string;
  flowId?: string;
  status?: string;
}
export interface ListMarketplaceOperationFlowFindingsRequest {
  flowId: string;
  limit?: number;
  cursor?: string;
  status?: string;
}
export interface ListMarketplaceOperationFlowsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListMarketplaceOperationsRequest {
  limit?: number;
  cursor?: string;
  accountId?: string;
}
export interface ListMarketplacePublicationDriftsRequest {
  operationId: string;
}
export interface ListNotificationDeliveriesRequest {
  notificationId: string;
}
export interface ListNotificationsRequest {
  limit?: number;
}
export interface ListOrdersRequest {
  q?: string;
  status?: string;
  placedFrom?: string;
  placedTo?: string;
  limit?: number;
  cursor?: string;
}
export interface ListPaymentsRequest {
  limit?: number;
}
export interface ListPluginsRequest {
  limit?: number;
}
export interface ListProcurementOffersRequest {
  supplierId?: string;
}
export interface ListProcurementPurchaseOrdersRequest {
  status?: string;
  supplierId?: string;
}
export interface ListProductsRequest {
  q?: string;
  status?: string;
  limit?: number;
  cursor?: string;
}
export interface ListPublicationQualityRunsRequest {
  productId?: string;
  limit?: number;
}
export interface ListReplenishmentRunsRequest {
  limit?: number;
}
export interface ListReturnsRequest {
  limit?: number;
}
export interface ListSecurityEvidenceRequest {
  limit?: number;
  before?: string;
}
export interface ListSettingsSecurityAuditRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettingsSecurityLoginsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettingsSecuritySessionsRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSettlementEntriesRequest {
  limit?: number;
  cursor?: string;
}
export interface ListSocialChannelsRequest {
  limit?: number;
}
export interface ListSocialPublicationsRequest {
  limit?: number;
}
export interface ListWarehouseMobileDevicesRequest {
  warehouseId?: string;
  limit?: number;
}
export interface ListWarehouseMobileOfflineIntentsRequest {
  deviceId?: string;
  state?: string;
  limit?: number;
}
export interface ListWarehouseMobilePacksRequest {
  planId?: string;
  limit?: number;
}
export interface ListWarehouseMobilePickBatchesRequest {
  planId?: string;
  limit?: number;
}
export interface ListWarehouseMobilePlansRequest {
  mode?: string;
  state?: string;
  warehouseId?: string;
  limit?: number;
}
export interface ListWarehouseMobilePrintJobsRequest {
  planId?: string;
  limit?: number;
}
export interface ListWarehouseTaskHistoryRequest {
  taskId: string;
}
export interface ListWarehouseTasksRequest {
  state?: string;
  taskType?: string;
  warehouseId?: string;
  limit?: number;
  cursor?: string;
}
export interface ListWorkflowRunEvidenceRequest {
  runId: string;
  limit?: number;
}
export interface ListWorkflowRunStepsRequest {
  runId: string;
  limit?: number;
}
export interface ListWorkflowRunsRequest {
  limit?: number;
}
export interface ListWorkflowsRequest {
  limit?: number;
}
export interface ListWorkspaceMembersRequest {
  limit?: number;
  cursor?: string;
}
export interface MarkNotificationReadRequest {
  notificationId: string;
}
export interface MarkProcurementPurchaseOrderSendUnknownRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
}
export interface PauseWorkflowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PreflightMarketplacePublicationRequest {
  body: unknown;
}
export interface PreviewAIEgressRequest {
  body: unknown;
}
export interface PreviewCatalogBulkRequest {
  body: unknown;
}
export interface PreviewConnectorBootstrapRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PreviewFinancialBankStatementRequest {
  body: unknown;
}
export interface PreviewFinancialCOGSBackfillRequest {
  body: unknown;
}
export interface PreviewMarketplaceListingBatchRequest {
  body: unknown;
}
export interface PreviewProcurementPriceListRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PreviewRepricingRequest {
  body: unknown;
}
export interface PublishWorkflowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PutAIEgressPolicyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PutConnectorRuntimeConfigRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PutConnectorSyncScheduleRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface PutNotificationPreferenceRequest {
  channel: string;
  body: unknown;
}
export interface PutWarehouseFailoverRouteRequest {
  warehouseId: string;
  destinationWarehouseId: string;
  body: unknown;
}
export interface QueueCustomerServiceReplyRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface QueueWarehouseMobilePrintRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ReadAfterWriteMarketplaceListingRequest {
  body: unknown;
}
export interface ReadLogisticsLabelRequest {
  connectorAccountId: string;
  remoteId: string;
  format?: string;
}
export interface ReadLogisticsTrackingRequest {
  connectorAccountId: string;
  remoteId: string;
}
export interface ReceiveCommerceWebhookRequest {
  connectorId: string;
  organizationId: string;
  workspaceId: string;
  accountId: string;
  saleorSignature?: string;
  saleorEvent?: string;
  xWCWebhookSignature?: string;
  xWCWebhookTopic?: string;
  body: unknown;
}
export interface ReceiveProcurementPurchaseOrderRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ReceiveSocialWebhookRequest {
  connectorId: string;
  organizationId: string;
  workspaceId: string;
  accountId: string;
  xTelegramBotApiSecretToken?: string;
  xMaxBotApiSecret?: string;
  body: unknown;
}
export interface ReconcileCatalogBulkRunRequest {
  runId: string;
  body: unknown;
}
export interface ReconcileMarketplaceGrowthOperationRequest {
  body: unknown;
}
export interface RecordAssistantFeedbackRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RecordMarkingScanRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RecordReturnInspectionRequest {
  returnId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RecordWarehouseMobilePrintStatusRequest {
  printJobId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RecordWarehouseMobileRemoteObservationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RecordWarehouseMobileScanRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RefundPaymentRequest {
  paymentId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RegisterWarehouseMobileDeviceRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ReplaceConnectorAccountCapabilitiesRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ReplayWarehouseMobileOfflineScanRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ReplayWebhookDeliveryRequest {
  deliveryId: string;
}
export interface ReserveFulfillmentAllocationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ResolveSyncDriftRequest {
  driftId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RestoreLogisticsOrdersRequest {
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface RetireApprovalPolicyRequest {
  policyId: string;
  expectedVersion: number;
  idempotencyKey: string;
}
export interface RetryMarketplacePublicationRequest {
  operationId: string;
  idempotencyKey: string;
}
export interface RetryProcurementPurchaseOrderSendRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
}
export interface RetryWorkflowRunRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RevokeSettingsSecuritySessionRequest {
  sessionRef: string;
  idempotencyKey: string;
}
export interface RevokeWarehouseMobileDeviceRequest {
  deviceId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RollbackSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface RotateMCPAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RotateWebhookSigningSecretRequest {
  subscriptionId: string;
  body: unknown;
}
export interface RunConnectorReplayRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface RunSyncPolicyRequest {
  policyId: string;
  idempotencyKey: string;
}
export interface RunWorkflowRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface SaveSettingsIdentityProviderDraftRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ScanWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface SearchLegalPartiesRequest {
  q?: string;
  inn?: string;
  registrationId?: string;
  partyType?: string;
  limit?: number;
}
export interface SearchLogisticsOrdersRequest {
  connectorAccountId: string;
  externalId: string;
  limit?: number;
}
export interface SendAssistantMessageRequest {
  sessionId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface SendProcurementPurchaseOrderRequest {
  purchaseOrderId: string;
  idempotencyKey: string;
  approvalRequestID: string;
}
export interface SetCatalogBulkKillSwitchRequest {
  body: unknown;
}
export interface SetMCPAgentKillSwitchRequest {
  body: unknown;
}
export interface SetMarketplaceGrowthKillSwitchRequest {
  body: unknown;
}
export interface StartConnectorBootstrapRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface StartConnectorOAuthRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface StartWarehouseTaskRequest {
  taskId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface SubmitLogisticsBatchRequest {
  batchId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface SubscribeSocialWebhookRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface SyncConnectorAccountRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface TransitionCustomerServiceConversationRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface UnarchiveLogisticsBatchRequest {
  batchId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface UnsubscribeSocialWebhookRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateCurrentUserProfileRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateInventoryWarehouseRequest {
  warehouseId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateLogisticsBatchSendingDateRequest {
  batchId: string;
  idempotencyKey: string;
  approvalRequestID: string;
  body: unknown;
}
export interface UpdateOfferPriceRequest {
  productId: string;
  offerOrPriceId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateProcurementSupplierRequest {
  supplierId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateProductRequest {
  productId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateProductImageRequest {
  productId: string;
  imageId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateProductOfferRequest {
  productId: string;
  offerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateSocialChannelRequest {
  channelId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateSyncPolicyRequest {
  policyId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateWarehouseOperationalStateRequest {
  warehouseId: string;
  body: unknown;
}
export interface UpdateWorkspaceMemberRequest {
  memberId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateWorkspaceMemberProfileRequest {
  memberId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface UpdateWorkspaceSettingsRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface UploadCurrentUserAvatarRequest {
  idempotencyKey: string;
  body: unknown;
}
export interface ValidateSettingsIdentityProviderRequest {
  providerId: string;
  idempotencyKey: string;
  body: unknown;
}
export interface ValidateWorkflowRequest {
  body: unknown;
}
export class TorgnexaClient {
  constructor(config: ClientConfig);
  activateSettingsIdentityProvider(input: ActivateSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  adjustInventoryPosition(input: AdjustInventoryPositionRequest, options?: RequestOptions): Promise<APIResponse>;
  advanceWarehouseMobilePlan(input: AdvanceWarehouseMobilePlanRequest, options?: RequestOptions): Promise<APIResponse>;
  analyzeWithAIProvider(input: AnalyzeWithAIProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  appendFinancialBankAccount(input: AppendFinancialBankAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  appendFinancialBankStatement(input: AppendFinancialBankStatementRequest, options?: RequestOptions): Promise<APIResponse>;
  appendFinancialCOGSBackfill(input: AppendFinancialCOGSBackfillRequest, options?: RequestOptions): Promise<APIResponse>;
  appendFinancialSource(input: AppendFinancialSourceRequest, options?: RequestOptions): Promise<APIResponse>;
  applyCatalogBulk(input: ApplyCatalogBulkRequest, options?: RequestOptions): Promise<APIResponse>;
  applyMarketplaceGrowthOperation(input: ApplyMarketplaceGrowthOperationRequest, options?: RequestOptions): Promise<APIResponse>;
  applyMarketplaceListingBatch(input: ApplyMarketplaceListingBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  applyMarketplaceOperationFindingAction(input: ApplyMarketplaceOperationFindingActionRequest, options?: RequestOptions): Promise<APIResponse>;
  applyMarketplaceOperationFlowCommand(input: ApplyMarketplaceOperationFlowCommandRequest, options?: RequestOptions): Promise<APIResponse>;
  approveAssistantActionPreview(input: ApproveAssistantActionPreviewRequest, options?: RequestOptions): Promise<APIResponse>;
  approveProcurementPurchaseOrder(input: ApproveProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  archiveLogisticsBatch(input: ArchiveLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  archiveWorkflow(input: ArchiveWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  assignCustomerServiceConversation(input: AssignCustomerServiceConversationRequest, options?: RequestOptions): Promise<APIResponse>;
  assignProductCategory(input: AssignProductCategoryRequest, options?: RequestOptions): Promise<APIResponse>;
  calculateLogisticsRates(input: CalculateLogisticsRatesRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelAssistantRun(input: CancelAssistantRunRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelLogisticsBatch(input: CancelLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelLogisticsShipment(input: CancelLogisticsShipmentRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelProcurementPurchaseOrder(input: CancelProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelWarehouseTask(input: CancelWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  cancelWorkflowRun(input: CancelWorkflowRunRequest, options?: RequestOptions): Promise<APIResponse>;
  changeOrderCancellationStatus(input: ChangeOrderCancellationStatusRequest, options?: RequestOptions): Promise<APIResponse>;
  changeOrderStatus(input: ChangeOrderStatusRequest, options?: RequestOptions): Promise<APIResponse>;
  changeReturnStatus(input: ChangeReturnStatusRequest, options?: RequestOptions): Promise<APIResponse>;
  checkConnectorAccount(input: CheckConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  claimWarehouseTask(input: ClaimWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  closeWarehouseMobilePack(input: CloseWarehouseMobilePackRequest, options?: RequestOptions): Promise<APIResponse>;
  commitProcurementPriceList(input: CommitProcurementPriceListRequest, options?: RequestOptions): Promise<APIResponse>;
  completeConnectorOAuth(input: CompleteConnectorOAuthRequest, options?: RequestOptions): Promise<APIResponse>;
  completeWarehouseTask(input: CompleteWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  createAIProviderAccount(input: CreateAIProviderAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  createApprovalPolicy(input: CreateApprovalPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  createApprovalRequest(input: CreateApprovalRequestRequest, options?: RequestOptions): Promise<APIResponse>;
  createAssistantSession(input: CreateAssistantSessionRequest, options?: RequestOptions): Promise<APIResponse>;
  createCatalogCategory(input: CreateCatalogCategoryRequest, options?: RequestOptions): Promise<APIResponse>;
  createConnectorAccount(input: CreateConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  createCounterparty(input: CreateCounterpartyRequest, options?: RequestOptions): Promise<APIResponse>;
  createCurrentUserProfilePrivacyRequest(input: CreateCurrentUserProfilePrivacyRequestRequest, options?: RequestOptions): Promise<APIResponse>;
  createDemoApproval(input: CreateDemoApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  createDemoOrders(input: CreateDemoOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  createInventoryWarehouse(input: CreateInventoryWarehouseRequest, options?: RequestOptions): Promise<APIResponse>;
  createLegalParty(input: CreateLegalPartyRequest, options?: RequestOptions): Promise<APIResponse>;
  createLogisticsBatch(input: CreateLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  createLogisticsSeparateReturn(input: CreateLogisticsSeparateReturnRequest, options?: RequestOptions): Promise<APIResponse>;
  createLogisticsShipment(input: CreateLogisticsShipmentRequest, options?: RequestOptions): Promise<APIResponse>;
  createMCPAccount(input: CreateMCPAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  createMarketplaceGrowthPreview(input: CreateMarketplaceGrowthPreviewRequest, options?: RequestOptions): Promise<APIResponse>;
  createMarketplaceOperationFlow(input: CreateMarketplaceOperationFlowRequest, options?: RequestOptions): Promise<APIResponse>;
  createOfferPrice(input: CreateOfferPriceRequest, options?: RequestOptions): Promise<APIResponse>;
  createOrderCancellation(input: CreateOrderCancellationRequest, options?: RequestOptions): Promise<APIResponse>;
  createPayment(input: CreatePaymentRequest, options?: RequestOptions): Promise<APIResponse>;
  createPrivacyRequest(input: CreatePrivacyRequestRequest, options?: RequestOptions): Promise<APIResponse>;
  createProcurementOffer(input: CreateProcurementOfferRequest, options?: RequestOptions): Promise<APIResponse>;
  createProcurementPurchaseOrder(input: CreateProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  createProcurementPurchaseOrderFromRecommendations(input: CreateProcurementPurchaseOrderFromRecommendationsRequest, options?: RequestOptions): Promise<APIResponse>;
  createProcurementSupplier(input: CreateProcurementSupplierRequest, options?: RequestOptions): Promise<APIResponse>;
  createProduct(input: CreateProductRequest, options?: RequestOptions): Promise<APIResponse>;
  createProductImage(input: CreateProductImageRequest, options?: RequestOptions): Promise<APIResponse>;
  createProductOffer(input: CreateProductOfferRequest, options?: RequestOptions): Promise<APIResponse>;
  createProfitabilityScenario(input: CreateProfitabilityScenarioRequest, options?: RequestOptions): Promise<APIResponse>;
  createReconciliationJob(input: CreateReconciliationJobRequest, options?: RequestOptions): Promise<APIResponse>;
  createRefundAllocation(input: CreateRefundAllocationRequest, options?: RequestOptions): Promise<APIResponse>;
  createReplenishmentRun(input: CreateReplenishmentRunRequest, options?: RequestOptions): Promise<APIResponse>;
  createReturn(input: CreateReturnRequest, options?: RequestOptions): Promise<APIResponse>;
  createReturnItem(input: CreateReturnItemRequest, options?: RequestOptions): Promise<APIResponse>;
  createReturnLogistics(input: CreateReturnLogisticsRequest, options?: RequestOptions): Promise<APIResponse>;
  createSellerFinancialCalculation(input: CreateSellerFinancialCalculationRequest, options?: RequestOptions): Promise<APIResponse>;
  createSocialChannel(input: CreateSocialChannelRequest, options?: RequestOptions): Promise<APIResponse>;
  createSocialPublication(input: CreateSocialPublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  createSyncPolicy(input: CreateSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  createUpload(input: CreateUploadRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseMobilePack(input: CreateWarehouseMobilePackRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseMobilePickBatch(input: CreateWarehouseMobilePickBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseMobilePickBatchForPlan(input: CreateWarehouseMobilePickBatchForPlanRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseMobilePlan(input: CreateWarehouseMobilePlanRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseTask(input: CreateWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseTaskBatch(input: CreateWarehouseTaskBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  createWarehouseTasksFromOrder(input: CreateWarehouseTasksFromOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  createWebhookSubscription(input: CreateWebhookSubscriptionRequest, options?: RequestOptions): Promise<APIResponse>;
  createWorkflow(input: CreateWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  decideApproval(input: DecideApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteCurrentUserAvatar(input: DeleteCurrentUserAvatarRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteDemoOrders(input: DeleteDemoOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteLogisticsSeparateReturn(input: DeleteLogisticsSeparateReturnRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteProductImage(input: DeleteProductImageRequest, options?: RequestOptions): Promise<APIResponse>;
  deleteSocialPublication(input: DeleteSocialPublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  disableAIProviderAccount(input: DisableAIProviderAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  disableConnectorAccount(input: DisableConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  disableMCPAccount(input: DisableMCPAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  disableSettingsIdentityProvider(input: DisableSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  disableWebhookSubscription(input: DisableWebhookSubscriptionRequest, options?: RequestOptions): Promise<APIResponse>;
  editLogisticsSeparateReturn(input: EditLogisticsSeparateReturnRequest, options?: RequestOptions): Promise<APIResponse>;
  editSocialPublication(input: EditSocialPublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  enableConnectorAccount(input: EnableConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  enqueueMarketplacePublication(input: EnqueueMarketplacePublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  enrollConnectorCredentials(input: EnrollConnectorCredentialsRequest, options?: RequestOptions): Promise<APIResponse>;
  evaluateEntitlement(input: EvaluateEntitlementRequest, options?: RequestOptions): Promise<APIResponse>;
  evaluateProductCompliance(input: EvaluateProductComplianceRequest, options?: RequestOptions): Promise<APIResponse>;
  exceptionWarehouseTask(input: ExceptionWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  executeApproval(input: ExecuteApprovalRequest, options?: RequestOptions): Promise<APIResponse>;
  getAIEgressPolicy(options?: RequestOptions): Promise<APIResponse>;
  getAssistantRun(input: GetAssistantRunRequest, options?: RequestOptions): Promise<APIResponse>;
  getAssistantSession(input: GetAssistantSessionRequest, options?: RequestOptions): Promise<APIResponse>;
  getCatalogBulkKillSwitch(options?: RequestOptions): Promise<APIResponse>;
  getCatalogBulkPreview(input: GetCatalogBulkPreviewRequest, options?: RequestOptions): Promise<APIResponse>;
  getCatalogBulkRun(input: GetCatalogBulkRunRequest, options?: RequestOptions): Promise<APIResponse>;
  getCloudSubscription(options?: RequestOptions): Promise<APIResponse>;
  getConnectorBootstrapState(options?: RequestOptions): Promise<APIResponse>;
  getConnectorReadiness(input: GetConnectorReadinessRequest, options?: RequestOptions): Promise<APIResponse>;
  getConnectorRuntimeConfig(input: GetConnectorRuntimeConfigRequest, options?: RequestOptions): Promise<APIResponse>;
  getCurrentUserProfile(options?: RequestOptions): Promise<APIResponse>;
  getCustomerServiceCustomerTimeline(input: GetCustomerServiceCustomerTimelineRequest, options?: RequestOptions): Promise<APIResponse>;
  getCustomerServiceSummary(options?: RequestOptions): Promise<APIResponse>;
  getCustomerServiceThread(input: GetCustomerServiceThreadRequest, options?: RequestOptions): Promise<APIResponse>;
  getFinancialCompleteness(input: GetFinancialCompletenessRequest, options?: RequestOptions): Promise<APIResponse>;
  getFulfillmentAllocation(input: GetFulfillmentAllocationRequest, options?: RequestOptions): Promise<APIResponse>;
  getHealth(options?: RequestOptions): Promise<APIResponse>;
  getIntegrationCenter(input: GetIntegrationCenterRequest, options?: RequestOptions): Promise<APIResponse>;
  getIntegrationCenterAccount(input: GetIntegrationCenterAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  getInventoryPosition(input: GetInventoryPositionRequest, options?: RequestOptions): Promise<APIResponse>;
  getLineageTimeline(input: GetLineageTimelineRequest, options?: RequestOptions): Promise<APIResponse>;
  getLogisticsBatch(input: GetLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  getLogisticsOrder(input: GetLogisticsOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  getMCPAccountPolicy(input: GetMCPAccountPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  getMCPAgentKillSwitch(options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceGrowthKillSwitch(options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceGrowthOperation(input: GetMarketplaceGrowthOperationRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceGrowthPreview(input: GetMarketplaceGrowthPreviewRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceListingBatch(input: GetMarketplaceListingBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceListingTaxonomy(input: GetMarketplaceListingTaxonomyRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceOperationFlow(input: GetMarketplaceOperationFlowRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplaceOperations(input: GetMarketplaceOperationsRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarketplacePublication(input: GetMarketplacePublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  getMarkingOverview(input: GetMarkingOverviewRequest, options?: RequestOptions): Promise<APIResponse>;
  getNotificationPreference(input: GetNotificationPreferenceRequest, options?: RequestOptions): Promise<APIResponse>;
  getOrder(input: GetOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  getOrderCancellation(input: GetOrderCancellationRequest, options?: RequestOptions): Promise<APIResponse>;
  getPayment(input: GetPaymentRequest, options?: RequestOptions): Promise<APIResponse>;
  getProcurementPurchaseOrder(input: GetProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  getProcurementSupplier(input: GetProcurementSupplierRequest, options?: RequestOptions): Promise<APIResponse>;
  getProduct(input: GetProductRequest, options?: RequestOptions): Promise<APIResponse>;
  getPublicationQualityReceipt(input: GetPublicationQualityReceiptRequest, options?: RequestOptions): Promise<APIResponse>;
  getPublicationQualityRun(input: GetPublicationQualityRunRequest, options?: RequestOptions): Promise<APIResponse>;
  getReportData(input: GetReportDataRequest, options?: RequestOptions): Promise<APIResponse>;
  getReturn(input: GetReturnRequest, options?: RequestOptions): Promise<APIResponse>;
  getReturnLogistics(input: GetReturnLogisticsRequest, options?: RequestOptions): Promise<APIResponse>;
  getRuntimeSecurityPosture(options?: RequestOptions): Promise<APIResponse>;
  getSellerCashFlow(input: GetSellerCashFlowRequest, options?: RequestOptions): Promise<APIResponse>;
  getSellerFinancialQuality(input: GetSellerFinancialQualityRequest, options?: RequestOptions): Promise<APIResponse>;
  getSellerProfitAndLoss(input: GetSellerProfitAndLossRequest, options?: RequestOptions): Promise<APIResponse>;
  getSellerProfitAndLossDetails(input: GetSellerProfitAndLossDetailsRequest, options?: RequestOptions): Promise<APIResponse>;
  getSellerUnitEconomics(input: GetSellerUnitEconomicsRequest, options?: RequestOptions): Promise<APIResponse>;
  getSettingsSecurityConfiguration(options?: RequestOptions): Promise<APIResponse>;
  getSyncStatus(options?: RequestOptions): Promise<APIResponse>;
  getUpload(input: GetUploadRequest, options?: RequestOptions): Promise<APIResponse>;
  getUploadContent(input: GetUploadContentRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseIncident(input: GetWarehouseIncidentRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseMobilePlan(input: GetWarehouseMobilePlanRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseMobileSummary(options?: RequestOptions): Promise<APIResponse>;
  getWarehouseOperationalState(input: GetWarehouseOperationalStateRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseTask(input: GetWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  getWarehouseTaskBatch(input: GetWarehouseTaskBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  getWebhookDeliveryHistory(input: GetWebhookDeliveryHistoryRequest, options?: RequestOptions): Promise<APIResponse>;
  getWorkflow(input: GetWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  getWorkflowRun(input: GetWorkflowRunRequest, options?: RequestOptions): Promise<APIResponse>;
  getWorkspaceMemberProfile(input: GetWorkspaceMemberProfileRequest, options?: RequestOptions): Promise<APIResponse>;
  getWorkspaceSettings(options?: RequestOptions): Promise<APIResponse>;
  handoffWarehouseTaskBatch(input: HandoffWarehouseTaskBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  importInventory(input: ImportInventoryRequest, options?: RequestOptions): Promise<APIResponse>;
  ingestCustomerServiceInbound(input: IngestCustomerServiceInboundRequest, options?: RequestOptions): Promise<APIResponse>;
  installMCPAccountPolicy(input: InstallMCPAccountPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  inviteWorkspaceMember(input: InviteWorkspaceMemberRequest, options?: RequestOptions): Promise<APIResponse>;
  listAIProviderAccounts(options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingCampaigns(input: ListAdvertisingCampaignsRequest, options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingMetrics(input: ListAdvertisingMetricsRequest, options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingPerformance(input: ListAdvertisingPerformanceRequest, options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingReconciliationFindings(input: ListAdvertisingReconciliationFindingsRequest, options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingSpend(input: ListAdvertisingSpendRequest, options?: RequestOptions): Promise<APIResponse>;
  listAdvertisingSyncRuns(input: ListAdvertisingSyncRunsRequest, options?: RequestOptions): Promise<APIResponse>;
  listApprovalPolicies(options?: RequestOptions): Promise<APIResponse>;
  listApprovals(options?: RequestOptions): Promise<APIResponse>;
  listArchivedLogisticsBatches(input: ListArchivedLogisticsBatchesRequest, options?: RequestOptions): Promise<APIResponse>;
  listAssistantSessions(input: ListAssistantSessionsRequest, options?: RequestOptions): Promise<APIResponse>;
  listAuditRecords(input: ListAuditRecordsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCatalogBulkChannels(options?: RequestOptions): Promise<APIResponse>;
  listCatalogBulkPreviews(input: ListCatalogBulkPreviewsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCatalogBulkRuns(input: ListCatalogBulkRunsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCatalogCategories(options?: RequestOptions): Promise<APIResponse>;
  listComplianceDocuments(options?: RequestOptions): Promise<APIResponse>;
  listConnectorAccountHealthHistory(input: ListConnectorAccountHealthHistoryRequest, options?: RequestOptions): Promise<APIResponse>;
  listConnectorAccounts(input: ListConnectorAccountsRequest, options?: RequestOptions): Promise<APIResponse>;
  listConnectorReadiness(input: ListConnectorReadinessRequest, options?: RequestOptions): Promise<APIResponse>;
  listConnectors(options?: RequestOptions): Promise<APIResponse>;
  listCounterparties(input: ListCounterpartiesRequest, options?: RequestOptions): Promise<APIResponse>;
  listCustomerServiceFindings(input: ListCustomerServiceFindingsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCustomerServiceInbox(input: ListCustomerServiceInboxRequest, options?: RequestOptions): Promise<APIResponse>;
  listCustomerServiceQuestions(input: ListCustomerServiceQuestionsRequest, options?: RequestOptions): Promise<APIResponse>;
  listCustomerServiceReviews(input: ListCustomerServiceReviewsRequest, options?: RequestOptions): Promise<APIResponse>;
  listFXRates(input: ListFXRatesRequest, options?: RequestOptions): Promise<APIResponse>;
  listFinancialBankAccounts(options?: RequestOptions): Promise<APIResponse>;
  listFinancialCOGSBackfills(input: ListFinancialCOGSBackfillsRequest, options?: RequestOptions): Promise<APIResponse>;
  listFinancialCompletenessFindings(input: ListFinancialCompletenessFindingsRequest, options?: RequestOptions): Promise<APIResponse>;
  listFinancialSources(input: ListFinancialSourcesRequest, options?: RequestOptions): Promise<APIResponse>;
  listFulfillmentAllocations(options?: RequestOptions): Promise<APIResponse>;
  listInventoryPositions(options?: RequestOptions): Promise<APIResponse>;
  listInventoryWarehouses(options?: RequestOptions): Promise<APIResponse>;
  listLogisticsBatchOrders(input: ListLogisticsBatchOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  listLogisticsBatches(input: ListLogisticsBatchesRequest, options?: RequestOptions): Promise<APIResponse>;
  listLogisticsPickupPoints(input: ListLogisticsPickupPointsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMCPAccounts(options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceGrowthDrifts(input: ListMarketplaceGrowthDriftsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceGrowthOperations(input: ListMarketplaceGrowthOperationsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceGrowthRules(input: ListMarketplaceGrowthRulesRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceOperationFindings(input: ListMarketplaceOperationFindingsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceOperationFlowFindings(input: ListMarketplaceOperationFlowFindingsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceOperationFlows(input: ListMarketplaceOperationFlowsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplaceOperations(input: ListMarketplaceOperationsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplacePublicationDrifts(input: ListMarketplacePublicationDriftsRequest, options?: RequestOptions): Promise<APIResponse>;
  listMarketplacePublications(options?: RequestOptions): Promise<APIResponse>;
  listNotificationDeliveries(input: ListNotificationDeliveriesRequest, options?: RequestOptions): Promise<APIResponse>;
  listNotifications(input: ListNotificationsRequest, options?: RequestOptions): Promise<APIResponse>;
  listOrders(input: ListOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  listPayments(input: ListPaymentsRequest, options?: RequestOptions): Promise<APIResponse>;
  listPlugins(input: ListPluginsRequest, options?: RequestOptions): Promise<APIResponse>;
  listProcurementOffers(input: ListProcurementOffersRequest, options?: RequestOptions): Promise<APIResponse>;
  listProcurementPurchaseOrders(input: ListProcurementPurchaseOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  listProcurementReconciliationFindings(options?: RequestOptions): Promise<APIResponse>;
  listProcurementSuppliers(options?: RequestOptions): Promise<APIResponse>;
  listProducts(input: ListProductsRequest, options?: RequestOptions): Promise<APIResponse>;
  listPublicationQualityRuns(input: ListPublicationQualityRunsRequest, options?: RequestOptions): Promise<APIResponse>;
  listReplenishmentRuns(input: ListReplenishmentRunsRequest, options?: RequestOptions): Promise<APIResponse>;
  listReports(options?: RequestOptions): Promise<APIResponse>;
  listReturns(input: ListReturnsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSecurityEvidence(input: ListSecurityEvidenceRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettingsIdentityProviders(options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecurityAudit(input: ListSettingsSecurityAuditRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecurityLogins(input: ListSettingsSecurityLoginsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettingsSecuritySessions(input: ListSettingsSecuritySessionsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSettlementEntries(input: ListSettlementEntriesRequest, options?: RequestOptions): Promise<APIResponse>;
  listSocialChannels(input: ListSocialChannelsRequest, options?: RequestOptions): Promise<APIResponse>;
  listSocialPublications(input: ListSocialPublicationsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseIncidents(options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobileDevices(input: ListWarehouseMobileDevicesRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobileOfflineIntents(input: ListWarehouseMobileOfflineIntentsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobilePacks(input: ListWarehouseMobilePacksRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobilePickBatches(input: ListWarehouseMobilePickBatchesRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobilePlans(input: ListWarehouseMobilePlansRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseMobilePrintJobs(input: ListWarehouseMobilePrintJobsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseTaskHistory(input: ListWarehouseTaskHistoryRequest, options?: RequestOptions): Promise<APIResponse>;
  listWarehouseTasks(input: ListWarehouseTasksRequest, options?: RequestOptions): Promise<APIResponse>;
  listWebhookSubscriptions(options?: RequestOptions): Promise<APIResponse>;
  listWorkflowRunEvidence(input: ListWorkflowRunEvidenceRequest, options?: RequestOptions): Promise<APIResponse>;
  listWorkflowRunSteps(input: ListWorkflowRunStepsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWorkflowRuns(input: ListWorkflowRunsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWorkflows(input: ListWorkflowsRequest, options?: RequestOptions): Promise<APIResponse>;
  listWorkspaceMembers(input: ListWorkspaceMembersRequest, options?: RequestOptions): Promise<APIResponse>;
  markNotificationRead(input: MarkNotificationReadRequest, options?: RequestOptions): Promise<APIResponse>;
  markProcurementPurchaseOrderSendUnknown(input: MarkProcurementPurchaseOrderSendUnknownRequest, options?: RequestOptions): Promise<APIResponse>;
  pauseWorkflow(input: PauseWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  preflightMarketplacePublication(input: PreflightMarketplacePublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  previewAIEgress(input: PreviewAIEgressRequest, options?: RequestOptions): Promise<APIResponse>;
  previewCatalogBulk(input: PreviewCatalogBulkRequest, options?: RequestOptions): Promise<APIResponse>;
  previewConnectorBootstrap(input: PreviewConnectorBootstrapRequest, options?: RequestOptions): Promise<APIResponse>;
  previewFinancialBankStatement(input: PreviewFinancialBankStatementRequest, options?: RequestOptions): Promise<APIResponse>;
  previewFinancialCOGSBackfill(input: PreviewFinancialCOGSBackfillRequest, options?: RequestOptions): Promise<APIResponse>;
  previewMarketplaceListingBatch(input: PreviewMarketplaceListingBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  previewProcurementPriceList(input: PreviewProcurementPriceListRequest, options?: RequestOptions): Promise<APIResponse>;
  previewRepricing(input: PreviewRepricingRequest, options?: RequestOptions): Promise<APIResponse>;
  publishWorkflow(input: PublishWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  putAIEgressPolicy(input: PutAIEgressPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  putConnectorRuntimeConfig(input: PutConnectorRuntimeConfigRequest, options?: RequestOptions): Promise<APIResponse>;
  putConnectorSyncSchedule(input: PutConnectorSyncScheduleRequest, options?: RequestOptions): Promise<APIResponse>;
  putNotificationPreference(input: PutNotificationPreferenceRequest, options?: RequestOptions): Promise<APIResponse>;
  putWarehouseFailoverRoute(input: PutWarehouseFailoverRouteRequest, options?: RequestOptions): Promise<APIResponse>;
  queueCustomerServiceReply(input: QueueCustomerServiceReplyRequest, options?: RequestOptions): Promise<APIResponse>;
  queueWarehouseMobilePrint(input: QueueWarehouseMobilePrintRequest, options?: RequestOptions): Promise<APIResponse>;
  readAfterWriteMarketplaceListing(input: ReadAfterWriteMarketplaceListingRequest, options?: RequestOptions): Promise<APIResponse>;
  readLogisticsLabel(input: ReadLogisticsLabelRequest, options?: RequestOptions): Promise<APIResponse>;
  readLogisticsTracking(input: ReadLogisticsTrackingRequest, options?: RequestOptions): Promise<APIResponse>;
  receiveCommerceWebhook(input: ReceiveCommerceWebhookRequest, options?: RequestOptions): Promise<APIResponse>;
  receiveProcurementPurchaseOrder(input: ReceiveProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  receiveSocialWebhook(input: ReceiveSocialWebhookRequest, options?: RequestOptions): Promise<APIResponse>;
  reconcileCatalogBulkRun(input: ReconcileCatalogBulkRunRequest, options?: RequestOptions): Promise<APIResponse>;
  reconcileMarketplaceGrowthOperation(input: ReconcileMarketplaceGrowthOperationRequest, options?: RequestOptions): Promise<APIResponse>;
  recordAssistantFeedback(input: RecordAssistantFeedbackRequest, options?: RequestOptions): Promise<APIResponse>;
  recordMarkingScan(input: RecordMarkingScanRequest, options?: RequestOptions): Promise<APIResponse>;
  recordReturnInspection(input: RecordReturnInspectionRequest, options?: RequestOptions): Promise<APIResponse>;
  recordWarehouseMobilePrintStatus(input: RecordWarehouseMobilePrintStatusRequest, options?: RequestOptions): Promise<APIResponse>;
  recordWarehouseMobileRemoteObservation(input: RecordWarehouseMobileRemoteObservationRequest, options?: RequestOptions): Promise<APIResponse>;
  recordWarehouseMobileScan(input: RecordWarehouseMobileScanRequest, options?: RequestOptions): Promise<APIResponse>;
  refundPayment(input: RefundPaymentRequest, options?: RequestOptions): Promise<APIResponse>;
  registerWarehouseMobileDevice(input: RegisterWarehouseMobileDeviceRequest, options?: RequestOptions): Promise<APIResponse>;
  replaceConnectorAccountCapabilities(input: ReplaceConnectorAccountCapabilitiesRequest, options?: RequestOptions): Promise<APIResponse>;
  replayWarehouseMobileOfflineScan(input: ReplayWarehouseMobileOfflineScanRequest, options?: RequestOptions): Promise<APIResponse>;
  replayWebhookDelivery(input: ReplayWebhookDeliveryRequest, options?: RequestOptions): Promise<APIResponse>;
  reserveFulfillmentAllocation(input: ReserveFulfillmentAllocationRequest, options?: RequestOptions): Promise<APIResponse>;
  resolveSyncDrift(input: ResolveSyncDriftRequest, options?: RequestOptions): Promise<APIResponse>;
  restoreLogisticsOrders(input: RestoreLogisticsOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  retireApprovalPolicy(input: RetireApprovalPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  retryMarketplacePublication(input: RetryMarketplacePublicationRequest, options?: RequestOptions): Promise<APIResponse>;
  retryProcurementPurchaseOrderSend(input: RetryProcurementPurchaseOrderSendRequest, options?: RequestOptions): Promise<APIResponse>;
  retryWorkflowRun(input: RetryWorkflowRunRequest, options?: RequestOptions): Promise<APIResponse>;
  revokeSettingsSecuritySession(input: RevokeSettingsSecuritySessionRequest, options?: RequestOptions): Promise<APIResponse>;
  revokeWarehouseMobileDevice(input: RevokeWarehouseMobileDeviceRequest, options?: RequestOptions): Promise<APIResponse>;
  rollbackSettingsIdentityProvider(input: RollbackSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  rotateMCPAccount(input: RotateMCPAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  rotateWebhookSigningSecret(input: RotateWebhookSigningSecretRequest, options?: RequestOptions): Promise<APIResponse>;
  runConnectorReplay(input: RunConnectorReplayRequest, options?: RequestOptions): Promise<APIResponse>;
  runSyncPolicy(input: RunSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  runWorkflow(input: RunWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
  saveSettingsIdentityProviderDraft(input: SaveSettingsIdentityProviderDraftRequest, options?: RequestOptions): Promise<APIResponse>;
  scanWarehouseTask(input: ScanWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  searchLegalParties(input: SearchLegalPartiesRequest, options?: RequestOptions): Promise<APIResponse>;
  searchLogisticsOrders(input: SearchLogisticsOrdersRequest, options?: RequestOptions): Promise<APIResponse>;
  sendAssistantMessage(input: SendAssistantMessageRequest, options?: RequestOptions): Promise<APIResponse>;
  sendProcurementPurchaseOrder(input: SendProcurementPurchaseOrderRequest, options?: RequestOptions): Promise<APIResponse>;
  setCatalogBulkKillSwitch(input: SetCatalogBulkKillSwitchRequest, options?: RequestOptions): Promise<APIResponse>;
  setMCPAgentKillSwitch(input: SetMCPAgentKillSwitchRequest, options?: RequestOptions): Promise<APIResponse>;
  setMarketplaceGrowthKillSwitch(input: SetMarketplaceGrowthKillSwitchRequest, options?: RequestOptions): Promise<APIResponse>;
  startConnectorBootstrap(input: StartConnectorBootstrapRequest, options?: RequestOptions): Promise<APIResponse>;
  startConnectorOAuth(input: StartConnectorOAuthRequest, options?: RequestOptions): Promise<APIResponse>;
  startWarehouseTask(input: StartWarehouseTaskRequest, options?: RequestOptions): Promise<APIResponse>;
  streamRealtimeInvalidations(options?: RequestOptions): Promise<APIResponse>;
  submitLogisticsBatch(input: SubmitLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  subscribeSocialWebhook(input: SubscribeSocialWebhookRequest, options?: RequestOptions): Promise<APIResponse>;
  syncConnectorAccount(input: SyncConnectorAccountRequest, options?: RequestOptions): Promise<APIResponse>;
  transitionCustomerServiceConversation(input: TransitionCustomerServiceConversationRequest, options?: RequestOptions): Promise<APIResponse>;
  unarchiveLogisticsBatch(input: UnarchiveLogisticsBatchRequest, options?: RequestOptions): Promise<APIResponse>;
  unsubscribeSocialWebhook(input: UnsubscribeSocialWebhookRequest, options?: RequestOptions): Promise<APIResponse>;
  updateCurrentUserProfile(input: UpdateCurrentUserProfileRequest, options?: RequestOptions): Promise<APIResponse>;
  updateInventoryWarehouse(input: UpdateInventoryWarehouseRequest, options?: RequestOptions): Promise<APIResponse>;
  updateLogisticsBatchSendingDate(input: UpdateLogisticsBatchSendingDateRequest, options?: RequestOptions): Promise<APIResponse>;
  updateOfferPrice(input: UpdateOfferPriceRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProcurementSupplier(input: UpdateProcurementSupplierRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProduct(input: UpdateProductRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProductImage(input: UpdateProductImageRequest, options?: RequestOptions): Promise<APIResponse>;
  updateProductOffer(input: UpdateProductOfferRequest, options?: RequestOptions): Promise<APIResponse>;
  updateSocialChannel(input: UpdateSocialChannelRequest, options?: RequestOptions): Promise<APIResponse>;
  updateSyncPolicy(input: UpdateSyncPolicyRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWarehouseOperationalState(input: UpdateWarehouseOperationalStateRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWorkspaceMember(input: UpdateWorkspaceMemberRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWorkspaceMemberProfile(input: UpdateWorkspaceMemberProfileRequest, options?: RequestOptions): Promise<APIResponse>;
  updateWorkspaceSettings(input: UpdateWorkspaceSettingsRequest, options?: RequestOptions): Promise<APIResponse>;
  uploadCurrentUserAvatar(input: UploadCurrentUserAvatarRequest, options?: RequestOptions): Promise<APIResponse>;
  validateSettingsIdentityProvider(input: ValidateSettingsIdentityProviderRequest, options?: RequestOptions): Promise<APIResponse>;
  validateWorkflow(input: ValidateWorkflowRequest, options?: RequestOptions): Promise<APIResponse>;
}
