import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {Page} from "./Page";

interface Campaign {id:string;account_id:string;channel:string;remote_id:string;name:string;status:string;currency:string;daily_budget_minor:number;total_budget_minor:number;observed_at:string}
interface Metric {channel:string;campaign_id:string;sku?:string;currency:string;spend_minor:number;impressions:number;clicks:number;orders:number;revenue_minor:number;roas_basis_points:number;romi_basis_points:number;drr_basis_points:number;order_cost_minor:number;quality:string}
interface Finding {id:string;kind:string;campaign_id?:string;expected_minor:number;actual_minor:number;severity:string;explanation:string;observed_at:string}
const statuses:Record<string,string>={draft:"Черновик",active:"Активна",paused:"Пауза",stopped:"Остановлена",archived:"Архив",unknown:"Неизвестно"};
function items<T>(value:unknown):T[]{const root=value as {items?:unknown};if(!Array.isArray(root?.items))throw new Error("invalid advertising response");return root.items as T[]}
function money(minor:number,currency:string){return new Intl.NumberFormat("ru-RU",{style:"currency",currency:currency||"RUB",maximumFractionDigits:2}).format(minor/100)}
function percent(basisPoints:number){return `${(basisPoints/100).toLocaleString("ru-RU",{maximumFractionDigits:2})}%`}
function dateValue(days:number){const end=new Date();const start=new Date(end);start.setUTCDate(end.getUTCDate()-days);return {from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)}}

export function AdvertisingPage(){
 const api=useApi();const [channel,setChannel]=useState("");const [campaignID,setCampaignID]=useState("");const [from,setFrom]=useState(()=>dateValue(30).from);const [to,setTo]=useState(()=>dateValue(30).to);const [tab,setTab]=useState<"metrics"|"campaigns"|"findings">("metrics");
 const range={from:new Date(`${from}T00:00:00Z`).toISOString(),to:new Date(`${to}T23:59:59Z`).toISOString(),channel:channel||undefined,campaignId:campaignID||undefined,limit:200};
 const campaigns=useQuery({queryKey:["advertising","campaigns",channel],queryFn:async()=>items<Campaign>((await api.listAdvertisingCampaigns({channel:channel||undefined,limit:200})).body),staleTime:30_000});
 const metrics=useQuery({queryKey:["advertising","metrics",from,to,channel,campaignID],queryFn:async()=>items<Metric>((await api.listAdvertisingMetrics(range)).body),staleTime:30_000});
 const findings=useQuery({queryKey:["advertising","findings"],queryFn:async()=>items<Finding>((await api.listAdvertisingReconciliationFindings({limit:100})).body),staleTime:30_000});
 const preset=(days:number)=>{const value=dateValue(days);setFrom(value.from);setTo(value.to)};
 return <Page eyebrow="Продвижение" title="Реклама" description="Расходы и эффективность кампаний WB и Ozon. Показатели считаются по нормализованным фактам, а качество данных видно рядом с результатом.">
  <section className="panel report-result">
   <div className="analytics-presets"><button className="button ghost" onClick={()=>preset(7)}>7 дней</button><button className="button ghost" onClick={()=>preset(30)}>30 дней</button><button className="button ghost" onClick={()=>preset(90)}>90 дней</button></div>
   <div className="report-filters"><label>Канал<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Все каналы</option><option value="wildberries">Wildberries</option><option value="ozon">Ozon</option></select></label><label>Кампания<select value={campaignID} onChange={e=>setCampaignID(e.target.value)}><option value="">Все кампании</option>{(campaigns.data??[]).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>С даты<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
   <div className="catalog-tabs" role="tablist"><button role="tab" aria-selected={tab==="metrics"} className={tab==="metrics"?"active":""} onClick={()=>setTab("metrics")}>Эффективность</button><button role="tab" aria-selected={tab==="campaigns"} className={tab==="campaigns"?"active":""} onClick={()=>setTab("campaigns")}>Кампании</button><button role="tab" aria-selected={tab==="findings"} className={tab==="findings"?"active":""} onClick={()=>setTab("findings")}>Сверка</button></div>
   {tab==="metrics"?<Metrics query={metrics}/>:tab==="campaigns"?<Campaigns query={campaigns}/>:<Findings query={findings}/>} 
  </section>
  <p className="settings-note">Управление ставками, бюджетами и статусами кампаний пока не включено: запись появится после отдельной квалификации и approval-контура.</p>
 </Page>
}

function Metrics({query}:{query:{data?:Metric[];isPending:boolean;isError:boolean;refetch:()=>unknown}}){if(query.isPending)return <LoadingBlock/>;if(query.isError)return <ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить рекламные показатели.</ErrorBlock>;if(!query.data?.length)return <EmptyState title="Рекламных фактов пока нет" text="Подключите кабинет с ads.read и дождитесь первой синхронизации."/>;return <div className="table-wrap"><table><thead><tr><th>Канал / кампания</th><th>SKU</th><th>Расход</th><th>Выручка</th><th>Заказы</th><th>ROAS</th><th>ДРР</th><th>Качество</th></tr></thead><tbody>{query.data.map(item=><tr key={`${item.channel}-${item.campaign_id}-${item.sku}`}><td><strong>{item.channel}</strong><small className="table-subline mono">{item.campaign_id}</small></td><td className="mono">{item.sku||"—"}</td><td><strong>{money(item.spend_minor,item.currency)}</strong></td><td>{money(item.revenue_minor,item.currency)}</td><td>{item.orders.toLocaleString("ru-RU")}</td><td>{percent(item.roas_basis_points)}</td><td>{percent(item.drr_basis_points)}</td><td><StatusBadge value={item.quality}/></td></tr>)}</tbody></table></div>}
function Campaigns({query}:{query:{data?:Campaign[];isPending:boolean;isError:boolean;refetch:()=>unknown}}){if(query.isPending)return <LoadingBlock/>;if(query.isError)return <ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить кампании.</ErrorBlock>;if(!query.data?.length)return <EmptyState title="Кампаний пока нет" text="Синхронизация появится после подключения WB или Ozon."/>;return <div className="table-wrap"><table><thead><tr><th>Кампания</th><th>Канал</th><th>Статус</th><th>Дневной бюджет</th><th>Наблюдение</th></tr></thead><tbody>{query.data.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small className="table-subline mono">{item.remote_id}</small></td><td>{item.channel}</td><td><StatusBadge value={statuses[item.status]??item.status}/></td><td>{money(item.daily_budget_minor,item.currency)}</td><td><time>{new Date(item.observed_at).toLocaleString("ru-RU")}</time></td></tr>)}</tbody></table></div>}
function Findings({query}:{query:{data?:Finding[];isPending:boolean;isError:boolean;refetch:()=>unknown}}){if(query.isPending)return <LoadingBlock/>;if(query.isError)return <ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить сверку.</ErrorBlock>;if(!query.data?.length)return <EmptyState title="Расхождений не найдено" text="Это означает только, что в сохранённых данных пока нет зафиксированных reconciliation findings."/>;return <div className="table-wrap"><table><thead><tr><th>Тип</th><th>Кампания</th><th>Ожидалось</th><th>Фактически</th><th>Уровень</th><th>Описание</th><th>Дата</th></tr></thead><tbody>{query.data.map(item=><tr key={item.id}><td>{item.kind}</td><td className="mono">{item.campaign_id||"—"}</td><td>{item.expected_minor}</td><td>{item.actual_minor}</td><td><StatusBadge value={item.severity}/></td><td>{item.explanation}</td><td><time>{new Date(item.observed_at).toLocaleString("ru-RU")}</time></td></tr>)}</tbody></table></div>}
