import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {Page} from "./Page";
import {Dialog} from "../components/Dialog";
import {useToast} from "../components/Toast";
type Item={id:string;requester_id:string;action:string;resource_type:string;resource_id:string;risk:string;state:string;current_stage:number;expires_at:string;requested_at:string;version:number};
type Policy={id:string;name:string;action:string;resource_type:string;minimum_risk:string;request_ttl_minutes:number;escalate_after_minutes:number;separation_of_duties:boolean;required_approvals:number;eligible_scope:string;active:boolean;version:number};
function items(v:unknown):Item[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid approvals");return root.items as Item[]}
function policies(v:unknown):Policy[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid policies");return root.items as Policy[]}
const states:Record<string,string>={pending:"Ожидает решения",approved:"Одобрено",rejected:"Отклонено",expired:"Срок истёк",cancelled:"Отменено",executing:"Выполняется",completed:"Завершено",failed:"Ошибка"};
const risks:Record<string,string>={write_sensitive:"Чувствительное изменение",legally_significant:"Юридически значимое"};
const actions:Record<string,string>={"demo.dataset.delete":"Удаление демонстрационных данных","demo.catalog.publish":"Публикация демонстрационного товара"};
export function ApprovalsPage(){
 const api=useApi(),cache=useQueryClient(),toast=useToast(),[confirmExecute,setConfirmExecute]=useState<Item|null>(null),[name,setName]=useState("Удаление демо-данных"),[ttl,setTTL]=useState(1440),[approvals,setApprovals]=useState(1),[separation,setSeparation]=useState(false),[editing,setEditing]=useState<Policy|null>(null);
 const requests=useQuery({queryKey:["approvals"],queryFn:async()=>items((await api.listApprovals()).body),staleTime:10_000});
 const policyQuery=useQuery({queryKey:["approval-policies"],queryFn:async()=>policies((await api.listApprovalPolicies()).body)});
 const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:["approvals"]}),cache.invalidateQueries({queryKey:["approval-policies"]}),cache.invalidateQueries({queryKey:["audit"]})]);
 const createPolicy=useMutation({mutationFn:async()=>api.createApprovalPolicy({idempotencyKey:crypto.randomUUID(),body:{id:editing?.id??crypto.randomUUID(),name,action:"demo.dataset.delete",resource_type:"demo_dataset",minimum_risk:"write_sensitive",version:(editing?.version??0)+1,request_ttl_minutes:ttl,escalate_after_minutes:Math.min(60,ttl-1),separation_of_duties:separation,required_approvals:approvals,eligible_scope:"approval.demo"}}),onSuccess:async()=>{setEditing(null);await refresh()}});
 const retire=useMutation({mutationFn:async(p:Policy)=>api.retireApprovalPolicy({policyId:p.id,expectedVersion:p.version,idempotencyKey:crypto.randomUUID()}),onSuccess:refresh});
 const requestDelete=useMutation({mutationFn:async()=>api.createApprovalRequest({idempotencyKey:crypto.randomUUID(),body:{action:"demo.dataset.delete",resource_type:"demo_dataset",resource_id:"",risk:"write_sensitive"}}),onSuccess:refresh});
 const decide=useMutation({mutationFn:async({item,vote}:{item:Item;vote:"approve"|"reject"})=>api.decideApproval({requestId:item.id,idempotencyKey:crypto.randomUUID(),body:{vote,expected_version:item.version}}),onSuccess:refresh});
 const execute=useMutation({mutationFn:async(item:Item)=>api.executeApproval({requestId:item.id,idempotencyKey:crypto.randomUUID()}),onSuccess:async()=>{setConfirmExecute(null);toast.push({kind:"success",title:"Согласованная операция запущена"});await refresh()},onError:()=>toast.push({kind:"error",title:"Не удалось выполнить согласованную операцию"})});
 return <Page eyebrow="Контроль операций" title="Согласования" description="Политики и запросы на подтверждение реальных чувствительных операций.">
  <section className="panel settings-card"><div className="section-heading"><div><h2>Редактор политики</h2><p>Изменение создаёт новую неизменяемую версию политики.</p></div></div><div className="settings-form"><label className="field"><span>Название</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Срок решения, минут</span><input type="number" min="2" max="43200" value={ttl} onChange={e=>setTTL(Number(e.target.value))}/></label><label className="field"><span>Количество одобрений</span><input type="number" min="1" max="32" value={approvals} onChange={e=>setApprovals(Number(e.target.value))}/></label><label className="field"><span><input type="checkbox" checked={separation} onChange={e=>setSeparation(e.target.checked)}/> Запретить автору согласовывать свой запрос</span></label><div className="button-row"><button className="button primary" disabled={!name||ttl<2||createPolicy.isPending} onClick={()=>createPolicy.mutate()}>{editing?`Сохранить версию ${editing.version+1}`:"Создать политику удаления демо-данных"}</button>{editing?<button className="button ghost" onClick={()=>setEditing(null)}>Отмена</button>:null}</div>{createPolicy.isError?<ErrorBlock>Не удалось сохранить политику.</ErrorBlock>:null}</div></section>
  <section><div className="section-heading"><div><h2>Политики</h2></div><button className="button primary" disabled={requestDelete.isPending||!policyQuery.data?.some(p=>p.active&&p.action==="demo.dataset.delete")} onClick={()=>requestDelete.mutate()}>Запросить удаление демо-данных</button></div>{policyQuery.isPending?<LoadingBlock/>:policyQuery.isError?<ErrorBlock retry={()=>void policyQuery.refetch()}>Не удалось загрузить политики.</ErrorBlock>:policyQuery.data.length===0?<EmptyState title="Политик пока нет" text="Создайте правило для чувствительной операции выше."/>:<div className="table-wrap"><table><thead><tr><th>Политика</th><th>Операция</th><th>Риск</th><th>Требования</th><th>Версия</th><th></th></tr></thead><tbody>{policyQuery.data.map(p=><tr key={p.id}><td>{p.name}<br/><StatusBadge value={p.active?"active":"disabled"}/></td><td>{actions[p.action]??p.action}</td><td>{risks[p.minimum_risk]??p.minimum_risk}</td><td>{p.required_approvals} реш. · {p.request_ttl_minutes} мин.{p.separation_of_duties?" · разделение обязанностей":""}</td><td>{p.version}</td><td><div className="button-row"><button className="button ghost" onClick={()=>{setEditing(p);setName(p.name);setTTL(p.request_ttl_minutes);setApprovals(p.required_approvals);setSeparation(p.separation_of_duties)}}>Изменить</button>{p.active?<button className="button danger" disabled={retire.isPending} onClick={()=>retire.mutate(p)}>Отключить</button>:null}</div></td></tr>)}</tbody></table></div>}{requestDelete.isError?<ErrorBlock>Нужна активная политика для этой операции.</ErrorBlock>:null}</section>
  <section><div className="section-heading"><div><h2>Запросы</h2></div></div>{requests.isPending?<LoadingBlock/>:requests.isError?<ErrorBlock retry={()=>void requests.refetch()}>Не удалось загрузить запросы.</ErrorBlock>:requests.data.length===0?<EmptyState title="Запросов пока нет" text="Создайте политику и запросите чувствительную операцию."/>:<div className="table-wrap"><table><thead><tr><th>Запрошено</th><th>Операция</th><th>Риск</th><th>Состояние</th><th>Срок</th><th>Действие</th></tr></thead><tbody>{requests.data.map(v=><tr key={v.id}><td>{new Date(v.requested_at).toLocaleString("ru-RU")}<br/><span className="mono">{v.requester_id}</span></td><td>{actions[v.action]??v.action}</td><td>{risks[v.risk]??v.risk}</td><td><StatusBadge value={states[v.state]??v.state}/></td><td>{new Date(v.expires_at).toLocaleString("ru-RU")}</td><td>{v.state==="pending"?<div className="button-row"><button className="button primary" disabled={decide.isPending} onClick={()=>decide.mutate({item:v,vote:"approve"})}>Одобрить</button><button className="button danger" disabled={decide.isPending} onClick={()=>decide.mutate({item:v,vote:"reject"})}>Отклонить</button></div>:v.state==="approved"?<button className="button danger" disabled={execute.isPending} onClick={()=>setConfirmExecute(v)}>Выполнить операцию</button>:"—"}</td></tr>)}</tbody></table></div>}</section>
 <Dialog open={!!confirmExecute} title="Выполнить чувствительную операцию?" description="Решение уже согласовано, но само выполнение может изменить или удалить данные." onClose={()=>setConfirmExecute(null)}><div className="dialog-actions"><button className="button ghost" onClick={()=>setConfirmExecute(null)}>Отмена</button><button className="button danger" disabled={execute.isPending} onClick={()=>confirmExecute&&execute.mutate(confirmExecute)}>{execute.isPending?"Выполняем…":"Подтвердить выполнение"}</button></div></Dialog>
 </Page>
}
