import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {EmptyState} from "../components/EmptyState";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {Page} from "./Page";

interface AuditRecord {id:string;actor_id:string;source:string;action:string;resource_type:string;resource_id:string;correlation_id:string;risk:string;summary:Record<string,unknown>;created_at:string}
function decode(value:unknown):AuditRecord[]{const root=value as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid audit page");return root.items as AuditRecord[]}
function summary(value:Record<string,unknown>){const entries=Object.entries(value);return entries.length===0?"—":entries.map(([key,item])=>`${key}: ${typeof item==="object"?JSON.stringify(item):String(item)}`).join(" · ")}

export function AuditPage(){const api=useApi();const queryClient=useQueryClient();const query=useQuery({queryKey:["audit"],queryFn:async()=>decode((await api.listAuditRecords({limit:100})).body),staleTime:15_000});const demo=useMutation({mutationFn:async()=>api.createDemoOrders({idempotencyKey:"demo-dataset:audit-preview"}),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["audit"]});}});return <Page eyebrow="Governance" title="Аудит" description="Неизменяемая tenant-scoped история привилегированных и операционных действий.">{query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock>Не удалось загрузить журнал аудита.</ErrorBlock>:query.data.length===0?<EmptyState title="Записей аудита пока нет" text="Изменения workspace, подключений и другие контролируемые операции появятся здесь автоматически."><button className="button primary" disabled={demo.isPending} onClick={()=>demo.mutate()}>{demo.isPending?"Создаём…":"Создать демо-запись"}</button>{demo.isError?<ErrorBlock>Не удалось создать демонстрационную запись.</ErrorBlock>:null}</EmptyState>:<div className="table-wrap"><table><thead><tr><th>Время</th><th>Действие</th><th>Ресурс</th><th>Субъект</th><th>Риск</th><th>Сводка</th></tr></thead><tbody>{query.data.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString("ru-RU")}<br/><span className="mono">{item.source}</span></td><td><strong>{item.action}</strong><br/><span className="mono">{item.correlation_id}</span></td><td>{item.resource_type}<br/><span className="mono">{item.resource_id}</span></td><td className="mono">{item.actor_id}</td><td><StatusBadge value={item.risk}/></td><td className="audit-summary">{summary(item.summary)}</td></tr>)}</tbody></table></div>}</Page>}
