import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {decodeItems as decode} from "../api/decoders";
import {EmptyState} from "../components/EmptyState";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {auditActionLabel,auditResourceLabel,auditSourceLabel,humanizeTechnicalValue} from "../components/labels";
import {Page} from "./Page";

interface AuditRecord {id:string;actor_id:string;source:string;action:string;resource_type:string;resource_id:string;correlation_id:string;risk:string;summary:Record<string,unknown>;created_at:string}
const summaryLabels:Readonly<Record<string,string>>={actor_id:"Субъект",account_id:"Кабинет",code:"Код",connector_id:"Интеграция",enabled:"Включено",error_code:"Код ошибки",expires_at:"Срок действия",interval_minutes:"Интервал, мин.",job_id:"Задание",mode:"Режим",new_status:"Новое состояние",old_status:"Предыдущее состояние",policy_count:"Политик",preview_id:"Предпросмотр",reason:"Причина",schedule_version:"Версия расписания",status:"Состояние",version:"Версия",warehouse_id:"Склад"};
function summary(value:Record<string,unknown>){const entries=Object.entries(value);return entries.length===0?"—":entries.map(([key,item])=>`${summaryLabels[key]??humanizeTechnicalValue(key)}: ${typeof item==="object"?JSON.stringify(item):String(item)}`).join(" · ")}

export function AuditPage(){const api=useApi();const query=useQuery({queryKey:["audit"],queryFn:async()=>decode((await api.listAuditRecords({limit:100})).body),staleTime:15_000});return <Page eyebrow="Управление" title="Аудит" description="Неизменяемая история привилегированных и операционных действий в рабочем пространстве.">{query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить журнал аудита.</ErrorBlock>:query.data.length===0?<EmptyState title="Записей аудита пока нет" text="Изменения рабочего пространства, подключений и другие контролируемые операции появятся здесь автоматически. Заполните весь демо-контур на главной странице, чтобы увидеть пример журнала."/>:<div className="table-wrap"><table><thead><tr><th>Время</th><th>Действие</th><th>Ресурс</th><th>Субъект</th><th>Риск</th><th>Сводка</th></tr></thead><tbody>{query.data.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString("ru-RU")}<br/><span className="mono">{auditSourceLabel(item.source)}</span></td><td><strong>{auditActionLabel(item.action)}</strong><br/><span className="mono">{item.correlation_id}</span></td><td>{auditResourceLabel(item.resource_type)}<br/><span className="mono">{item.resource_id}</span></td><td className="mono">{item.actor_id}</td><td><StatusBadge value={item.risk}/></td><td className="audit-summary">{summary(item.summary)}</td></tr>)}</tbody></table></div>}</Page>}
