import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {Page} from "./Page";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";

type Evidence={kind?:string;source_ref?:string;checked_at?:string;environment?:string};
type PortfolioItem={id:string;kind:string;tier:string;display_name:string;status:string;owner:string;priority:string;decision:string;next_action:string;support_level:string;deployment:string;capabilities?:string[];evidence?:Evidence};
type Overview={status_counts?:Record<string,number>;portfolio?:PortfolioItem[];visible_apps?:number;onboarding?:Array<{id:string;resource_id:string;state:string;checks:Array<{id:string;label:string;required:boolean;state:string}>}>;partners?:Array<{id:string;partner_ref:string;tier:string;state:string;expires_at:string}>;mobile?:Array<{id:string;target:string;status:string;capabilities:string[];offline_policy:string}>;hosted_tiers?:Array<{id:string;name:string;deployment:string;support_level:string;sla_claimable:boolean;recovery_point_minutes:number;recovery_time_minutes:number}>;support?:{open_cases:number;at_risk_cases:number;diagnostics:string;policies:Array<{tier:string;coverage:string;first_response_minutes:number;resolution_target_minutes:number}>};metrics?:Array<{name:string;value:number;unit:string;state:string}>;external_gates?:string[]};

const statusLabels:Record<string,string>={integrated:"Интегрировано",verified:"Проверено",ready:"Готово к runtime",qualified:"Квалифицировано",supported:"Поддерживается",deprecated:"Устарело",blocked:"Заблокировано",running:"Проверяется",blocked_onboarding:"Заблокировано",ready_onboarding:"Готово",applied:"Заявлен",sandbox_ready:"Sandbox готов",certified:"Сертифицирован",suspended:"Приостановлен",revoked:"Отозван"};
const status=(value:string)=><StatusBadge value={statusLabels[value]??value}/>;
const date=(value?:string)=>value?new Date(value).toLocaleString("ru-RU"):"—";

export function EcosystemPage(){
 const api=useApi() as any;
 const query=useQuery({queryKey:["ecosystem-overview"],queryFn:async()=>((await api.getEcosystemOverview()).body as Overview),staleTime:30_000});
 if(query.isPending)return <Page eyebrow="Экосистема" title="Интеграции и поддержка" description="Портфель, внедрение, мобильная работа, cloud-режим и фактические release-gates в одном месте."><LoadingBlock/></Page>;
 if(query.isError)return <Page eyebrow="Экосистема" title="Интеграции и поддержка" description="Портфель, внедрение, мобильная работа, cloud-режим и фактические release-gates в одном месте."><ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить ecosystem overview.</ErrorBlock></Page>;
 const data=query.data??{};const counts=data.status_counts??{};const portfolio=data.portfolio??[];const onboarding=data.onboarding??[];const partners=data.partners??[];const support=data.support;
 return <Page eyebrow="Экосистема" title="Интеграции и поддержка" description="Портфель, внедрение, мобильная работа, cloud-режим и фактические release-gates в одном месте.">
  <section className="integration-center-summary ecosystem-summary" aria-label="Уровни готовности"><Metric label="Интегрировано" value={counts.integrated??0}/><Metric label="Проверено" value={counts.verified??0}/><Metric label="Готово к runtime" value={counts.ready??0}/><Metric label="Квалифицировано" value={counts.qualified??0}/><Metric label="Поддерживается" value={counts.supported??0}/><Metric label="Приложений" value={data.visible_apps??0}/></section>
  <div className="panel alert warning ecosystem-notice" role="status"><strong>Статус без маркетинговых обещаний.</strong> `qualified` и `supported` появляются только после сохранённого evidence. Community и hosted не получают SLA автоматически.</div>
  <section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Portfolio</p><h2>Что реально доступно</h2><p>Манифест или health-check показывают наличие поверхности, но не заменяют runtime и qualification.</p></div></div><div className="table-wrap"><table><thead><tr><th>Ресурс</th><th>Уровень</th><th>Владелец</th><th>Приоритет</th><th>Следующее действие</th><th>Evidence</th></tr></thead><tbody>{portfolio.map(item=><tr key={item.id}><td><strong>{item.display_name}</strong><small className="table-subline mono">{item.id} · {item.tier}</small></td><td>{status(item.status)}<small className="table-subline">{item.support_level}</small></td><td>{item.owner}</td><td>{item.priority}</td><td>{item.next_action}</td><td>{item.evidence?<><span>{item.evidence.kind}</span><small className="table-subline">{date(item.evidence.checked_at)}</small></>:"Нет подтверждения"}</td></tr>)}</tbody></table></div></section>
  <div className="ecosystem-columns"><section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Onboarding</p><h2>Проверка подключения</h2></div></div>{onboarding.length===0?<p className="settings-note">Запусков onboarding пока нет.</p>:<div className="ecosystem-list">{onboarding.map(run=><article key={run.id}><div><strong>{run.resource_id}</strong><small>{run.checks.filter(check=>check.required&&check.state==="passed").length}/{run.checks.filter(check=>check.required).length} обязательных проверок</small></div>{status(run.state==="blocked"?"blocked_onboarding":run.state+"_onboarding")}</article>)}</div>}<p className="settings-note">Новая проверка создаётся через API с `Idempotency-Key`; она не выполняет remote write сама.</p></section><section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Partners</p><h2>Партнёрская сеть</h2></div></div>{partners.length===0?<p className="settings-note">Сертифицированных партнёров пока нет.</p>:<div className="ecosystem-list">{partners.map(partner=><article key={partner.id}><div><strong>{partner.partner_ref}</strong><small>{partner.tier} · до {date(partner.expires_at)}</small></div>{status(partner.state)}</article>)}</div>}<p className="settings-note">Сертификация требует UAT, rollback и отдельного подтверждения среды.</p></section></div>
  <div className="ecosystem-columns"><section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Mobile</p><h2>Мобильная доставка</h2></div></div>{(data.mobile??[]).map(surface=><article className="ecosystem-card" key={surface.id}><div><strong>{surface.target}</strong><small>{surface.offline_policy}</small></div>{status(surface.status)}<p>{surface.capabilities.join(" · ")}</p></article>)}</section><section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Cloud</p><h2>Hosted tiers и SLO</h2></div></div>{(data.hosted_tiers??[]).map(tier=><article className="ecosystem-card" key={tier.id}><div><strong>{tier.name}</strong><small>{tier.deployment} · {tier.support_level}</small></div><span className={`status ${tier.sla_claimable?"status-active":"status-warning"}`}>{tier.sla_claimable?"SLA подтверждён":"Квалификация нужна"}</span><p>RPO {tier.recovery_point_minutes} мин · RTO {tier.recovery_time_minutes} мин</p></article>)}</section></div>
  <section className="panel ecosystem-section"><div className="section-heading"><div><p className="eyebrow">Support</p><h2>Поддержка и измерения</h2></div></div><div className="settings-facts"><div><dt>Открытые обращения</dt><dd>{support?.open_cases??0}</dd></div><div><dt>На грани SLA</dt><dd>{support?.at_risk_cases??0}</dd></div><div><dt>Метрик</dt><dd>{data.metrics?.length??0}</dd></div></div><p className="settings-note">{support?.diagnostics??"Операционные цели ещё не загружены."}</p><div className="chip-list">{(data.external_gates??[]).map(gate=><span className="chip" key={gate}>{gate}</span>)}</div></section>
 </Page>
}

function Metric({label,value}:{label:string;value:number}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}
