import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {EmptyState} from "../components/EmptyState";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {Page} from "./Page";

interface Column {key:string;label:string}
interface Report {id:string;generated_at:string;source:string;columns:Column[];rows:string[][]}
interface CompletenessComponent {code:string;label:string;quality:string;required:boolean;evidence_count:number;amount_minor_units:number;currency:string;reason?:string}
interface Completeness {matrix:{code:string;label:string;canonical_source:string;fallback:string;required_for:string[];retention:string}[];evaluation:{basis:string;from:string;to:string;reporting_currency?:string;status:string;coverage_percent:number;components:CompletenessComponent[];missing_codes?:string[];warnings?:string[];source_refs:string[]};source_count:number;open_finding_count:number;last_observed_at?:string}
interface Finding {id:string;kind:string;subject_ref:string;expected_minor_units:number;observed_minor_units:number;currency:string;severity:string;status:string;explanation:string;detected_at:string}
type Tab="pnl"|"cash"|"unit"|"quality"|"completeness";

function read(value:unknown):Report {const report=value as Report;if(!report||!Array.isArray(report.columns)||!Array.isArray(report.rows))throw new Error("invalid financial report");return report}
function readCompleteness(value:unknown):Completeness {const summary=value as Completeness;if(!summary?.evaluation||!Array.isArray(summary.evaluation.components))throw new Error("invalid financial completeness");return summary}
function money(value:string,currency:string){if(value==="—"||value==="")return "—";return new Intl.NumberFormat("ru-RU",{style:"currency",currency:currency||"RUB",maximumFractionDigits:2}).format(Number(value)/100)}
function amount(value:number,currency:string,quality:string){return quality==="missing"||quality==="unmatched"?"Нет подтверждённых данных":money(String(value),currency||"RUB")}
function qualityLabel(value:string){return ({observed:"Наблюдается",confirmed:"Подтверждено",estimated:"Оценка",missing:"Нет источника",unmatched:"Не сопоставлено",stale:"Устарело",disputed:"Оспаривается",conflict:"Конфликт"} as Record<string,string>)[value]??value}
function statusLabel(value:string){return ({complete:"Полный контур",partial:"Неполный контур",stale:"Есть устаревшие данные",unmatched:"Есть несопоставленные данные",disputed:"Есть спорные данные",conflict:"Есть конфликт источников"} as Record<string,string>)[value]??value}
function formatCell(value:string,column:Column,row:string[]){if(value===""||value==="—")return "—";if(column.key.endsWith("_minor_units"))return money(value,row[1]||"RUB");if(column.key.endsWith("_basis_points"))return `${(Number(value)/100).toLocaleString("ru-RU",{maximumFractionDigits:2})}%`;if(column.key==="coverage_percent")return `${value}%`;return value}
function makeRange(days:number){const end=new Date();const start=new Date(end);start.setUTCDate(end.getUTCDate()-days+1);return {from:start.toISOString(),to:end.toISOString()}}

export function FinancialAnalyticsPage(){
 const api=useApi();const [tab,setTab]=useState<Tab>("pnl");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [currency,setCurrency]=useState("");
 const range=from&&to?{from:new Date(`${from}T00:00:00Z`).toISOString(),to:new Date(`${to}T23:59:59Z`).toISOString()}:{};
 const query=useQuery<Report|Completeness>({queryKey:["seller-financial",tab,from,to,currency],queryFn:async()=>{if(tab==="completeness"){const response=await api.getFinancialCompleteness({basis:"order_accrual",...range,currency:currency||undefined});return readCompleteness(response.body)}const input={...range,currency:currency||undefined,limit:200};const response=tab==="pnl"?await api.getSellerProfitAndLoss(input):tab==="cash"?await api.getSellerCashFlow(input):tab==="unit"?await api.getSellerUnitEconomics(input):await api.getSellerFinancialQuality(input);return read(response.body)},staleTime:30_000});
 const findings=useQuery({queryKey:["financial-completeness-findings"],queryFn:async()=>{const response=await api.listFinancialCompletenessFindings({limit:20});const body=response.body as {items?:Finding[]};return body.items??[]},enabled:tab==="completeness",staleTime:30_000});
 const completeness=tab==="completeness"?query.data as Completeness|undefined:undefined;
 const preset=(days:number)=>{const value=makeRange(days);setFrom(value.from.slice(0,10));setTo(value.to.slice(0,10))};
 return <Page eyebrow="Управленческий контур" title="Финансовая аналитика" description="P&L, денежный поток и юнит-экономика продавца на основе сохранённого расчётного снимка.">
  <div className="catalog-tabs" role="tablist"><button role="tab" aria-selected={tab==="pnl"} className={tab==="pnl"?"active":""} onClick={()=>setTab("pnl")}>P&L</button><button role="tab" aria-selected={tab==="cash"} className={tab==="cash"?"active":""} onClick={()=>setTab("cash")}>Денежный поток</button><button role="tab" aria-selected={tab==="unit"} className={tab==="unit"?"active":""} onClick={()=>setTab("unit")}>Юнит-экономика</button><button role="tab" aria-selected={tab==="quality"} className={tab==="quality"?"active":""} onClick={()=>setTab("quality")}>Качество данных</button><button role="tab" aria-selected={tab==="completeness"} className={tab==="completeness"?"active":""} onClick={()=>setTab("completeness")}>Полнота данных</button></div>
  <section className="panel report-result"><div className="analytics-presets"><button className="button ghost" onClick={()=>preset(7)}>7 дней</button><button className="button ghost" onClick={()=>preset(30)}>30 дней</button><button className="button ghost" onClick={()=>preset(90)}>90 дней</button></div><div className="report-filters"><label>С даты<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>По дату<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><label>Валюта<select value={currency} onChange={event=>setCurrency(event.target.value)}><option value="">Все валюты</option><option>RUB</option><option>USD</option><option>EUR</option></select></label></div>
   {query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить финансовые данные. Проверьте доступ и повторите запрос.</ErrorBlock>:tab==="completeness"&&completeness?<CompletenessPanel summary={completeness} findings={findings.data??[]} findingsError={findings.isError}/>:!query.data||!(query.data as Report).rows?.length?<EmptyState title="Расчётных данных пока нет" text="Worker формирует снимок за предыдущий UTC-день. Для ручного запуска используйте API финансовых расчётов."/>:<><p className="settings-note">Снимок от {new Date((query.data as Report).generated_at).toLocaleString("ru-RU")} · {(query.data as Report).source} · отсутствующие факты отмечены статусом и не заменены нулём.</p><div className="table-wrap"><table><thead><tr>{(query.data as Report).columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{(query.data as Report).rows.map((row,index)=><tr key={index}>{(query.data as Report).columns.map((column,columnIndex)=><td key={column.key}>{formatCell(row[columnIndex]??"",column,row)}</td>)}</tr>)}</tbody></table></div></>}
  </section>
 </Page>
}

function CompletenessPanel({summary,findings,findingsError}:{summary:Completeness;findings:Finding[];findingsError:boolean}){
 const evaluation=summary.evaluation;const currency=evaluation.reporting_currency||"RUB";
 return <div className="catalog-stack"><div className="settings-facts"><div><dt>Статус</dt><dd>{statusLabel(evaluation.status)}</dd></div><div><dt>Покрытие</dt><dd>{evaluation.coverage_percent}%</dd></div><div><dt>Источники</dt><dd>{summary.source_count}</dd></div><div><dt>Открытые расхождения</dt><dd>{summary.open_finding_count}</dd></div><div><dt>Basis</dt><dd>{evaluation.basis}</dd></div><div><dt>Период</dt><dd>{new Date(evaluation.from).toLocaleDateString("ru-RU")} — {new Date(evaluation.to).toLocaleDateString("ru-RU")}</dd></div></div><p className="settings-note">Суммы считаются только по наблюдаемым источникам. Отсутствующий банк, COGS, FX, реклама или промо остаётся пропуском и не превращается в ноль.</p><div className="table-wrap"><table><thead><tr><th>Компонент</th><th>Источник</th><th>Статус</th><th>Фактов</th><th>Сумма</th><th>Комментарий</th></tr></thead><tbody>{evaluation.components.map(component=>{const requirement=summary.matrix.find(item=>item.code===component.code);return <tr key={component.code}><td><strong>{component.label}</strong><small className="table-subline mono">{component.code}</small></td><td>{requirement?.canonical_source??"—"}</td><td><span className={component.quality==="missing"?"status-badge attention":"status-badge"}>{qualityLabel(component.quality)}</span></td><td>{component.evidence_count}</td><td>{amount(component.amount_minor_units,component.currency||currency,component.quality)}</td><td>{component.reason||"Источник найден"}</td></tr>})}</tbody></table></div><section className="drawer-section"><div className="settings-card-heading"><div><h3>Очередь расхождений</h3><p className="settings-copy">Открытые findings требуют подтверждения источника или отдельного adjustment с audit.</p></div></div>{findingsError?<p className="settings-note">Очередь временно недоступна, предыдущие данные не скрыты.</p>:findings.length===0?<p className="settings-note">Открытых расхождений нет.</p>:<div className="chip-list">{findings.map(finding=><span className="chip" key={finding.id}>{finding.kind} · {finding.subject_ref||"без объекта"} · {finding.status}</span>)}</div>}</section></div>
}
