import {useEffect,useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {useLocationPath,navigate} from "../shell/useLocationPath";
import {Page} from "./Page";
import {DataTable} from "../components/DataTable";
import {Drawer} from "../components/Drawer";
import {StatusBadge} from "../components/StatusBadge";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";

type CenterRow={account_id:string;connector_id:string;display_name?:string;family:string;surface:string;overall:string;version:number;generated_at:string;dimensions:Record<string,{status:string;evidence?:{checked_at?:string;age_seconds?:number;visibility?:string}}>;capabilities:Array<{name:string;status:string;direction:string;approval_required:boolean}>;issues:Array<{code:string;title:string;severity:string;reason_code:string}>;available_actions:Array<{id:string;label:string;href?:string;permission:string;expected_version:number}>;snapshot_digest:string};
type CenterResponse={items?:CenterRow[];summary?:Record<string,number>;partial?:boolean;generated_at?:string;snapshot_digest?:string;next_cursor?:string;source_watermarks?:string[]};
type ReadinessCapability={name:string;status:string;direction:string;required_scopes?:string[];risk_class:string;idempotency:string;read_after_write:string;webhook_or_reconciliation:boolean;runtime_evidence:string};
type ReadinessProfile={connector_id:string;display_name:string;family:string;surface:string;status:string;owner:string;priority:string;decision:string;next_action:string;official_docs_ref:string;official_docs_status:string;sandbox_status:string;live_qualification_status:string;last_verified_at:string;conformance_ref:string;runtime_ref:string;health_only:boolean;capabilities:ReadinessCapability[];blockers:string[];rate_limit:{max_concurrency:number;min_interval_ms:number;request_timeout_ms:number;retry_max_attempts:number}};
type ReadinessResponse={items?:ReadinessProfile[];summary?:Record<string,number>;generated_at?:string;consistency?:string;next_cursor?:string};
const overallLabels:Record<string,string>={healthy:"Работает",attention:"Требует внимания",degraded:"Нестабильно",syncing:"Синхронизация",blocked:"Заблокировано",setup_required:"Нужно настроить",reauthorization_required:"Нужна авторизация",stale:"Устарело",disabled:"Отключено",unsupported:"Не подключено",unknown:"Нет данных"};
const statusLabels:Record<string,string>={ready:"Готово",manifest_only:"Только манифест",read_only:"Только чтение",partially_supported:"Частично доступно",qualified:"Квалифицировано",not_available:"Нет поддержки",separate_surface:"В отдельном разделе",health_only:"Только проверка",unsupported:"Не подключено",not_registered:"Не зарегистрировано",drifted:"Расхождение runtime",active:"Активен",disabled:"Отключён",suspended:"Приостановлен",error:"Ошибка",missing:"Не настроено",present:"Подтверждён",expired:"Истёк",reauthorization_required:"Нужна авторизация",invalid:"Недействителен",unknown:"Нет данных",valid:"Корректна",stale:"Устарела",healthy:"Здорово",degraded:"Нестабильно",unavailable:"Недоступно",not_declared:"Не заявлено",declared:"Заявлено",granted:"Выдано",enabled:"Включено",blocked:"Заблокировано",qualification_required:"Нужна квалификация",not_configured:"Не настроено",idle:"Ожидание",running:"Выполняется",retrying:"Повтор",failed:"Ошибка",paused:"Приостановлено",drift_open:"Есть расхождения",receiving:"Принимается",failing:"Ошибки доставки",available:"Доступен",limited:"Лимит достигнут",reset_unknown:"Сброс неизвестен",not_observed:"Не наблюдался"};
const readinessLabels:Record<string,string>={manifest_only:"Только манифест",health_only:"Только проверка связи",read_only:"Только чтение",partially_supported:"Частично доступно",ready:"Готово к runtime",qualified:"Квалифицировано",degraded:"Нестабильно",reauthorization_required:"Нужно переподключение",not_available:"Нет поддержки"};
const surfaceLabels:Record<string,string>={integrations:"Основные интеграции",ai_providers:"ИИ-провайдеры",ai:"ИИ-провайдеры",finance:"Финансы",logistics:"Доставка",crm:"CRM",social:"Социальные сети",unknown:"Не определено"};
const dimensionLabels:Record<string,string>={runtime:"Runtime",account:"Кабинет",credential:"Доступ",configuration:"Конфигурация",health:"Подключение",capability:"Операции",sync:"Синхронизация",reconciliation:"Сверка",webhook:"Webhook",rate_limit:"Лимит запросов"};
const stateLabel=(value?:string)=>statusLabels[value??"unknown"]??value??"Нет данных";
function StateBadge({value}:{value?:string}){const normalized=(value??"unknown").toLowerCase().replace(/[^a-z0-9]+/g,"-");return <span className={`status status-${normalized}`}>{stateLabel(value)}</span>}

function useSearchState(){
 const [search,setSearch]=useState(()=>window.location.search);
 useEffect(()=>{const onPop=()=>setSearch(window.location.search);window.addEventListener("popstate",onPop);return()=>window.removeEventListener("popstate",onPop)},[]);
 const update=(key:string,value:string)=>{const url=new URL(window.location.href);if(value)url.searchParams.set(key,value);else url.searchParams.delete(key);url.searchParams.delete("cursor");window.history.pushState({},"",url);setSearch(url.search)};
 return {params:useMemo(()=>new URLSearchParams(search),[search]),update};
}

export function IntegrationStatusPage(){
 const api=useApi() as any;const path=useLocationPath();const {params,update}=useSearchState();
 const queryParams={limit:50,cursor:params.get("cursor")||undefined,family:params.get("family")||undefined,surface:params.get("surface")||undefined,overall:params.get("overall")||undefined,health:params.get("health")||undefined,sync:params.get("sync")||undefined,capability:params.get("capability")||undefined,issue:params.get("issue")||undefined,stale:params.get("stale")==="true"?true:undefined};
 const query=useQuery({queryKey:["integration-center",params.toString()],queryFn:async()=>((await api.getIntegrationCenter(queryParams)).body as CenterResponse),staleTime:10_000});
 const readinessQuery=useQuery({queryKey:["connector-readiness"],queryFn:async()=>((await api.listConnectorReadiness({limit:100})).body as ReadinessResponse),staleTime:60_000});
 const selectedID=path.startsWith("/integrations/status/")?decodeURIComponent(path.slice("/integrations/status/".length)):undefined;
 const detail=useQuery({queryKey:["integration-center","detail",selectedID],enabled:Boolean(selectedID),queryFn:async()=>((await api.getIntegrationCenterAccount({accountId:selectedID})).body as CenterRow)});
 const items=query.data?.items??[];const summary=query.data?.summary??{};
 const columns=[
  {key:"connector",label:"Интеграция",value:(v:CenterRow)=>`${v.display_name||v.connector_id} ${v.connector_id}`,render:(v:CenterRow)=><span className="integration-center-name"><strong>{v.display_name||v.connector_id}</strong><small>{v.connector_id} · {surfaceLabels[v.surface]??v.surface}</small></span>},
  {key:"overall",label:"Итог",value:(v:CenterRow)=>v.overall,render:(v:CenterRow)=><StateBadge value={v.overall}/>},
  {key:"runtime",label:"Runtime",value:(v:CenterRow)=>v.dimensions.runtime?.status??"unknown",render:(v:CenterRow)=><span>{stateLabel(v.dimensions.runtime?.status)}</span>},
  {key:"health",label:"Подключение",value:(v:CenterRow)=>v.dimensions.health?.status??"unknown",render:(v:CenterRow)=><StateBadge value={v.dimensions.health?.status}/>},
  {key:"capability",label:"Операции",value:(v:CenterRow)=>v.dimensions.capability?.status??"unknown",render:(v:CenterRow)=><span>{stateLabel(v.dimensions.capability?.status)}</span>},
  {key:"sync",label:"Синхронизация",value:(v:CenterRow)=>v.dimensions.sync?.status??"unknown",render:(v:CenterRow)=><span>{stateLabel(v.dimensions.sync?.status)}</span>},
  {key:"issue",label:"Причина",value:(v:CenterRow)=>v.issues?.[0]?.title??"",render:(v:CenterRow)=><span className="table-subline">{v.issues?.[0]?.title??"Проверка без замечаний"}</span>}
 ];
 return <Page eyebrow="Интеграции" title="Состояние интеграций" description="Единая фактическая картина кабинетов, доступных операций, подключения и обмена. Чтение не выполняет удалённые проверки.">
  <section className="integration-center-summary" aria-label="Сводка состояния"><Metric label="Всего" value={summary.total??items.length}/><Metric label="Работают" value={summary.healthy??0}/><Metric label="Внимание" value={summary.attention??0}/><Metric label="Заблокированы" value={summary.blocked??0}/><Metric label="Устарели" value={summary.stale??0}/><Metric label="Синхронизация" value={summary.syncing??0}/></section>
  {query.data?.partial?<div className="panel alert warning" role="status">Часть источников недоступна. Состояния с неполными данными не считаются зелёными.</div>:null}
  <div className="integration-center-filters"><label className="field"><span>Состояние</span><select value={params.get("overall")??""} onChange={e=>update("overall",e.target.value)}><option value="">Все состояния</option>{Object.entries(overallLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>Рабочий контур</span><select value={params.get("surface")??""} onChange={e=>update("surface",e.target.value)}><option value="">Все контуры</option>{Object.entries(surfaceLabels).filter(([key])=>key!=="unknown").map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>Семейство</span><input value={params.get("family")??""} placeholder="storefront, logistics…" onChange={e=>update("family",e.target.value)}/></label><label className="field"><span>Операция</span><input value={params.get("capability")??""} placeholder="products.write…" onChange={e=>update("capability",e.target.value)}/></label><button type="button" className="button ghost" onClick={()=>{window.history.pushState({},"",window.location.pathname);window.dispatchEvent(new PopStateEvent("popstate"))}}>Сбросить фильтры</button></div>
  {query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить состояние интеграций.</ErrorBlock>:<DataTable rows={items} columns={columns} rowKey={v=>v.account_id} searchPlaceholder="Кабинет, коннектор, причина…" empty="Нет кабинетов по выбранным фильтрам" onOpen={v=>navigate(`/integrations/status/${encodeURIComponent(v.account_id)}`)}/>} 
  <section className="panel connector-readiness-panel" aria-label="Глубина коннекторов"><div className="section-heading"><div><p className="eyebrow">Каталог runtime</p><h2>Глубина 61 коннектора</h2><p>Уровень показывает фактическую поверхность репозитория и наличие evidence. Health-check не даёт права на запись и не означает production qualification.</p></div><span className="status status-unknown">{readinessQuery.data?.consistency??"repository_snapshot"}</span></div>{readinessQuery.isPending?<LoadingBlock/>:readinessQuery.isError?<ErrorBlock retry={()=>void readinessQuery.refetch()}>Не удалось загрузить матрицу глубины коннекторов.</ErrorBlock>:<><div className="integration-center-summary readiness-summary"><Metric label="Всего" value={readinessQuery.data?.summary?.total??readinessQuery.data?.items?.length??0}/><Metric label="Готовы к runtime" value={readinessQuery.data?.summary?.ready??0}/><Metric label="Только чтение" value={readinessQuery.data?.summary?.read_only??0}/><Metric label="Частично" value={readinessQuery.data?.summary?.partially_supported??0}/><Metric label="Health-only" value={readinessQuery.data?.summary?.health_only??0}/><Metric label="Квалифицированы" value={readinessQuery.data?.summary?.qualified??0}/></div><div className="table-wrap"><table><thead><tr><th>Коннектор</th><th>Глубина</th><th>Операции</th><th>Владелец / приоритет</th><th>Следующий шаг</th><th>Blocker</th></tr></thead><tbody>{(readinessQuery.data?.items??[]).map(profile=><tr key={profile.connector_id}><td><strong>{profile.display_name}</strong><small className="table-subline mono">{profile.connector_id} · {surfaceLabels[profile.surface]??profile.surface}</small></td><td><StateBadge value={profile.status}/><small className="table-subline">{readinessLabels[profile.status]??profile.status}</small></td><td>{profile.capabilities.length}<small className="table-subline">{profile.capabilities.filter(item=>item.direction==="write").length} write</small></td><td>{profile.owner}<small className="table-subline">{profile.priority}</small></td><td>{profile.next_action}</td><td>{profile.blockers.length?profile.blockers.join(", "):"—"}</td></tr>)}</tbody></table></div></>}</section>
  {query.data?.next_cursor?<div className="button-row integration-center-pagination"><button type="button" className="button ghost" onClick={()=>update("cursor",query.data?.next_cursor??"")}>Загрузить следующую страницу</button></div>:null}
  <p className="integration-center-footnote">Снимок: {query.data?.generated_at?new Date(query.data.generated_at).toLocaleString("ru-RU"):"—"} · digest <span className="mono">{query.data?.snapshot_digest?.slice(0,16)??"—"}</span></p>
  <Drawer open={Boolean(selectedID)} title={detail.data?.display_name||detail.data?.connector_id||"Состояние интеграции"} subtitle={selectedID?`Кабинет · ${selectedID}`:undefined} onClose={()=>navigate("/integrations/status")}><IntegrationDetail query={detail}/></Drawer>
 </Page>
}

function Metric({label,value}:{label:string;value:number}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong></article>}
function IntegrationDetail({query}:{query:any}){if(query.isPending)return <LoadingBlock/>;if(query.isError)return <ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить детали состояния.</ErrorBlock>;const row=query.data as CenterRow;return <div className="catalog-stack"><div className="drawer-kpis"><div><small>Итог</small><StateBadge value={row.overall}/></div><div><small>Runtime</small><strong>{stateLabel(row.dimensions.runtime?.status)}</strong></div><div><small>Версия кабинета</small><strong>{row.version}</strong></div></div><section className="drawer-section"><h3>Измерения</h3><dl className="detail-list">{Object.entries(row.dimensions).map(([key,value])=><div key={key}><dt>{dimensionLabels[key]??key}</dt><dd><StateBadge value={value.status}/>{value.evidence?.visibility==="redacted"?<small> нет прав на раздел</small>:value.evidence?.checked_at?<small> · {new Date(value.evidence.checked_at).toLocaleString("ru-RU")}</small>:null}</dd></div>)}</dl></section><section className="drawer-section"><h3>Доступные операции</h3>{row.capabilities?.length?<ul className="integration-capability-list">{row.capabilities.map(cap=><li key={`${cap.name}:${cap.direction}`}><span>{cap.name}</span><StateBadge value={cap.status}/>{cap.approval_required?<small> требуется согласование</small>:null}</li>)}</ul>:<p className="drawer-help">Операции не заявлены или не выданы. Сам факт подключения не даёт права на запись.</p>}</section>{row.issues?.length?<section className="drawer-section"><h3>Что требует внимания</h3>{row.issues.map(issue=><article className="integration-issue" key={issue.code}><StatusBadge value={issue.severity}/><span><strong>{issue.title}</strong><small>{issue.reason_code}</small></span></article>)}</section>:null}<section className="drawer-section"><h3>Следующее действие</h3>{row.available_actions?.length?row.available_actions.map(action=><button type="button" className="button ghost" key={action.id} onClick={()=>action.href?navigate(action.href):undefined}>{action.label}</button>):<p className="drawer-help">Действий нет: состояние фиксируется источниками системы.</p>}</section></div>}
