import {useEffect,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {Page} from "./Page";
import {DataTable} from "../components/DataTable";
import {Drawer} from "../components/Drawer";
import {useToast} from "../components/Toast";
import {Icon} from "../components/Icon";

type R={body:any};type Client={listInventoryPositions():Promise<R>;getInventoryPosition(x:object):Promise<R>;adjustInventoryPosition(x:object):Promise<R>;listInventoryWarehouses():Promise<R>;createInventoryWarehouse(x:object):Promise<R>;updateInventoryWarehouse(x:object):Promise<R>;importInventory(x:object):Promise<R>;listWarehouseIncidents():Promise<R>;getWarehouseIncident(x:object):Promise<R>;listFulfillmentAllocations():Promise<R>;getFulfillmentAllocation(x:object):Promise<R>;reserveFulfillmentAllocation(x:object):Promise<R>;getWarehouseOperationalState(x:object):Promise<R>;updateWarehouseOperationalState(x:object):Promise<R>;putWarehouseFailoverRoute(x:object):Promise<R>};
const operationalStates=[["active","Активен"],["degraded","Деградирован"],["unavailable","Недоступен"],["lost","Утрачен"]] as const;
const tabs=[["positions","Позиции"],["warehouses","Склады"],["incidents","Инциденты"],["allocations","Fulfillment"],["import","Импорт"]] as const;
export function InventoryPage(){const api=useApi() as unknown as Client,[tab,setTab]=useState("positions");return <Page eyebrow="Commerce Core" title="Остатки и fulfillment" description="ATP, резервы, состояния складов, автоматический failover и неизменяемая история исполнения."><div className="catalog-tabs inventory-tabs" role="tablist">{tabs.map(x=><button key={x[0]} role="tab" aria-selected={tab===x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{tab==="positions"?<Positions api={api}/>:tab==="warehouses"?<Warehouses api={api}/>:tab==="incidents"?<Incidents api={api}/>:tab==="allocations"?<Allocations api={api}/>:<Import api={api}/>}</Page>}
function Positions({api}:{api:Client}){const [id,setId]=useState("");const q=useQuery({queryKey:["inventory"],queryFn:async()=>((await api.listInventoryPositions()).body.items??[]) as any[]});const detail=useQuery({queryKey:["inventory-position",id],enabled:!!id,queryFn:async()=>(await api.getInventoryPosition({positionId:id})).body});if(q.isPending)return <LoadingBlock/>;if(q.isError)return <ErrorBlock>Не удалось загрузить остатки.</ErrorBlock>;const columns=[{key:"sku",label:"SKU / товар",value:(v:any)=>`${v.SKU} ${v.ProductTitle}`,render:(v:any)=><span><strong className="mono">{v.SKU}</strong><small className="table-subline">{v.ProductTitle}</small></span>},{key:"warehouse",label:"Склад",value:(v:any)=>`${v.WarehouseName} ${v.WarehouseCode}`,render:(v:any)=><span>{v.WarehouseName}<small className="table-subline mono">{v.WarehouseCode}</small></span>},{key:"onhand",label:"На складе",value:(v:any)=>v.OnHand,align:"end" as const},{key:"reserved",label:"Резерв",value:(v:any)=>v.Reserved,align:"end" as const},{key:"available",label:"ATP",value:(v:any)=>v.Available,render:(v:any)=><strong className={Number(v.Available)<=0?"danger-text":""}>{v.Available} {v.Unit}</strong>,align:"end" as const}];return <><DataTable rows={q.data} columns={columns} rowKey={v=>v.ID} searchPlaceholder="SKU, товар или склад…" onOpen={v=>setId(v.ID)}/><Drawer open={!!id} title={detail.data?.position?.SKU??"Складская позиция"} subtitle={detail.data?.position?`${detail.data.position.WarehouseName} · ${detail.data.position.ProductTitle}`:undefined} onClose={()=>setId("")}><>{detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock>Не удалось открыть позицию.</ErrorBlock>:detail.data?<PositionCard api={api} body={detail.data}/>:null}</></Drawer></>}
function PositionCard({api,body}:{api:Client;body:any}){const qc=useQueryClient(),toast=useToast(),p=body.position,[quantity,setQuantity]=useState(p.OnHand),[reason,setReason]=useState("manual_correction");const adjust=useMutation({mutationFn:()=>api.adjustInventoryPosition({positionId:p.ID,body:{quantity,reason,version:p.Version}}),onSuccess:async()=>{toast.push({kind:"success",title:"Остаток скорректирован",body:`${p.SKU} · ${p.WarehouseName}`});await qc.invalidateQueries({queryKey:["inventory"]});await qc.invalidateQueries({queryKey:["inventory-position",p.ID]})},onError:()=>toast.push({kind:"error",title:"Корректировка отклонена",body:"Проверьте резерв и актуальность версии."})});return <div className="catalog-stack"><div className="drawer-kpis"><div><small>На складе</small><strong>{p.OnHand} {p.Unit}</strong></div><div><small>Резерв</small><strong>{p.Reserved} {p.Unit}</strong></div><div><small>ATP</small><strong>{p.Available} {p.Unit}</strong></div></div><section className="drawer-section"><h3>Корректировка</h3><form className="drawer-form" onSubmit={e=>{e.preventDefault();adjust.mutate()}}><label className="field"><span>Фактический остаток</span><input required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="field"><span>Причина</span><input required value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button primary" disabled={adjust.isPending}>{adjust.isPending?"Проводим…":"Провести корректировку"}</button></form></section><section className="drawer-section"><h3>История движений</h3><div className="timeline">{(body.movements??[]).map((m:any)=><article key={m.ID}><span className="timeline-dot"/><div><strong>{movementName(m.Change)}</strong><small>{m.OldOnHand||"—"} → {m.OnHand} {m.Unit} · {m.Reason||"Системная операция"}</small><time>{new Date(m.OccurredAt).toLocaleString("ru-RU")}</time></div></article>)}</div></section></div>}
const movementName=(v:string)=>({created:"Позиция создана",on_hand_set:"Фактический остаток установлен",reserved:"Зарезервировано",released:"Резерв освобождён",consumed_reserved:"Резерв списан"}[v]??v);
function Warehouses({api}:{api:Client}){const qc=useQueryClient(),toast=useToast(),q=useQuery({queryKey:["inventory-warehouses"],queryFn:async()=>((await api.listInventoryWarehouses()).body.items??[]) as any[]});const [code,setCode]=useState(""),[name,setName]=useState("");const [operating,setOperating]=useState<any>(null);const create=useMutation({mutationFn:()=>api.createInventoryWarehouse({body:{code,name}}),onSuccess:async()=>{setCode("");setName("");toast.push({kind:"success",title:"Склад создан"});await qc.invalidateQueries({queryKey:["inventory-warehouses"]})}});const status=useMutation({mutationFn:(x:any)=>api.updateInventoryWarehouse({warehouseId:x.ID,body:{version:x.Version,status:x.Status==="active"?"disabled":"active"}}),onSuccess:async()=>qc.invalidateQueries({queryKey:["inventory-warehouses"]})});return <div className="catalog-stack"><section className="panel inline-create"><div><h2>Склады</h2><p>Создавайте точки хранения и управляйте доступностью для новых операций.</p></div><form onSubmit={e=>{e.preventDefault();create.mutate()}}><input required value={code} onChange={e=>setCode(e.target.value)} placeholder="Код склада"/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Название"/><button className="button primary">Создать</button></form></section>{q.isPending?<LoadingBlock/>:q.isError?<ErrorBlock>Не удалось загрузить склады.</ErrorBlock>:<div className="warehouse-grid">{q.data.map(x=><article className="card warehouse-card" key={x.ID}><span className="warehouse-icon"><Icon name="warehouse"/></span><div><strong>{x.Name}</strong><small className="mono">{x.Code}</small></div><StatusBadge value={x.Status}/><button className="button ghost" onClick={()=>setOperating(x)}>Failover</button><button className="button ghost" onClick={()=>status.mutate(x)}>{x.Status==="active"?"Отключить":"Включить"}</button></article>)}</div>}<Drawer open={!!operating} title={operating?`Failover · ${operating.Name}`:""} subtitle={operating?.Code} onClose={()=>setOperating(null)}>{operating?<WarehouseOperations api={api} warehouse={operating} others={q.data??[]}/>:null}</Drawer></div>}
function WarehouseOperations({api,warehouse,others}:{api:Client;warehouse:any;others:any[]}){const qc=useQueryClient(),toast=useToast();const state=useQuery({queryKey:["warehouse-operational-state",warehouse.ID],queryFn:async()=>(await api.getWarehouseOperationalState({warehouseId:warehouse.ID})).body});const [next,setNext]=useState("active"),[reason,setReason]=useState("");useEffect(()=>{if(state.data?.State)setNext(state.data.State)},[state.data?.State]);const updateState=useMutation({mutationFn:()=>api.updateWarehouseOperationalState({warehouseId:warehouse.ID,body:{state:next,reason:reason.trim()||undefined,version:state.data?.Version??0}}),onSuccess:async()=>{toast.push({kind:"success",title:"Состояние склада обновлено"});await qc.invalidateQueries({queryKey:["warehouse-operational-state",warehouse.ID]});await qc.invalidateQueries({queryKey:["warehouse-incidents"]})},onError:()=>toast.push({kind:"error",title:"Не удалось обновить состояние",body:"Кто-то мог обновить его раньше вас — откройте панель заново."})});const destinations=others.filter(o=>o.ID!==warehouse.ID);const [destination,setDestination]=useState(destinations[0]?.ID??""),[priority,setPriority]=useState(100),[enabled,setEnabled]=useState(true),[routeVersion,setRouteVersion]=useState(0);const route=useMutation({mutationFn:()=>api.putWarehouseFailoverRoute({warehouseId:warehouse.ID,destinationWarehouseId:destination,body:{priority,enabled,version:routeVersion}}),onSuccess:async()=>toast.push({kind:"success",title:"Маршрут failover сохранён"}),onError:()=>toast.push({kind:"error",title:"Не удалось сохранить маршрут",body:"Если маршрут уже существует, укажите его текущую версию."})});return <div className="catalog-stack">
 <section className="drawer-section">
  <h3>Операционное состояние</h3>
  <p className="settings-copy">UNAVAILABLE/LOST автоматически открывает инцидент и запускает переназначение резервов на резервные склады.</p>
  {state.isPending?<LoadingBlock/>:state.isError?<ErrorBlock>Не удалось получить состояние.</ErrorBlock>:<><div className="drawer-kpis"><div><small>Текущее</small><strong><StatusBadge value={state.data.State??"active"}/></strong></div><div><small>Версия</small><strong>{state.data.Version??0}</strong></div></div>
  <div className="settings-grid">
   <label className="field"><span>Новое состояние</span><select value={next} onChange={e=>setNext(e.target.value)}>{operationalStates.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
   <label className="field"><span>Причина (опционально)</span><input value={reason} maxLength={64} placeholder="warehouse_fire, power_outage…" onChange={e=>setReason(e.target.value)}/></label>
  </div>
  <div className="account-actions"><button className="button primary" disabled={updateState.isPending} onClick={()=>updateState.mutate()}>{updateState.isPending?"Обновляем…":"Обновить состояние"}</button></div></>}
 </section>
 <section className="drawer-section">
  <h3>Маршрут failover</h3>
  <p className="settings-copy">Явный резервный склад и приоритет. Списка существующих маршрутов API не отдаёт — если склад уже настроен, сохранение вернёт конфликт версии.</p>
  {destinations.length===0?<EmptyState title="Нет других складов" text="Создайте ещё один склад, чтобы настроить failover."/>:<><div className="settings-grid">
   <label className="field"><span>Резервный склад</span><select value={destination} onChange={e=>setDestination(e.target.value)}>{destinations.map(d=><option value={d.ID} key={d.ID}>{d.Name} ({d.Code})</option>)}</select></label>
   <label className="field"><span>Приоритет (1–10000)</span><input type="number" min={1} max={10000} value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label>
   <label className="field"><span>Версия (0 для нового маршрута)</span><input type="number" min={0} value={routeVersion} onChange={e=>setRouteVersion(Number(e.target.value))}/></label>
   <label className="check-row"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>Маршрут активен</span></label>
  </div>
  <div className="account-actions"><button className="button primary" disabled={route.isPending} onClick={()=>route.mutate()}>{route.isPending?"Сохраняем…":"Сохранить маршрут"}</button></div></>}
 </section>
</div>}
function Incidents({api}:{api:Client}){const [selected,setSelected]=useState<any>(null);const q=useQuery({queryKey:["warehouse-incidents"],queryFn:async()=>((await api.listWarehouseIncidents()).body.items??[]) as any[],refetchInterval:20_000});const detail=useQuery({queryKey:["warehouse-incident",selected?.ID],enabled:!!selected,queryFn:async()=>(await api.getWarehouseIncident({incidentId:selected.ID})).body});if(q.isPending)return <LoadingBlock/>;if(q.isError)return <ErrorBlock>Не удалось загрузить инциденты.</ErrorBlock>;const columns=[{key:"opened",label:"Открыт",value:(v:any)=>v.OpenedAt,render:(v:any)=><time>{new Date(v.OpenedAt).toLocaleString("ru-RU")}</time>},{key:"warehouse",label:"Склад",value:(v:any)=>v.WarehouseID,render:(v:any)=><span className="mono">{v.WarehouseID}</span>},{key:"state",label:"Состояние",value:(v:any)=>v.OperationalState,render:(v:any)=><StatusBadge value={v.OperationalState}/>},{key:"status",label:"Обработка",value:(v:any)=>v.Status,render:(v:any)=><StatusBadge value={v.Status}/>},{key:"rerouted",label:"Переназначено",value:(v:any)=>v.ReroutedAllocationCount,align:"end" as const},{key:"attention",label:"Требует внимания",value:(v:any)=>v.ExecutionAttentionCount,render:(v:any)=><strong className={v.ExecutionAttentionCount?"danger-text":""}>{v.ExecutionAttentionCount}</strong>,align:"end" as const}];return <><div className="incident-banner"><Icon name="incident"/><div><strong>Автоматический failover работает только с доказуемыми reservation allocations.</strong><p>TORGNEXA переносит обязательство исполнения, а не физический товар. Неоднозначные резервы остаются для оператора.</p></div></div><DataTable rows={q.data} columns={columns} rowKey={v=>v.ID} searchPlaceholder="Инцидент, склад, состояние…" onOpen={setSelected}/><Drawer open={!!selected} title="Складской инцидент" subtitle={selected?.ID} onClose={()=>setSelected(null)}><>{detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock>Не удалось открыть инцидент.</ErrorBlock>:detail.data?<IncidentDetail value={detail.data}/>:null}</></Drawer></>}
function IncidentDetail({value}:{value:any}){return <><div className="drawer-kpis"><div><small>Переназначено allocations</small><strong>{value.ReroutedAllocationCount}</strong></div><div><small>Без маршрута</small><strong>{value.NoRouteCount}</strong></div><div><small>Требует человека</small><strong>{value.ExecutionAttentionCount}</strong></div></div><section className="drawer-section"><h3>Состояние</h3><dl className="detail-list"><div><dt>Склад</dt><dd className="mono">{value.WarehouseID}</dd></div><div><dt>Operational state</dt><dd><StatusBadge value={value.OperationalState}/></dd></div><div><dt>Причина</dt><dd>{value.ReasonCode||"—"}</dd></div><div><dt>Статус</dt><dd><StatusBadge value={value.Status}/></dd></div><div><dt>Открыт</dt><dd>{new Date(value.OpenedAt).toLocaleString("ru-RU")}</dd></div></dl></section></>}
function Allocations({api}:{api:Client}){const qc=useQueryClient(),toast=useToast();const q=useQuery({queryKey:["fulfillment-allocations"],queryFn:async()=>((await api.listFulfillmentAllocations()).body.items??[]) as any[]});const warehouses=useQuery({queryKey:["inventory-warehouses"],queryFn:async()=>((await api.listInventoryWarehouses()).body.items??[]) as any[]});const [orderItemId,setOrderItemId]=useState(""),[warehouseId,setWarehouseId]=useState(""),[selected,setSelected]=useState<any>(null);const detail=useQuery({queryKey:["fulfillment-allocation",selected?.ID],enabled:!!selected,queryFn:async()=>(await api.getFulfillmentAllocation({allocationId:selected.ID})).body});const reserve=useMutation({mutationFn:()=>api.reserveFulfillmentAllocation({idempotencyKey:crypto.randomUUID(),body:{order_item_id:orderItemId.trim(),warehouse_id:warehouseId.trim()}}),onSuccess:async()=>{toast.push({kind:"success",title:"Резерв создан"});setOrderItemId("");setWarehouseId("");await qc.invalidateQueries({queryKey:["fulfillment-allocations"]})},onError:()=>toast.push({kind:"error",title:"Не удалось создать резерв",body:"Проверьте order item, склад (активен/деградирован) и наличие ATP."})});if(q.isPending)return <LoadingBlock/>;if(q.isError)return <ErrorBlock>Не удалось загрузить fulfillment allocations.</ErrorBlock>;const columns=[{key:"order",label:"Order item",value:(v:any)=>v.OrderItemID,render:(v:any)=><span><strong className="mono">{v.OrderItemID}</strong><small className="table-subline mono">{v.OrderID}</small></span>},{key:"warehouse",label:"Склад",value:(v:any)=>v.WarehouseID,render:(v:any)=><span className="mono">{v.WarehouseID}</span>},{key:"status",label:"Статус",value:(v:any)=>v.Status,render:(v:any)=><StatusBadge value={v.Status}/>},{key:"reason",label:"Причина",value:(v:any)=>v.ReasonCode||"—"},{key:"incident",label:"Инцидент / замена",value:(v:any)=>`${v.IncidentID??""} ${v.ReplacesID??""}`,render:(v:any)=><span><small className="table-subline mono">{v.IncidentID||"—"}</small><small className="table-subline mono">{v.ReplacesID?`заменяет ${v.ReplacesID}`:""}</small></span>}];return <div className="catalog-stack">
 <section className="panel inline-create">
  <div><h2>Ручной резерв</h2><p>Зарезервировать конкретный order item на выбранном складе (в обход автоматического распределения при оформлении заказа).</p></div>
  <form onSubmit={e=>{e.preventDefault();reserve.mutate()}}>
   <input required value={orderItemId} onChange={e=>setOrderItemId(e.target.value)} placeholder="Order item ID"/>
   <select required value={warehouseId} onChange={e=>setWarehouseId(e.target.value)}><option value="">Склад…</option>{(warehouses.data??[]).map((w:any)=><option value={w.ID} key={w.ID}>{w.Name} ({w.Code})</option>)}</select>
   <button className="button primary" disabled={reserve.isPending}>{reserve.isPending?"Резервируем…":"Зарезервировать"}</button>
  </form>
 </section>
 <DataTable rows={q.data} columns={columns} rowKey={v=>v.ID} searchPlaceholder="Order item, склад, incident…" onOpen={setSelected}/>
 <Drawer open={!!selected} title="Fulfillment allocation" subtitle={selected?.ID} onClose={()=>setSelected(null)}><>{detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock>Не удалось открыть allocation.</ErrorBlock>:detail.data?<AllocationDetail value={detail.data}/>:null}</></Drawer>
</div>}
function AllocationDetail({value}:{value:any}){return <dl className="detail-list">
 <div><dt>Order</dt><dd className="mono">{value.OrderID}</dd></div>
 <div><dt>Order item</dt><dd className="mono">{value.OrderItemID}</dd></div>
 <div><dt>Склад</dt><dd className="mono">{value.WarehouseID}</dd></div>
 <div><dt>Количество</dt><dd>{value.Quantity}</dd></div>
 <div><dt>Статус</dt><dd><StatusBadge value={value.Status}/></dd></div>
 <div><dt>Причина</dt><dd>{value.ReasonCode||"—"}</dd></div>
 <div><dt>Инцидент</dt><dd className="mono">{value.IncidentID||"—"}</dd></div>
 <div><dt>Заменяет allocation</dt><dd className="mono">{value.ReplacesID||"—"}</dd></div>
 <div><dt>Версия</dt><dd>{value.Version}</dd></div>
 <div><dt>Создан</dt><dd>{new Date(value.CreatedAt).toLocaleString("ru-RU")}</dd></div>
 <div><dt>Обновлён</dt><dd>{new Date(value.UpdatedAt).toLocaleString("ru-RU")}</dd></div>
</dl>}
function Import({api}:{api:Client}){const qc=useQueryClient(),toast=useToast(),[text,setText]=useState("SKU,WAREHOUSE,QUANTITY,UNIT\nDEMO-SKU,DEMO-WH,25,PCS");const run=useMutation({mutationFn:()=>{const lines=text.trim().split(/\r?\n/).slice(1);const rows=lines.map(line=>{const [sku,warehouse_code,quantity,unit,reason]=line.split(",").map(x=>x.trim());return {sku,warehouse_code,quantity,unit:unit.toUpperCase(),reason:reason||"csv_import"}});return api.importInventory({body:{rows}})},onSuccess:async r=>{toast.push({kind:"success",title:"Импорт завершён",body:`Создано ${r.body.created}, обновлено ${r.body.updated}.`});await qc.invalidateQueries({queryKey:["inventory"]})},onError:()=>toast.push({kind:"error",title:"Импорт остановлен",body:"Проверьте SKU, склад и формат количества."})});return <section className="card import-card"><h2>Импорт остатков из CSV</h2><p>Формат: <span className="mono">SKU,WAREHOUSE,QUANTITY,UNIT,REASON</span>. Перед применением данные валидируются сервером.</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={12}/><div><button className="button primary" disabled={run.isPending} onClick={()=>run.mutate()}>{run.isPending?"Импортируем…":"Импортировать"}</button></div></section>}
