import {useEffect,useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {useAuth} from "../auth/AuthProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {Page} from "./Page";
import {formatJson as pretty} from "../lib/formatters";

type Client={
  getMarketplaceListingTaxonomy(input:{taxonomyId?:string;connectorId?:string;connectorAccountId?:string;categoryCode?:string;locale?:string;jurisdiction?:string}):Promise<{body:unknown}>;
  previewMarketplaceListingBatch(input:{body:unknown}):Promise<{body:unknown}>;
  applyMarketplaceListingBatch(input:{idempotencyKey:string;approvalRequestID:string;body:unknown}):Promise<{body:unknown}>;
  getMarketplaceListingBatch(input:{batchId:string}):Promise<{body:unknown}>;
  readAfterWriteMarketplaceListing(input:{body:unknown}):Promise<{body:unknown}>;
  listMarketplacePublications():Promise<{body:unknown}>;
};
type Taxonomy={fingerprint:string;version:number;source:string;connector_id:string;locale:string;jurisdiction:string;provider_profile?:{schema_version:string;category_code_kind:string;attribute_key_kind:string;bulk_apply_mode:string;read_after_write_mode:string;qualification:string};categories:Array<{code:string;name:string;attribute_codes?:string[]}>;attributes:Array<{code:string;name:string;value_type:string;requirement:string;enum_values?:Array<{code:string;label:string}>}>;media_slots:Array<{code:string;name:string;required:boolean}>};
type Preview={id:string;input_digest:string;affected_count:number;eligible_count:number;blocked_count:number;rows:Array<{sku:string;eligible:boolean;changed:boolean;diagnostics?:Array<{code:string;severity:string;field_path:string;message:string;remediation:string}>}>};
type Batch={id:string;preview_id:string;state:string;input_digest:string;approval_ref?:string;remote_operation_ids?:string[];created_at:string;updated_at:string};
type PublicationOperation={id:string;state:string;remote_id?:string;remote_operation_id?:string;error_code?:string;updated_at?:string};

function asObject<T>(value:unknown):T{return value as T}

export function MarketplaceListingPage(){
  const api=useApi() as unknown as Client;
  const auth=useAuth();
  const toast=useToast();
  const canWrite=auth.session?.capabilities.includes("products.write")??false;
  const [connector,setConnector]=useState("demo"),[locale,setLocale]=useState("ru-RU"),[jurisdiction,setJurisdiction]=useState("RU"),[categoryCode,setCategoryCode]=useState("");
  const [accountID,setAccountID]=useState("demo-account"),[itemsText,setItemsText]=useState(""),[operationsText,setOperationsText]=useState('[{"kind":"set","field":"content.title","value":"Обновлённое название"}]');
  const [approvalID,setApprovalID]=useState(""),[remotePlanText,setRemotePlanText]=useState(""),[preview,setPreview]=useState<Preview>(),[batch,setBatch]=useState<Batch>(),[readText,setReadText]=useState(""),[readResult,setReadResult]=useState<unknown>();
  const taxonomy=useQuery({queryKey:["marketplace-listing-taxonomy",connector,accountID,categoryCode,locale,jurisdiction],queryFn:async()=>asObject<Taxonomy>((await api.getMarketplaceListingTaxonomy({connectorId:connector,connectorAccountId:connector==="demo"?undefined:accountID,categoryCode:categoryCode.trim()||undefined,locale,jurisdiction})).body)});
  const publicationOperations=useQuery({queryKey:["marketplace-listing-publications",batch?.remote_operation_ids],enabled:Boolean(batch?.remote_operation_ids?.length),queryFn:async()=>{const body=asObject<{items?:PublicationOperation[]}>((await api.listMarketplacePublications()).body);const ids=new Set(batch?.remote_operation_ids??[]);return (body.items??[]).filter(item=>ids.has(item.id))},refetchInterval:15000});
  useEffect(()=>{if(taxonomy.data&&!itemsText.trim()){setItemsText(pretty({connector_account_id:accountID,connector_id:connector,taxonomy_fingerprint:taxonomy.data.fingerprint,note:"Вставьте сюда items из карточек каталога с идентификаторами текущей организации и рабочего пространства."}))}},[accountID,connector,itemsText,taxonomy.data]);
  const previewMutation=useMutation({mutationFn:()=>{const items=JSON.parse(itemsText) as unknown;const operations=JSON.parse(operationsText) as unknown;const body={connector_account_id:accountID.trim(),connector_id:connector.trim(),taxonomy:taxonomy.data,items:Array.isArray(items)?items:[],operations:Array.isArray(operations)?operations:[]};return api.previewMarketplaceListingBatch({body})},onSuccess:response=>{setPreview(asObject<Preview>(response.body));toast.push({kind:"success",title:"Проверка batch завершена",body:"Результат сохранён в текущем рабочем сеансе."})},onError:()=>toast.push({kind:"error",title:"Batch не прошёл проверку",body:"Проверьте JSON карточек, taxonomy и соответствие текущему workspace."})});
  const applyMutation=useMutation({mutationFn:()=>{const publications=remotePlanText.trim()?JSON.parse(remotePlanText) as unknown:[];return api.applyMarketplaceListingBatch({idempotencyKey:crypto.randomUUID(),approvalRequestID:approvalID.trim(),body:{preview,publications:Array.isArray(publications)?publications:[]}})},onSuccess:response=>{setBatch(asObject<Batch>(response.body));toast.push({kind:"success",title:"Batch поставлен в очередь",body:"Каждая строка сохранена в общей очереди публикаций и получит отдельный receipt."})},onError:()=>toast.push({kind:"error",title:"Batch не поставлен в очередь",body:"Нужен одобренный запрос, quality receipt и remote plan для выбранных строк."})});
  const readMutation=useMutation({mutationFn:()=>api.readAfterWriteMarketplaceListing({body:JSON.parse(readText) as unknown}),onSuccess:response=>{setReadResult(response.body);toast.push({kind:"success",title:"Read-after-write выполнен"})},onError:()=>toast.push({kind:"error",title:"Не удалось сверить карточку",body:"Проверьте expected draft, digest и нормализованное observation."})});
  const rows=preview?.rows??[];
  return <Page eyebrow="Каталог и каналы" title="Рабочее место карточки marketplace" description="Taxonomy, массовая проверка до 1 000 SKU и read-after-write в одном контуре. Живые записи доступны только после approval и подтверждённой квалификации коннектора.">
    <section className="hero-grid"><article className="metric-card primary-metric"><span>Версия схемы</span><strong>{taxonomy.data?.version??"—"}</strong><small>{taxonomy.data?.source??"загрузка taxonomy"}</small></article><article className="metric-card"><span>Атрибутов</span><strong>{taxonomy.data?.attributes.length??0}</strong><small>{taxonomy.data?.locale??locale}</small></article><article className="metric-card"><span>Затронуто SKU</span><strong>{preview?.affected_count??0}</strong><small>{preview?`${preview.eligible_count} готовы · ${preview.blocked_count} заблокированы` : "после проверки batch"}</small></article></section>
    {taxonomy.isPending?<LoadingBlock/>:taxonomy.isError?<ErrorBlock retry={()=>void taxonomy.refetch()}>Не удалось загрузить taxonomy канала.</ErrorBlock>:<section className="panel"><div className="drawer-section-heading"><div><p className="eyebrow">Схема канала</p><h2>{taxonomy.data.connector_id} · {taxonomy.data.locale}</h2><p>Синтетическая demo-схема помогает проверить UX. Для WB можно загрузить актуальные категории и характеристики из подключённого кабинета.</p></div><button type="button" className="button ghost" onClick={()=>void taxonomy.refetch()}>Обновить схему</button></div><div className="form-grid"><label className="field"><span>Connector</span><input value={connector} onChange={event=>setConnector(event.target.value)} maxLength={192}/></label><label className="field"><span>Account ID</span><input value={accountID} onChange={event=>setAccountID(event.target.value)} maxLength={192}/></label><label className="field"><span>Код категории (для WB)</span><input value={categoryCode} onChange={event=>setCategoryCode(event.target.value)} inputMode="numeric" maxLength={128} placeholder="например, 105"/></label><label className="field"><span>Локаль</span><input value={locale} onChange={event=>setLocale(event.target.value)} maxLength={16}/></label><label className="field"><span>Юрисдикция</span><input value={jurisdiction} onChange={event=>setJurisdiction(event.target.value)} maxLength={2}/></label></div><div className="chip-list">{taxonomy.data.provider_profile?<><span className="chip">Профиль {taxonomy.data.provider_profile.schema_version}</span><span className="chip">Квалификация: {taxonomy.data.provider_profile.qualification}</span><span className="chip">Apply: {taxonomy.data.provider_profile.bulk_apply_mode}</span><span className="chip">Read-after-write: {taxonomy.data.provider_profile.read_after_write_mode}</span></>:null}{taxonomy.data.categories.map(category=><span className="chip" key={category.code}>{category.name} · {category.code}</span>)}{taxonomy.data.attributes.map(attribute=><span className="chip" key={attribute.code}>{attribute.name} · {attribute.requirement}</span>)}</div></section>}
    <section className="panel inline-create"><div><p className="eyebrow">Batch preview</p><h2>Массовое редактирование</h2><p>Передайте JSON-массив items из каталога. Сервер проверит conditional attributes, enum, media release, локализацию и fingerprint taxonomy. В demo-подсказке нет реальных tenant IDs — вставьте карточки текущего workspace.</p></div><form onSubmit={event=>{event.preventDefault();if(!previewMutation.isPending)previewMutation.mutate()}}><label className="field"><span>Account ID</span><input required value={accountID} onChange={event=>setAccountID(event.target.value)} maxLength={192}/></label><label className="field"><span>Items JSON</span><textarea required rows={10} value={itemsText} onChange={event=>setItemsText(event.target.value)} spellCheck={false}/></label><label className="field"><span>Операции JSON</span><textarea required rows={4} value={operationsText} onChange={event=>setOperationsText(event.target.value)} spellCheck={false}/></label><div className="page-actions"><button className="button primary" disabled={previewMutation.isPending||taxonomy.isPending}>{previewMutation.isPending?"Проверяем…":"Проверить batch"}</button>{preview?.eligible_count&&canWrite?<><input className="field-inline-input" value={approvalID} onChange={event=>setApprovalID(event.target.value)} placeholder="Approval request ID" aria-label="Approval request ID"/><button type="button" className="button secondary" disabled={!approvalID.trim()||applyMutation.isPending} onClick={()=>applyMutation.mutate()}>{applyMutation.isPending?"Ставим…":"Подготовить применение"}</button></>:null}</div>{preview?.eligible_count&&canWrite?<label className="field"><span>Remote plan JSON (snapshot + quality receipt на строку)</span><textarea rows={6} value={remotePlanText} onChange={event=>setRemotePlanText(event.target.value)} placeholder={'[{"sku":"SKU-1","operation":"update_product","remote_id":"remote-1","quality_receipt_id":"receipt-1","snapshot":{...}}]'} spellCheck={false}/><small className="table-subline">Для create не передавайте remote ID. Для update/lifecycle нужен remote_id, для status_read — remote_id или remote_operation_id. Пустой план сохраняет batch-evidence без remote write.</small></label>:null}</form></section>
    {preview?<section className="panel"><div className="drawer-section-heading"><div><p className="eyebrow">Результат preview</p><h2 className="mono">{preview.id}</h2></div><StatusBadge value={preview.blocked_count?"needs_attention":"ready"}/></div><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Изменён</th><th>Решение</th><th>Диагностика</th></tr></thead><tbody>{rows.map(row=><tr key={row.sku}><td className="mono">{row.sku}</td><td>{row.changed?"Да":"Нет"}</td><td><StatusBadge value={row.eligible?"ready":"blocked"}/></td><td>{row.diagnostics?.length?<div className="timeline">{row.diagnostics.map((issue,index)=><span key={`${issue.code}-${index}`}><strong>{issue.field_path}</strong> · {issue.message}<small className="table-subline">{issue.remediation}</small></span>)}</div>:"—"}</td></tr>)}</tbody></table></div></section>:null}
    {batch?<section className="panel report-result"><p className="eyebrow">Очередь применения</p><h2>Batch сохранён как evidence</h2><dl className="detail-list"><div><dt>Batch ID</dt><dd className="mono">{batch.id}</dd></div><div><dt>Состояние</dt><dd><StatusBadge value={batch.state}/></dd></div><div><dt>Approval</dt><dd className="mono">{batch.approval_ref}</dd></div><div><dt>Preview</dt><dd className="mono">{batch.preview_id}</dd></div><div><dt>Remote operations</dt><dd>{batch.remote_operation_ids?.length??0} строк в общей очереди</dd></div></dl>{batch.remote_operation_ids?.length?<div className="table-wrap"><table><thead><tr><th>Operation ID</th><th>Состояние</th><th>Remote ID</th><th>Remote operation ID</th><th>Ошибка</th></tr></thead><tbody>{publicationOperations.data?.map(operation=><tr key={operation.id}><td className="mono">{operation.id}</td><td><StatusBadge value={operation.state}/></td><td className="mono">{operation.remote_id??"—"}</td><td className="mono">{operation.remote_operation_id??"—"}</td><td>{operation.error_code??"—"}</td></tr>)}</tbody></table></div>:null}</section>:null}
    <section className="panel inline-create"><div><p className="eyebrow">Reconciliation</p><h2>Read-after-write</h2><p>Вставьте expected draft и нормализованное observation коннектора. Для асинхронного канала допустим remote_operation_id вместо remote_id. Raw response сюда не попадает.</p></div><form onSubmit={event=>{event.preventDefault();if(!readMutation.isPending)readMutation.mutate()}}><label className="field"><span>JSON</span><textarea required rows={8} value={readText} onChange={event=>setReadText(event.target.value)} placeholder={'{"expected": {…}, "expected_digest": "…", "observation": {"remote_operation_id":"…","snapshot_digest":"…","status":"processing","observed_at":"…"}}'} spellCheck={false}/></label><button className="button secondary" disabled={readMutation.isPending}>{readMutation.isPending?"Сверяем…":"Сверить состояние"}</button></form>{readResult?<pre className="code-block">{pretty(readResult)}</pre>:null}</section>
  </Page>;
}
