import {useMemo} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {Page} from "./Page";
import {navigate,useLocationPath} from "../shell/useLocationPath";

interface Operation {key:string;label:string;state:string;required_capabilities:string[];available_capabilities:string[];permission:string;risk:string;approval_required:boolean;reason_code:string}
interface AccountMatrix {account_id:string;connector_id:string;display_name:string;account_status:string;health_status:string;overall_state:string;partial:boolean;operations:Operation[]}
interface MatrixResponse {items:AccountMatrix[];partial:boolean;generated_at:string;next_cursor?:string}
interface FlowReference {kind:string;id:string}
interface MarketplaceFlow {id:string;account_id:string;stage:string;state:string;version:number;last_reason_code?:string;references?:FlowReference[];created_at:string;updated_at:string}
interface FlowResponse {items:MarketplaceFlow[];next_cursor?:string}
interface FlowCommand {flow_id:string;operation_id:string;idempotency_key:string;stage:string;outcome:string;reason_code?:string;references?:FlowReference[];occurred_at:string}
interface FlowDetailResponse {flow:MarketplaceFlow;timeline:FlowCommand[]}
interface MarketplaceFinding {id:string;flow_id:string;account_id:string;stage:string;kind:string;entity_kind:string;entity_id:string;severity:string;status:string;reason_code:string;expected?:string;observed?:string;detected_at:string}
interface FindingResponse {items:MarketplaceFinding[];next_cursor?:string}

const reasonLabels:Record<string,string>={capability_not_enabled:"Операция не включена",write_capability_not_enabled:"Запись не включена",capability_set_incomplete:"Набор прав неполный",qualification_evidence_required:"Нужны qualification evidence",requires_separate_government_and_edo_accounts:"Нужны отдельные кабинеты Честного знака и ЭДО",account_or_credentials_blocked:"Кабинет или доступ заблокирован",qualification_evidence_current:"Есть актуальное evidence"};
const flowStages:Record<string,string>={account:"Подключение кабинета",product:"Товар",publication:"Публикация",pricing:"Цена",inventory:"Остаток",order:"Заказ",reservation:"Резерв",pick_pack:"Сборка",label:"Этикетка",shipment:"Отгрузка",return:"Возврат",settlement:"Settlement",profitability:"P&L",reconciliation:"Сверка",complete:"Завершён"};
const workspaceSurfaces=[
 {label:"Кабинеты",hint:"подключение и доступы",path:"/integrations"},
 {label:"Каталог",hint:"товары и SKU",path:"/catalog"},
 {label:"Заказы",hint:"заказы marketplace",path:"/orders"},
 {label:"Склад и сборка",hint:"остатки и задания",path:"/inventory"},
 {label:"Возвраты",hint:"отмены и возвраты",path:"/returns"},
 {label:"Settlement и P&L",hint:"деньги и экономика",path:"/finance/analytics"},
 {label:"Реклама",hint:"расходы и кампании",path:"/advertising"},
 {label:"Синхронизация",hint:"ошибки и сверка",path:"/sync"},
];

function state(value:string){return <StatusBadge value={value}/>}

export function MarketplaceOperationsPage(){
 const api=useApi() as any;const cache=useQueryClient();const toast=useToast();const path=useLocationPath();const flowID=path.startsWith("/marketplace-operations/flows/")?decodeURIComponent(path.slice("/marketplace-operations/flows/".length)):undefined;const selectedID=!flowID&&path.startsWith("/marketplace-operations/")?decodeURIComponent(path.slice("/marketplace-operations/".length)):undefined;
 const query=useQuery({queryKey:["marketplace-operations",selectedID??"list"],queryFn:async()=>{const response=selectedID?await api.getMarketplaceOperations({accountId:selectedID}):await api.listMarketplaceOperations({limit:100});return response.body as MatrixResponse|AccountMatrix},staleTime:10_000});
 const flows=useQuery({queryKey:["marketplace-operation-flows"],queryFn:async()=>{const response=await api.listMarketplaceOperationFlows({limit:50});return response.body as FlowResponse},staleTime:10_000});
 const findings=useQuery({queryKey:["marketplace-operation-findings"],queryFn:async()=>{const response=await api.listMarketplaceOperationFindings({limit:50,status:"open"});return response.body as FindingResponse},staleTime:10_000});
 const flowDetail=useQuery({queryKey:["marketplace-operation-flow",flowID],enabled:!!flowID,queryFn:async()=>{const response=await api.getMarketplaceOperationFlow({flowId:flowID});return response.body as FlowDetailResponse},staleTime:5_000});
 const startFlow=useMutation({mutationFn:(accountID:string)=>api.createMarketplaceOperationFlow({idempotencyKey:crypto.randomUUID(),body:{account_id:accountID}}),onSuccess:async()=>{toast.push({kind:"success",title:"Workflow создан",body:"Следующий шаг будет зафиксирован после проверки кабинета и доступных операций."});await cache.invalidateQueries({queryKey:["marketplace-operation-flows"]})},onError:()=>toast.push({kind:"error",title:"Workflow не создан",body:"Проверьте доступ к кабинету и попробуйте ещё раз."})});
 const findingAction=useMutation({mutationFn:(input:{id:string;action:"retry"|"reconcile"|"resolve"})=>api.applyMarketplaceOperationFindingAction({findingId:input.id,idempotencyKey:crypto.randomUUID(),body:{action:input.action}}),onSuccess:async()=>{toast.push({kind:"success",title:"Действие зафиксировано",body:"Worker обработает durable intent после повторной проверки прав и capability."});await cache.invalidateQueries({queryKey:["marketplace-operation-findings"]})},onError:()=>toast.push({kind:"error",title:"Действие не принято",body:"Finding уже изменён или требует проверки доступа."})});
 if(flowID){const detail=flowDetail.data?.flow;return <Page eyebrow="Marketplace / Workflow" title="Детали обработки заказа" description="Единая timeline от заказа и резерва до возврата денег и сверки."><button type="button" className="button ghost" onClick={()=>navigate("/marketplace-operations")}>← Все workflows</button>{flowDetail.isPending?<LoadingBlock/>:flowDetail.isError||!detail?<ErrorBlock retry={()=>void flowDetail.refetch()}>Не удалось загрузить timeline workflow.</ErrorBlock>:<><section className="hero-grid"><article className="metric-card primary-metric"><span>Текущая стадия</span><strong>{flowStages[detail.stage]??detail.stage}</strong><small><StatusBadge value={detail.state}/></small></article><article className="metric-card"><span>Версия</span><strong>{detail.version}</strong><small className="mono">{detail.id}</small></article><article className="metric-card"><span>Связанные записи</span><strong>{detail.references?.length??0}</strong><small>канонические ссылки</small></article></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Durable timeline</p><h2>История этапов</h2><p>Идемпотентность и результаты внешних вызовов видны как метаданные; raw payloads и секреты не сохраняются.</p></div></div>{detail.timeline.length===0?<EmptyState title="Команд ещё нет" text="Workflow создан и ожидает первой команды владельца текущей стадии."/>:<div className="timeline">{detail.timeline.map(item=><article key={item.operation_id}><span className="timeline-dot"/><div><strong>{flowStages[item.stage]??item.stage} · <StatusBadge value={item.outcome}/></strong><small className="mono">{item.operation_id}{item.reason_code?` · ${item.reason_code}`:""}</small><time>{new Date(item.occurred_at).toLocaleString("ru-RU")}</time></div></article>)}</div>}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Lineage</p><h2>Канонические записи</h2></div></div><div className="tag-list">{(detail.references??[]).map(reference=><span className="tag" key={`${reference.kind}:${reference.id}`}><strong>{reference.kind}</strong><span className="mono">{reference.id}</span></span>)}</div></section></>}</Page>}
 const items=useMemo(()=>selectedID?(query.data&&!Array.isArray(query.data)&&"account_id" in query.data?[query.data as AccountMatrix]:[]):((query.data as MatrixResponse|undefined)?.items??[]),[query.data,selectedID]);
 const allOperations=items.flatMap(item=>item.operations);const qualified=allOperations.filter(item=>item.state==="qualified").length;const attention=allOperations.filter(item=>item.state==="partially_supported"||item.state==="blocked").length;
 return <Page eyebrow="Marketplace" title="Операции marketplace" description="Фактическая матрица кабинетов: что доступно сейчас, что требует квалификации и какие записи заблокированы.">
  {query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить матрицу операций marketplace.</ErrorBlock>:items.length===0?<EmptyState title="Marketplace-кабинеты не подключены" text="Сначала создайте и проверьте кабинет в разделе «Интеграции»."/>:<>
   <section className="hero-grid"><article className="metric-card primary-metric"><span>Кабинеты</span><strong>{items.length}</strong><small>в текущем workspace</small></article><article className="metric-card"><span>Квалифицировано</span><strong>{qualified}</strong><small>операций с evidence</small></article><article className="metric-card"><span>Требует внимания</span><strong>{attention}</strong><small>частичные или заблокированные</small></article></section>
   {query.data&&!Array.isArray(query.data)&&"partial" in query.data&&query.data.partial?<div className="panel alert warning" role="status">Снимок собран с неполными источниками. Зелёный статус не выводится без актуального evidence.</div>:null}
   <section className="panel marketplace-surfaces"><div className="section-heading"><div><p className="eyebrow">Единое рабочее место</p><h2>Перейти к операции</h2><p>Разделы используют те же tenant-scoped домены. Доступные записи по кабинету проверяются в этой матрице.</p></div></div><div className="module-grid">{workspaceSurfaces.map(surface=><button type="button" className="module-card" key={surface.path} onClick={()=>navigate(surface.path)}><span className="module-glyph">{surface.label.slice(0,1)}</span><span><strong>{surface.label}</strong><small>{surface.hint}</small></span><span className="arrow">→</span></button>)}</div></section>
    {flows.isError?<div className="panel alert warning" role="status">Не удалось загрузить историю workflow. Матрица кабинетов доступна, но текущие зависшие операции нужно проверить в «Синхронизации».</div>:flows.data?.items?.length?<section className="panel marketplace-flows"><div className="section-heading"><div><p className="eyebrow">Фактическое выполнение</p><h2>Workflow marketplace</h2><p>Сохранённые стадии и unknown-состояния. Повтор команды защищён идемпотентным журналом.</p></div></div><div className="table-wrap"><table><thead><tr><th>Кабинет</th><th>Стадия</th><th>Состояние</th><th>Последняя причина</th><th>Обновлено</th></tr></thead><tbody>{flows.data.items.map(flow=><tr key={flow.id}><td><span className="mono">{flow.account_id}</span><small className="table-subline mono">{flow.id}</small></td><td><button type="button" className="button link-button" onClick={()=>navigate(`/marketplace-operations/flows/${encodeURIComponent(flow.id)}`)}>{flowStages[flow.stage]??flow.stage}</button></td><td><StatusBadge value={flow.state}/></td><td>{flow.last_reason_code||"—"}</td><td>{new Date(flow.updated_at).toLocaleString("ru-RU")}</td></tr>)}</tbody></table></div></section>:null}
    {findings.isError?<div className="panel alert warning" role="status">Не удалось загрузить findings. Проверьте раздел «Синхронизация».</div>:findings.data?.items?.length?<section className="panel marketplace-findings"><div className="section-heading"><div><p className="eyebrow">Reconciliation</p><h2>Требуют внимания</h2><p>Finding неизменяем; retry, reconcile и resolve фиксируются отдельным журналом.</p></div></div><div className="table-wrap"><table><thead><tr><th>Причина</th><th>Сущность</th><th>Серьёзность</th><th>Ожидалось / получено</th><th>Действие</th></tr></thead><tbody>{findings.data.items.map(finding=><tr key={finding.id}><td><strong>{finding.reason_code}</strong><small className="table-subline mono">{finding.kind}</small></td><td>{finding.entity_kind}<small className="table-subline mono">{finding.entity_id}</small></td><td><StatusBadge value={finding.severity}/></td><td className="mono">{finding.expected||"—"} / {finding.observed||"—"}</td><td><div className="button-row"><button type="button" className="button ghost" disabled={findingAction.isPending} onClick={()=>findingAction.mutate({id:finding.id,action:"reconcile"})}>Сверить</button><button type="button" className="button ghost" disabled={findingAction.isPending} onClick={()=>findingAction.mutate({id:finding.id,action:"retry"})}>Повторить</button><button type="button" className="button ghost" disabled={findingAction.isPending} onClick={()=>findingAction.mutate({id:finding.id,action:"resolve"})}>Закрыть</button></div></td></tr>)}</tbody></table></div></section>:null}
    {items.map(item=><section className="panel" key={item.account_id}><div className="section-heading"><div><p className="eyebrow">{item.connector_id}</p><h2>{item.display_name||item.connector_id}</h2><p>{item.account_id} · подключение: {item.health_status}</p></div><div className="button-row"><span>{state(item.overall_state)}</span>{!selectedID?<><button type="button" className="button ghost" onClick={()=>navigate(`/marketplace-operations/${encodeURIComponent(item.account_id)}`)}>Открыть кабинет</button><button type="button" className="button primary" disabled={startFlow.isPending} onClick={()=>startFlow.mutate(item.account_id)}>{startFlow.isPending?"Создаём…":"Начать workflow"}</button></>:<button type="button" className="button ghost" onClick={()=>navigate("/marketplace-operations")}>Все кабинеты</button>}</div></div><div className="table-wrap"><table><thead><tr><th>Операция</th><th>Состояние</th><th>Риск и согласование</th><th>Доступные права</th><th>Следующий шаг</th></tr></thead><tbody>{item.operations.map(operation=><tr key={operation.key}><td><strong>{operation.label}</strong><small className="table-subline mono">{operation.key}</small></td><td>{state(operation.state)}</td><td>{operation.risk}{operation.approval_required?<small className="table-subline">нужно согласование</small>:null}</td><td className="mono">{operation.available_capabilities.length?operation.available_capabilities.join(", "):"—"}</td><td>{reasonLabels[operation.reason_code]??operation.reason_code}</td></tr>)}</tbody></table></div></section>)}
  </>}
  <p className="settings-note">`qualified` означает, что отдельно сохранено актуальное qualification evidence. Наличие токена, manifest или health-check само по себе не открывает запись во внешний marketplace.</p>
 </Page>;
}
