import {useEffect,useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {useAuth} from "../auth/AuthProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {Page} from "./Page";

type Client={
  getMarketplaceListingTaxonomy(input:{taxonomyId?:string;connectorId?:string;locale?:string;jurisdiction?:string}):Promise<{body:unknown}>;
  previewMarketplaceListingBatch(input:{body:unknown}):Promise<{body:unknown}>;
  applyMarketplaceListingBatch(input:{idempotencyKey:string;approvalRequestID:string;body:unknown}):Promise<{body:unknown}>;
  getMarketplaceListingBatch(input:{batchId:string}):Promise<{body:unknown}>;
  readAfterWriteMarketplaceListing(input:{body:unknown}):Promise<{body:unknown}>;
};
type Taxonomy={fingerprint:string;version:number;source:string;connector_id:string;locale:string;jurisdiction:string;categories:Array<{code:string;name:string;attribute_codes?:string[]}>;attributes:Array<{code:string;name:string;value_type:string;requirement:string;enum_values?:Array<{code:string;label:string}>}>;media_slots:Array<{code:string;name:string;required:boolean}>};
type Preview={id:string;input_digest:string;affected_count:number;eligible_count:number;blocked_count:number;rows:Array<{sku:string;eligible:boolean;changed:boolean;diagnostics?:Array<{code:string;severity:string;field_path:string;message:string;remediation:string}>}>};
type Batch={id:string;preview_id:string;state:string;input_digest:string;approval_ref?:string;created_at:string;updated_at:string};

function asObject<T>(value:unknown):T{return value as T}
function pretty(value:unknown){return JSON.stringify(value,null,2)}

export function MarketplaceListingPage(){
  const api=useApi() as unknown as Client;
  const auth=useAuth();
  const toast=useToast();
  const canWrite=auth.session?.capabilities.includes("products.write")??false;
  const [connector,setConnector]=useState("demo"),[locale,setLocale]=useState("ru-RU"),[jurisdiction,setJurisdiction]=useState("RU");
  const [accountID,setAccountID]=useState("demo-account"),[itemsText,setItemsText]=useState(""),[operationsText,setOperationsText]=useState('[{"kind":"set","field":"content.title","value":"Обновлённое название"}]');
  const [approvalID,setApprovalID]=useState(""),[preview,setPreview]=useState<Preview>(),[batch,setBatch]=useState<Batch>(),[readText,setReadText]=useState(""),[readResult,setReadResult]=useState<unknown>();
  const taxonomy=useQuery({queryKey:["marketplace-listing-taxonomy",connector,locale,jurisdiction],queryFn:async()=>asObject<Taxonomy>((await api.getMarketplaceListingTaxonomy({connectorId:connector,locale,jurisdiction})).body)});
  useEffect(()=>{if(taxonomy.data&&!itemsText.trim()){setItemsText(pretty({connector_account_id:accountID,connector_id:connector,taxonomy_fingerprint:taxonomy.data.fingerprint,note:"Вставьте сюда items из карточек каталога с идентификаторами текущей организации и рабочего пространства."}))}},[accountID,connector,itemsText,taxonomy.data]);
  const previewMutation=useMutation({mutationFn:()=>{const items=JSON.parse(itemsText) as unknown;const operations=JSON.parse(operationsText) as unknown;const body={connector_account_id:accountID.trim(),connector_id:connector.trim(),taxonomy:taxonomy.data,items:Array.isArray(items)?items:[],operations:Array.isArray(operations)?operations:[]};return api.previewMarketplaceListingBatch({body})},onSuccess:response=>{setPreview(asObject<Preview>(response.body));toast.push({kind:"success",title:"Проверка batch завершена",body:"Результат сохранён в текущем рабочем сеансе."})},onError:()=>toast.push({kind:"error",title:"Batch не прошёл проверку",body:"Проверьте JSON карточек, taxonomy и соответствие текущему workspace."})});
  const applyMutation=useMutation({mutationFn:()=>api.applyMarketplaceListingBatch({idempotencyKey:crypto.randomUUID(),approvalRequestID:approvalID.trim(),body:{preview}}),onSuccess:response=>{setBatch(asObject<Batch>(response.body));toast.push({kind:"success",title:"Batch поставлен в очередь",body:"Запись в marketplace остаётся approval- и qualification-gated."})},onError:()=>toast.push({kind:"error",title:"Batch не поставлен в очередь",body:"Нужен одобренный запрос и хотя бы одна готовая строка."})});
  const readMutation=useMutation({mutationFn:()=>api.readAfterWriteMarketplaceListing({body:JSON.parse(readText) as unknown}),onSuccess:response=>{setReadResult(response.body);toast.push({kind:"success",title:"Read-after-write выполнен"})},onError:()=>toast.push({kind:"error",title:"Не удалось сверить карточку",body:"Проверьте expected draft, digest и нормализованное observation."})});
  const rows=preview?.rows??[];
  return <Page eyebrow="Каталог и каналы" title="Рабочее место карточки marketplace" description="Taxonomy, массовая проверка до 1 000 SKU и read-after-write в одном контуре. Живые записи доступны только после approval и подтверждённой квалификации коннектора.">
    <section className="hero-grid"><article className="metric-card primary-metric"><span>Версия схемы</span><strong>{taxonomy.data?.version??"—"}</strong><small>{taxonomy.data?.source??"загрузка taxonomy"}</small></article><article className="metric-card"><span>Атрибутов</span><strong>{taxonomy.data?.attributes.length??0}</strong><small>{taxonomy.data?.locale??locale}</small></article><article className="metric-card"><span>Затронуто SKU</span><strong>{preview?.affected_count??0}</strong><small>{preview?`${preview.eligible_count} готовы · ${preview.blocked_count} заблокированы` : "после проверки batch"}</small></article></section>
    {taxonomy.isPending?<LoadingBlock/>:taxonomy.isError?<ErrorBlock retry={()=>void taxonomy.refetch()}>Не удалось загрузить taxonomy канала.</ErrorBlock>:<section className="panel"><div className="drawer-section-heading"><div><p className="eyebrow">Схема канала</p><h2>{taxonomy.data.connector_id} · {taxonomy.data.locale}</h2><p>Синтетическая demo-схема помогает проверить UX. Она не является подтверждением поддержки WB/Ozon/Yandex Market.</p></div><button type="button" className="button ghost" onClick={()=>void taxonomy.refetch()}>Обновить схему</button></div><div className="form-grid"><label className="field"><span>Connector</span><input value={connector} onChange={event=>setConnector(event.target.value)} maxLength={192}/></label><label className="field"><span>Локаль</span><input value={locale} onChange={event=>setLocale(event.target.value)} maxLength={16}/></label><label className="field"><span>Юрисдикция</span><input value={jurisdiction} onChange={event=>setJurisdiction(event.target.value)} maxLength={2}/></label></div><div className="chip-list">{taxonomy.data.categories.map(category=><span className="chip" key={category.code}>{category.name} · {category.code}</span>)}{taxonomy.data.attributes.map(attribute=><span className="chip" key={attribute.code}>{attribute.name} · {attribute.requirement}</span>)}</div></section>}
    <section className="panel inline-create"><div><p className="eyebrow">Batch preview</p><h2>Массовое редактирование</h2><p>Передайте JSON-массив items из каталога. Сервер проверит conditional attributes, enum, media release, локализацию и fingerprint taxonomy. В demo-подсказке нет реальных tenant IDs — вставьте карточки текущего workspace.</p></div><form onSubmit={event=>{event.preventDefault();if(!previewMutation.isPending)previewMutation.mutate()}}><label className="field"><span>Account ID</span><input required value={accountID} onChange={event=>setAccountID(event.target.value)} maxLength={192}/></label><label className="field"><span>Items JSON</span><textarea required rows={10} value={itemsText} onChange={event=>setItemsText(event.target.value)} spellCheck={false}/></label><label className="field"><span>Операции JSON</span><textarea required rows={4} value={operationsText} onChange={event=>setOperationsText(event.target.value)} spellCheck={false}/></label><div className="page-actions"><button className="button primary" disabled={previewMutation.isPending||taxonomy.isPending}>{previewMutation.isPending?"Проверяем…":"Проверить batch"}</button>{preview?.eligible_count&&canWrite?<><input className="field-inline-input" value={approvalID} onChange={event=>setApprovalID(event.target.value)} placeholder="Approval request ID" aria-label="Approval request ID"/><button type="button" className="button secondary" disabled={!approvalID.trim()||applyMutation.isPending} onClick={()=>applyMutation.mutate()}>{applyMutation.isPending?"Ставим…":"Подготовить применение"}</button></>:null}</div></form></section>
    {preview?<section className="panel"><div className="drawer-section-heading"><div><p className="eyebrow">Результат preview</p><h2 className="mono">{preview.id}</h2></div><StatusBadge value={preview.blocked_count?"needs_attention":"ready"}/></div><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Изменён</th><th>Решение</th><th>Диагностика</th></tr></thead><tbody>{rows.map(row=><tr key={row.sku}><td className="mono">{row.sku}</td><td>{row.changed?"Да":"Нет"}</td><td><StatusBadge value={row.eligible?"ready":"blocked"}/></td><td>{row.diagnostics?.length?<div className="timeline">{row.diagnostics.map((issue,index)=><span key={`${issue.code}-${index}`}><strong>{issue.field_path}</strong> · {issue.message}<small className="table-subline">{issue.remediation}</small></span>)}</div>:"—"}</td></tr>)}</tbody></table></div></section>:null}
    {batch?<section className="panel report-result"><p className="eyebrow">Очередь применения</p><h2>Batch сохранён как evidence</h2><dl className="detail-list"><div><dt>Batch ID</dt><dd className="mono">{batch.id}</dd></div><div><dt>Состояние</dt><dd><StatusBadge value={batch.state}/></dd></div><div><dt>Approval</dt><dd className="mono">{batch.approval_ref}</dd></div><div><dt>Preview</dt><dd className="mono">{batch.preview_id}</dd></div></dl></section>:null}
    <section className="panel inline-create"><div><p className="eyebrow">Reconciliation</p><h2>Read-after-write</h2><p>Вставьте expected draft и нормализованное observation коннектора. Raw response сюда не попадает.</p></div><form onSubmit={event=>{event.preventDefault();if(!readMutation.isPending)readMutation.mutate()}}><label className="field"><span>JSON</span><textarea required rows={8} value={readText} onChange={event=>setReadText(event.target.value)} placeholder={'{"expected": {…}, "expected_digest": "…", "observation": {"remote_id":"…","snapshot_digest":"…","status":"published","observed_at":"…"}}'} spellCheck={false}/></label><button className="button secondary" disabled={readMutation.isPending}>{readMutation.isPending?"Сверяем…":"Сверить состояние"}</button></form>{readResult?<pre className="code-block">{pretty(readResult)}</pre>:null}</section>
  </Page>;
}
