import {useEffect,useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {useAuth} from "../auth/AuthProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {Page} from "./Page";

type Client={
  listCatalogBulkChannels():Promise<{body:unknown}>;
  listCatalogBulkRuns(input:{cursor?:string;limit?:number}):Promise<{body:unknown}>;
  getCatalogBulkKillSwitch():Promise<{body:unknown}>;
  setCatalogBulkKillSwitch(input:{body:unknown}):Promise<{body:unknown}>;
  previewCatalogBulk(input:{body:unknown}):Promise<{body:unknown}>;
  applyCatalogBulk(input:{idempotencyKey:string;approvalRequestID:string;body:unknown}):Promise<{body:unknown}>;
  getCatalogBulkPreview(input:{previewId:string}):Promise<{body:unknown}>;
  getCatalogBulkRun(input:{runId:string}):Promise<{body:unknown}>;
  reconcileCatalogBulkRun(input:{runId:string;body:unknown}):Promise<{body:unknown}>;
};
type Channel={channel_id:string;label:string;state:string;capabilities?:string[];observed_at:string;fresh_until:string};
type Row={id:string;sku:string;channel_id:string;account_id:string;capability_state:string;changed_fields?:string[];eligible:boolean;state:string;diagnostics?:Array<{code:string;field_path:string;message:string;remediation:string}>};
type Preview={id:string;input_digest:string;affected_sku_count:number;affected_row_count:number;eligible_row_count:number;blocked_row_count:number;state:string;rows:Row[];created_at:string};
type Run={id:string;preview_id:string;state:string;partitions:string[];results:Array<{row_id:string;sku:string;channel_id:string;state:string;error_code?:string}>;approval_ref:string;actor_ref?:string};
type KillSwitch={enabled:boolean;reason:string;version:number;updated_at:string};

function object<T>(value:unknown):T{return value as T}
function pretty(value:unknown){return JSON.stringify(value,null,2)}
function digestTemplate(){return "0".repeat(64)}

export function MassCatalogPage(){
  const api=useApi() as unknown as Client;
  const auth=useAuth();
  const toast=useToast();
  const canWrite=auth.session?.capabilities.includes("products.write")??false;
  const channelsQuery=useQuery({queryKey:["catalog-bulk","channels"],queryFn:async()=>object<{items:Channel[]}>((await api.listCatalogBulkChannels()).body),staleTime:30_000});
  const historyQuery=useQuery({queryKey:["catalog-bulk","runs"],queryFn:async()=>object<{items:Run[]}>((await api.listCatalogBulkRuns({limit:20})).body),staleTime:10_000});
  const killQuery=useQuery({queryKey:["catalog-bulk","kill-switch"],queryFn:async()=>object<KillSwitch>((await api.getCatalogBulkKillSwitch()).body),staleTime:10_000});
  const [step,setStep]=useState(0),[selectionText,setSelectionText]=useState(""),[projectionsText,setProjectionsText]=useState(""),[changesText,setChangesText]=useState('[{"kind":"set","field":"content.title","value":"Новое название"}]'),[approvalID,setApprovalID]=useState(""),[preview,setPreview]=useState<Preview>(),[run,setRun]=useState<Run>(),[reconcileText,setReconcileText]=useState(""),[reconcileResult,setReconcileResult]=useState<unknown>(),[killReason,setKillReason]=useState("");
  const channels=channelsQuery.data?.items??[];
  useEffect(()=>{if(selectionText||!channels.length)return;const target=channels.find(item=>item.channel_id==="demo")??channels[0];setSelectionText(pretty({filter_digest:digestTemplate(),filter:"saved_filter",skus:["SKU-1"],targets:[{channel_id:target.channel_id,account_id:"demo-account",label:target.label,state:target.state,capabilities:target.capabilities??[],taxonomy_fingerprint:digestTemplate(),taxonomy_version:1,mapping_version:1,observed_at:target.observed_at,fresh_until:target.fresh_until}],snapshot_version:1,created_at:target.observed_at,expires_at:new Date(Date.parse(target.observed_at)+3600000).toISOString()}))},[channels,selectionText]);
  const previewMutation=useMutation({mutationFn:()=>{const body={selection:JSON.parse(selectionText) as unknown,projections:JSON.parse(projectionsText) as unknown,changes:JSON.parse(changesText) as unknown};return api.previewCatalogBulk({body})},onSuccess:response=>{setPreview(object<Preview>(response.body));setStep(3);toast.push({kind:"success",title:"Проверка каталога завершена",body:"Изменения разбиты по SKU и каналу; заблокированные строки не попадут в apply."})},onError:()=>toast.push({kind:"error",title:"Не удалось построить preview",body:"Проверьте scope, projections, fingerprint taxonomy и формат изменений."})});
  const applyMutation=useMutation({mutationFn:()=>api.applyCatalogBulk({idempotencyKey:crypto.randomUUID(),approvalRequestID:approvalID.trim(),body:{preview_id:preview?.id}}),onSuccess:response=>{setRun(object<Run>(response.body));setStep(5);void historyQuery.refetch();toast.push({kind:"success",title:"Массовая операция поставлена в очередь",body:"Каждый channel/account partition сохранён отдельно."})},onError:()=>toast.push({kind:"error",title:"Применение не разрешено",body:"Нужны актуальный preview, право записи и одобрение именно этой операции."})});
  const killMutation=useMutation({mutationFn:()=>api.setCatalogBulkKillSwitch({body:{enabled:!(killQuery.data?.enabled??false),reason:killReason.trim()}}),onSuccess:()=>{void killQuery.refetch();setKillReason("");toast.push({kind:"success",title:"Состояние аварийной остановки изменено"})},onError:()=>toast.push({kind:"error",title:"Не удалось изменить аварийную остановку",body:"Укажите причину и проверьте право products.write."})});
  const reconcileMutation=useMutation({mutationFn:()=>{if(!run)return Promise.reject(new Error("run is missing"));return api.reconcileCatalogBulkRun({runId:run.id,body:JSON.parse(reconcileText) as unknown})},onSuccess:response=>{setReconcileResult(response.body);toast.push({kind:"success",title:"Сверка завершена"})},onError:()=>toast.push({kind:"error",title:"Не удалось выполнить сверку",body:"Проверьте row_id и нормализованный remote observation."})});
  const rows=preview?.rows??[];
  return <Page eyebrow="Каталог · bulk workspace" title="Массовый каталог" description="Одна рабочая область для карточек, изображений, характеристик, вариантов, цен и остатков по нескольким каналам. PIM остаётся источником истины, а неподтверждённые каналы не получают ложную кнопку записи.">
    <section className="hero-grid"><article className="metric-card primary-metric"><span>Каналы</span><strong>{channels.length||"—"}</strong><small>реальное состояние capability</small></article><article className="metric-card"><span>SKU в scope</span><strong>{preview?.affected_sku_count??"—"}</strong><small>immutable selection snapshot</small></article><article className="metric-card"><span>Результат</span><strong>{preview?`${preview.eligible_row_count}/${preview.affected_row_count}`:"—"}</strong><small>{preview?"строк готовы к применению":"после preview"}</small></article></section>
    <section className="panel"><div className="catalog-tabs" role="tablist" aria-label="Этап массового каталога">{["Выбор","Сравнение","Изменения","Проверка","Согласование","История"].map((label,index)=><button type="button" role="tab" aria-selected={step===index} className={step===index?"active":""} key={label} onClick={()=>setStep(index)}>{index+1}. {label}</button>)}</div><p className="table-subline">Сначала сохраняется snapshot фильтра, затем строится before/after diff. Remote apply выполняется отдельными идемпотентными partition jobs.</p></section>
    {channelsQuery.isPending?<LoadingBlock/>:channelsQuery.isError?<ErrorBlock retry={()=>void channelsQuery.refetch()}>Не удалось загрузить capability matrix каналов.</ErrorBlock>:<section className="panel"><div className="section-heading"><div><p className="eyebrow">Capability matrix</p><h2>Доступность массовой записи</h2><p>Статус квалификации нельзя передать из браузера. Demo-контур синтетический; WB/Ozon и другие каналы требуют отдельного evidence.</p></div><button type="button" className="button ghost" onClick={()=>{void channelsQuery.refetch();void killQuery.refetch()}}>Обновить</button></div><div className="chip-list">{channels.map(channel=><span className="chip" key={channel.channel_id}><strong>{channel.label}</strong> · <StatusBadge value={channel.state}/></span>)}</div><div className="inline-notice"><strong>Аварийная остановка: {killQuery.data?.enabled?"включена":"выключена"}</strong><span>{killQuery.data?.reason||"Новые массовые записи разрешены только capability/approval-политикой."}</span>{canWrite?<><input className="field-inline-input" value={killReason} onChange={event=>setKillReason(event.target.value)} placeholder="Причина остановки/возобновления" aria-label="Причина аварийной остановки"/><button type="button" className="button ghost" disabled={killMutation.isPending||!killReason.trim()} onClick={()=>killMutation.mutate()}>{killQuery.data?.enabled?"Возобновить записи":"Остановить записи"}</button></>:null}</div></section>}
    <section className="panel inline-create"><div className="section-heading"><div><p className="eyebrow">Scope и сравнение</p><h2>Выберите карточки и projections</h2><p>Selection и projections приходят из текущего tenant/workspace. Вставьте только нормализованные PIM/channel facts; provider JSON и секреты запрещены.</p></div></div><div className="form-grid"><label className="field"><span>Selection snapshot JSON</span><textarea rows={13} value={selectionText} onChange={event=>setSelectionText(event.target.value)} spellCheck={false}/></label><label className="field"><span>Channel projections JSON</span><textarea rows={13} value={projectionsText} onChange={event=>setProjectionsText(event.target.value)} placeholder={'[{"sku":"SKU-1","product_id":"…","channel_id":"demo","account_id":"demo-account","draft":{…},"currency":"RUB","price_minor_units":10000,"stock":5,"version":1}]'} spellCheck={false}/></label></div><div className="page-actions"><button type="button" className="button ghost" onClick={()=>setStep(1)}>Сравнить каналы</button><button type="button" className="button primary" disabled={previewMutation.isPending||!selectionText.trim()||!projectionsText.trim()} onClick={()=>previewMutation.mutate()}>{previewMutation.isPending?"Проверяем…":"Построить preview"}</button></div></section>
    <section className="panel inline-create"><div><p className="eyebrow">Typed changes</p><h2>Изменения карточки</h2><p>Поддерживаются content/locales через field path, attributes, category, variants, digest-only media, integer price и stock. Очистка и удаление остаются явными операциями.</p></div><label className="field"><span>Changes JSON</span><textarea rows={7} value={changesText} onChange={event=>setChangesText(event.target.value)} spellCheck={false}/></label></section>
    {preview?<section className="panel"><div className="section-heading"><div><p className="eyebrow">Before / after diff</p><h2 className="mono">{preview.id}</h2><p>{preview.eligible_row_count} строк готовы · {preview.blocked_row_count} заблокированы. Невалидная строка не отправляется вместе с валидной.</p></div><StatusBadge value={preview.blocked_row_count?"needs_attention":"ready"}/></div><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Канал</th><th>Изменения</th><th>Capability</th><th>Решение</th><th>Диагностика</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="mono">{row.sku}</td><td>{row.channel_id}<br/><span className="mono">{row.account_id}</span></td><td>{row.changed_fields?.length?row.changed_fields.join(", "):"нет"}</td><td><StatusBadge value={row.capability_state}/></td><td><StatusBadge value={row.eligible?"ready":"blocked"}/></td><td>{row.diagnostics?.length?<div className="timeline">{row.diagnostics.map((item,index)=><span key={`${item.code}-${index}`}><strong>{item.field_path}</strong> · {item.message}<small className="table-subline">{item.remediation}</small></span>)}</div>:"—"}</td></tr>)}</tbody></table></div><div className="page-actions">{canWrite&&preview.eligible_row_count>0?<><input className="field-inline-input" value={approvalID} onChange={event=>setApprovalID(event.target.value)} placeholder="Approval request ID" aria-label="Approval request ID"/><button type="button" className="button secondary" disabled={!approvalID.trim()||applyMutation.isPending} onClick={()=>applyMutation.mutate()}>{applyMutation.isPending?"Ставим в очередь…":"Согласовать и применить готовые строки"}</button></>:<span className="table-subline">Применение скрыто: нужны products.write и approval.</span>}</div></section>:null}
    {run?<section className="panel report-result"><div className="section-heading"><div><p className="eyebrow">Durable run</p><h2>История применения</h2></div><StatusBadge value={run.state}/></div><dl className="detail-list"><div><dt>Run ID</dt><dd className="mono">{run.id}</dd></div><div><dt>Actor</dt><dd className="mono">{run.actor_ref??"—"}</dd></div><div><dt>Partition jobs</dt><dd>{run.partitions.length}</dd></div><div><dt>Строки</dt><dd>{run.results.length}</dd></div><div><dt>Approval</dt><dd className="mono">{run.approval_ref}</dd></div></dl><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Канал</th><th>Состояние</th><th>Ошибка</th></tr></thead><tbody>{run.results.map(item=><tr key={item.row_id}><td className="mono">{item.sku}</td><td>{item.channel_id}</td><td><StatusBadge value={item.state}/></td><td>{item.error_code??"—"}</td></tr>)}</tbody></table></div><label className="field"><span>Read-after-write observation JSON</span><textarea rows={5} value={reconcileText} onChange={event=>setReconcileText(event.target.value)} placeholder={'{"row_id":"…","observation":{"row_id":"…","remote_id":"…","observed_digest":"…","status":"published","observed_at":"…"}}'} spellCheck={false}/></label><div className="page-actions"><button type="button" className="button secondary" disabled={!reconcileText.trim()||reconcileMutation.isPending} onClick={()=>reconcileMutation.mutate()}>{reconcileMutation.isPending?"Сверяем…":"Сверить remote state"}</button></div>{reconcileResult?<pre className="code-block">{pretty(reconcileResult)}</pre>:null}</section>:null}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Cursor history</p><h2>Последние массовые операции</h2><p>История читается из PostgreSQL и не считается успешной по одному общему статусу.</p></div><button type="button" className="button ghost" onClick={()=>void historyQuery.refetch()}>Обновить историю</button></div>{historyQuery.isError?<ErrorBlock retry={()=>void historyQuery.refetch()}>История временно недоступна.</ErrorBlock>:<div className="table-wrap"><table><thead><tr><th>Run</th><th>Actor</th><th>State</th><th>Строки</th></tr></thead><tbody>{(historyQuery.data?.items??[]).map(item=><tr key={item.id}><td className="mono">{item.id}</td><td className="mono">{item.actor_ref??"—"}</td><td><StatusBadge value={item.state}/></td><td>{item.results.length}</td></tr>)}</tbody></table></div>}</section>
  </Page>;
}
