import {useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {Page} from "./Page";

type Evidence={source_kind:string;source_ref:string;source_version?:string;freshness:string;observed_at:string;checked_at:string;deep_link?:string;evidence_digest:string;age_seconds:number;ttl_seconds:number};
type Answer={summary:string;text:string;grounding_state:string;coverage_percent:number;facts:Array<{code:string;label:string;value:string;source:Evidence}>;evidence:Evidence[];limitations:string[];recommendations:Array<{code:string;title:string;reason:string;expected_effect:string;next_link?:string}>;action_previews:Array<{id:string;action:string;risk:string;approval_required:boolean;impact:string;status:string}>};
type Run={id:string;session_id:string;state:string;intent:string;context_digest:string;answer?:Answer;version:number;created_at:string;updated_at:string};
type Session={id:string;title?:string;locale:string;version:number;updated_at:string};
const list=(body:unknown):Session[]=>{const value=body as {items?:unknown};return Array.isArray(value?.items)?value.items as Session[]:[]};

export function OperatorAssistantPage(){
 const api=useApi() as any; const cache=useQueryClient(); const [sessionID,setSessionID]=useState(""); const [question,setQuestion]=useState(""); const [run,setRun]=useState<Run>();
 const sessions=useQuery({queryKey:["assistant","sessions"],queryFn:async()=>list((await api.listAssistantSessions({limit:20})).body),staleTime:10_000});
 useEffect(()=>{if(!sessionID&&sessions.data?.[0])setSessionID(sessions.data[0].id)},[sessionID,sessions.data]);
 const create=useMutation({mutationFn:()=>api.createAssistantSession({idempotencyKey:crypto.randomUUID(),body:{title:"Операторский помощник",locale:"ru-RU"}}),onSuccess:async(response:any)=>{const value=response.body as Session;setSessionID(value.id);await cache.invalidateQueries({queryKey:["assistant","sessions"]})}});
 const ask=useMutation({mutationFn:async()=>{if(!sessionID)throw Error("session required");return api.sendAssistantMessage({sessionId:sessionID,idempotencyKey:crypto.randomUUID(),body:{question:question.trim()}})},onSuccess:(response:any)=>{setRun(response.body as Run);setQuestion("")}});
 const stateLabel=useMemo(()=>({grounded:"Подтверждено источниками",partially_grounded:"Частично подтверждено",insufficient_data:"Недостаточно данных",stale_data:"Данные устарели",source_unavailable:"Источник недоступен",refused:"Запрос отклонён"} as Record<string,string>),[]);
 return <Page eyebrow="Операторский контур" title="AI-помощник оператора" description="Факты из разрешённых модулей, ссылки на источники и типизированные previews. Помощник не выполняет действия и не получает доступ к секретам.">
  <section className="assistant-layout">
   <aside className="panel assistant-sessions"><div className="settings-card-heading"><div><p className="eyebrow">Сессии</p><h2>Диалоги</h2></div><button className="button secondary" onClick={()=>create.mutate()} disabled={create.isPending}>{create.isPending?"Создаём…":"Новая сессия"}</button></div>{sessions.isPending?<LoadingBlock/>:sessions.isError?<ErrorBlock retry={()=>void sessions.refetch()}>Не удалось загрузить сессии.</ErrorBlock>:sessions.data?.length? <div className="assistant-session-list">{sessions.data.map(item=><button type="button" className={`assistant-session ${item.id===sessionID?"active":""}`} key={item.id} onClick={()=>{setSessionID(item.id);setRun(undefined)}}><strong>{item.title||"Без названия"}</strong><small>{new Date(item.updated_at).toLocaleString("ru-RU")}</small></button>)}</div>:<p className="settings-note">Создайте первую сессию.</p>}</aside>
   <section className="panel assistant-chat"><div className="settings-card-heading"><div><p className="eyebrow">Безопасный ответ</p><h2>Что нужно проверить?</h2></div><span className="status status-active">только чтение</span></div>
    <div className="assistant-examples"><button type="button" onClick={()=>setQuestion("Что требует внимания в интеграциях?")}>Что требует внимания?</button><button type="button" onClick={()=>setQuestion("Почему товар не публикуется?")}>Почему товар не публикуется?</button><button type="button" onClick={()=>setQuestion("Сформируй план исправления")}>План исправления</button></div>
    <form className="assistant-composer" onSubmit={event=>{event.preventDefault();if(question.trim()&&sessionID)ask.mutate()}}><textarea value={question} maxLength={2000} placeholder="Например: Что требует внимания в интеграциях?" onChange={event=>setQuestion(event.target.value)} disabled={!sessionID||ask.isPending}/><button className="button primary" type="submit" disabled={!sessionID||!question.trim()||ask.isPending}>{ask.isPending?"Проверяем…":"Спросить"}</button></form>
    {!sessionID?<p className="settings-note">Сначала создайте сессию.</p>:null}{ask.isError?<ErrorBlock>Ответ не получен. Повторите вопрос.</ErrorBlock>:null}
    {run?<article className="assistant-answer"><div className="assistant-answer-meta"><span className="status status-active">{stateLabel[run.answer?.grounding_state??""]??run.state}</span><span>Покрытие источниками: {run.answer?.coverage_percent??0}%</span><span>Намерение: {run.intent}</span></div><h3>{run.answer?.summary??"Ответ готовится"}</h3><p className="assistant-answer-text">{run.answer?.text}</p>{run.answer?.limitations?.length?<div className="assistant-limitations"><strong>Ограничения</strong><ul>{run.answer.limitations.map(item=><li key={item}>{item}</li>)}</ul></div>:null}{run.answer?.evidence?.length?<div className="assistant-evidence"><strong>Источники</strong>{run.answer.evidence.map(item=><a href={item.deep_link||"#"} key={item.evidence_digest}><span>{item.source_kind} · {item.source_ref}</span><small>{item.freshness} · проверено {new Date(item.checked_at).toLocaleString("ru-RU")}</small></a>)}</div>:null}{run.answer?.action_previews?.length?<div className="assistant-previews"><strong>Предварительные действия (без исполнения)</strong>{run.answer.action_previews.map(item=><div key={item.id}><span>{item.action}</span><small>{item.approval_required?"Требуется согласование":"Только чтение"} · {item.status}</small></div>)}</div>:null}</article>:<div className="assistant-empty">Ответы появляются здесь вместе с состоянием подтверждения и источниками.</div>}
   </section>
  </section>
 </Page>
}
