import {useState} from "react";
import {useMutation} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {Page} from "./Page";
import {StatusBadge} from "../components/StatusBadge";

type Row = {id:string; offer_id:string; sku:string; currency:string; current_minor:string; proposed_minor:string; floor_minor:string; max_change_bps:string};
type Result = {id:string; input_digest:string; status:string; generated_at:string; candidate_count:number; blocked_count:number; candidates:Array<Row & {status:string; delta_minor:number; delta_bps:number; explanation:string; approval_required:boolean}>};
const emptyRow = ():Row => ({id:"", offer_id:"", sku:"", currency:"RUB", current_minor:"", proposed_minor:"", floor_minor:"", max_change_bps:"500"});
const number = (value:string) => Number(value);

export function PricingPage() {
  const api = useApi();
  const [rows, setRows] = useState<Row[]>([emptyRow()]);
  const [result, setResult] = useState<Result>();
  const preview = useMutation({mutationFn: async () => api.previewRepricing({body: {candidates: rows.map((row) => ({...row, id: row.id.trim() || row.offer_id.trim(), current_minor:number(row.current_minor), proposed_minor:number(row.proposed_minor), floor_minor:number(row.floor_minor), max_change_bps:number(row.max_change_bps)}))}}), onSuccess: (response) => setResult(response.body as Result)});
  const valid = rows.length > 0 && rows.length <= 1000 && rows.every((row) => row.id.trim() && row.offer_id.trim() && row.sku.trim() && [row.current_minor,row.proposed_minor,row.floor_minor,row.max_change_bps].every((value) => /^\d+$/.test(value)));
  const update = (index:number, key:keyof Row, value:string) => setRows((current) => current.map((row, rowIndex) => rowIndex === index ? {...row, [key]:value} : row));
  return <Page eyebrow="Цены и правила" title="Цены и repricing" description="Проверьте массовое изменение цен до отправки в marketplace. Предпросмотр учитывает минимальную цену и максимальный шаг; удалённый кабинет не вызывается.">
    <section className="panel inline-create"><div><h2>Предпросмотр изменения</h2><p>Суммы указаны в минимальных единицах валюты. Заблокированные строки не могут перейти в apply-пакет. Для реальной записи потребуется отдельная квалификация коннектора и согласование.</p></div><div className="table-wrap"><table><thead><tr><th>Offer / SKU</th><th>Текущая</th><th>Новая</th><th>Минимум</th><th>Шаг, bps</th><th></th></tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td><input value={row.offer_id} onChange={(event) => update(index,"offer_id",event.target.value)} placeholder="Offer ID" aria-label="Offer ID"/><input value={row.sku} onChange={(event) => update(index,"sku",event.target.value)} placeholder="SKU" aria-label="SKU"/></td><td><input type="number" min="0" value={row.current_minor} onChange={(event) => update(index,"current_minor",event.target.value)} aria-label="Текущая цена"/></td><td><input type="number" min="0" value={row.proposed_minor} onChange={(event) => update(index,"proposed_minor",event.target.value)} aria-label="Новая цена"/></td><td><input type="number" min="0" value={row.floor_minor} onChange={(event) => update(index,"floor_minor",event.target.value)} aria-label="Минимальная цена"/></td><td><input type="number" min="0" max="10000" value={row.max_change_bps} onChange={(event) => update(index,"max_change_bps",event.target.value)} aria-label="Максимальный шаг"/></td><td><button className="button ghost" type="button" disabled={rows.length === 1} onClick={() => setRows((current) => current.filter((_, rowIndex) => rowIndex !== index))}>Удалить</button></td></tr>)}</tbody></table></div><div className="form-actions"><button className="button ghost" type="button" disabled={rows.length >= 1000} onClick={() => setRows((current) => [...current, emptyRow()])}>Добавить строку</button><button className="button primary" type="button" disabled={!valid || preview.isPending} onClick={() => preview.mutate()}>{preview.isPending ? "Проверяем…" : "Рассчитать preview"}</button></div>{preview.isError && <p className="panel alert error" role="alert">Не удалось рассчитать preview. Проверьте значения и доступ к каталогу.</p>}</section>
    {result && <section className="panel"><div className="drawer-section-heading"><div><h2>Результат {result.id}</h2><p>Digest {result.input_digest} · {new Date(result.generated_at).toLocaleString("ru-RU")}</p></div><StatusBadge value={result.status}/></div><p className="settings-note">Строк: {result.candidate_count} · заблокировано: {result.blocked_count}. Preview не меняет цены и не отправляет запросы во внешний кабинет.</p><div className="table-wrap"><table><thead><tr><th>SKU</th><th>Статус</th><th>Изменение</th><th>Причина</th></tr></thead><tbody>{result.candidates.map((candidate) => <tr key={candidate.id}><td><strong>{candidate.sku}</strong><small className="table-subline mono">{candidate.offer_id}</small></td><td><StatusBadge value={candidate.status}/></td><td>{candidate.delta_minor} ({candidate.delta_bps} bps)</td><td>{candidate.explanation}</td></tr>)}</tbody></table></div></section>}
  </Page>;
}
