import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {DataTable} from "../components/DataTable";
import {Drawer} from "../components/Drawer";
import {EmptyState} from "../components/EmptyState";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {StatusBadge} from "../components/StatusBadge";
import {Page} from "./Page";

type QualityRun = {id:string;product_id:string;offer_id?:string;connector_account_id:string;connector_id:string;channel_family:string;decision:string;score_bps:number;evaluated_at:string;valid_until:string;version:number};
type QualityDetail = QualityRun & {target:{product_id:string;offer_id?:string;connector_account_id:string;connector_id:string;channel_family:string;locale:string;jurisdiction:string};snapshot_digest:string;profile_digest:string;status:string;category_scores_bps:Record<string,number>;issues:Array<{code:string;category:string;severity:string;field_path:string;message:string;expected?:string;observed?:string;remediation:string}>};
const categoryLabels:Record<string,string>={identity_content:"Идентичность и контент",category_attributes:"Категория и атрибуты",media:"Медиа",price_stock:"Цена и остатки",compliance:"Соответствие",mapping_capability:"Mapping и capability",localization:"Локализация",channel_contract:"Контракт канала"};
const decisionLabels:Record<string,string>={ready:"Готово",ready_with_warnings:"Готово с предупреждениями",blocked:"Заблокировано",approval_required:"Требуется согласование",stale:"Устарело",unsupported:"Не поддерживается",not_configured:"Не настроено",unknown:"Неизвестно"};
function percent(score:number){return `${Math.round(score/100)}%`}
function decodeRuns(value:unknown):QualityRun[]{const root=value as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid quality runs");return root.items as QualityRun[]}

export function PublicationQualityPage(){
 const api=useApi(),[selected,setSelected]=useState<QualityRun|null>(null);
 const runs=useQuery({queryKey:["publication-quality","runs"],queryFn:async()=>decodeRuns((await api.listPublicationQualityRuns({limit:100})).body),refetchInterval:30_000});
 const detail=useQuery({queryKey:["publication-quality","run",selected?.id],enabled:!!selected,queryFn:async()=>(await api.getPublicationQualityRun({runId:selected!.id})).body as QualityDetail});
 return <Page eyebrow="Каталог" title="Качество публикации" description="Проверка готовности товара для конкретного кабинета до выхода в канал. Старые или неполные факты не превращаются в успешную публикацию.">
  <div className="hero-grid"><article className="metric-card primary-metric"><span>Проверок</span><strong>{runs.data?.length??0}</strong><small>последние запуски</small></article><article className="metric-card"><span>Готовы</span><strong>{runs.data?.filter(v=>v.decision==="ready"||v.decision==="ready_with_warnings").length??0}</strong><small>можно публиковать</small></article><article className="metric-card"><span>Требуют внимания</span><strong>{runs.data?.filter(v=>!["ready","ready_with_warnings"].includes(v.decision)).length??0}</strong><small>блокировки и stale</small></article></div>
  {runs.isPending?<LoadingBlock/>:runs.isError?<ErrorBlock retry={()=>void runs.refetch()}>Не удалось загрузить центр качества публикации.</ErrorBlock>:runs.data.length===0?<EmptyState title="Проверок публикации пока нет" text="После запуска quality preflight здесь появятся target-specific решения и причины блокировок."/>:<DataTable rows={runs.data} rowKey={v=>v.id} searchPlaceholder="Товар, кабинет, канал или решение…" onOpen={setSelected} columns={[{key:"product",label:"Товар",value:v=>`${v.product_id} ${v.offer_id??""}`,render:v=><span><strong className="mono">{v.product_id}</strong>{v.offer_id?<small className="table-subline mono">Offer {v.offer_id}</small>:null}</span>},{key:"target",label:"Цель",value:v=>`${v.connector_id} ${v.channel_family}`,render:v=><span><strong>{v.connector_id}</strong><small className="table-subline">{v.channel_family} · {v.connector_account_id}</small></span>},{key:"decision",label:"Решение",value:v=>decisionLabels[v.decision]??v.decision,render:v=><StatusBadge value={v.decision}/>},{key:"score",label:"Score",value:v=>v.score_bps,render:v=><strong>{percent(v.score_bps)}</strong>,align:"end"},{key:"evaluated",label:"Проверено",value:v=>v.evaluated_at,render:v=><time>{new Date(v.evaluated_at).toLocaleString("ru-RU")}</time>}]}/>} 
  <Drawer open={!!selected} title="Результат проверки" subtitle={selected?`${selected.connector_id} · ${selected.connector_account_id}`:undefined} onClose={()=>setSelected(null)}>{detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock retry={()=>void detail.refetch()}>Не удалось открыть результат проверки.</ErrorBlock>:detail.data?<QualityDetailView value={detail.data}/>:null}</Drawer>
 </Page>
}

function QualityDetailView({value}:{value:QualityDetail}){return <div className="catalog-stack"><div className="drawer-kpis"><div><small>Решение</small><StatusBadge value={value.decision}/><strong>{decisionLabels[value.decision]??value.decision}</strong></div><div><small>Score</small><strong>{percent(value.score_bps)}</strong><span>версия {value.version}</span></div><div><small>Статус run</small><StatusBadge value={value.status}/></div></div><section className="drawer-section"><h3>Цель и evidence</h3><dl className="detail-list"><div><dt>Товар</dt><dd className="mono">{value.target.product_id}</dd></div><div><dt>Кабинет</dt><dd className="mono">{value.target.connector_account_id}</dd></div><div><dt>Локаль / страна</dt><dd>{value.target.locale} · {value.target.jurisdiction}</dd></div><div><dt>Проверено</dt><dd>{new Date(value.evaluated_at).toLocaleString("ru-RU")}</dd></div><div><dt>Действует до</dt><dd>{new Date(value.valid_until).toLocaleString("ru-RU")}</dd></div><div><dt>Snapshot</dt><dd className="mono">{value.snapshot_digest}</dd></div><div><dt>Profile</dt><dd className="mono">{value.profile_digest}</dd></div></dl></section><section className="drawer-section"><h3>Оценка по категориям</h3><div className="chip-list">{Object.entries(value.category_scores_bps??{}).map(([key,score])=><span className="chip" key={key}>{categoryLabels[key]??key}: {percent(score)}</span>)}</div></section><section className="drawer-section"><h3>Проблемы и исправления</h3>{value.issues?.length?<div className="timeline">{value.issues.map((issue,index)=><article key={`${issue.code}-${issue.field_path}-${index}`}><span className="timeline-dot"/><div><strong><StatusBadge value={issue.severity}/> {issue.message}</strong><small>{issue.field_path||"Карточка товара"} · {issue.expected||""}{issue.observed?` · сейчас: ${issue.observed}`:""}</small><span>{issue.remediation}</span></div></article>)}</div>:<p className="settings-note">Проблем не обнаружено.</p>}</section></div>}
