import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {connectorCatalog} from "../generated/connector-catalog";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {navigate} from "../shell/useLocationPath";
import {Page} from "./Page";

interface ConnectorAccount{id:string;connector_id:string;family:string;status:string;health_status:string;capabilities:{capability:string;enabled:boolean}[]}
interface SocialChannel{id:string;connector_account_id:string;display_name:string;capabilities:string[];status:"active"|"disabled";version:number}
interface SocialButton{text:string;url:string}
interface SocialPublication{id:string;channel_account_id:string;channel_name:string;text:string;buttons?:SocialButton[];status:string;reason_code?:string;attempt:number;publish_at?:string;published_at?:string;version:number;created_at:string}
type Response={body:unknown};
type Client={listConnectorAccounts(input?:object):Promise<Response>;listSocialChannels(input?:object):Promise<Response>;createSocialChannel(input:{idempotencyKey:string;body:unknown}):Promise<Response>;updateSocialChannel(input:{channelId:string;idempotencyKey:string;body:unknown}):Promise<Response>;listSocialPublications(input?:object):Promise<Response>;createSocialPublication(input:{idempotencyKey:string;body:unknown}):Promise<Response>};

function items<T>(value:unknown):T[]{const root=value as {items?:unknown};if(!Array.isArray(root?.items))throw new Error("invalid social response");return root.items as T[]}
function uuidV7(){const bytes=crypto.getRandomValues(new Uint8Array(16)),millis=BigInt(Date.now());for(let index=5;index>=0;index--)bytes[5-index]=Number((millis>>BigInt(index*8))&255n);bytes[6]=(bytes[6]&15)|112;bytes[8]=(bytes[8]&63)|128;const raw=[...bytes].map(value=>value.toString(16).padStart(2,"0")).join("");return `${raw.slice(0,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}-${raw.slice(16,20)}-${raw.slice(20)}`}
const statusLabels:Record<string,string>={scheduled:"Запланировано",ready:"В очереди",publishing:"Публикуется",published:"Опубликовано",failed:"Ошибка",cancelled:"Отменено",active:"Активен",disabled:"Отключён"};

export function SocialPage(){
 const api=useApi() as unknown as Client,cache=useQueryClient(),toast=useToast();
 const [accountId,setAccountId]=useState(""),[channelName,setChannelName]=useState("Новый канал"),[channelId,setChannelId]=useState(""),[text,setText]=useState(""),[publishAt,setPublishAt]=useState(""),[buttonRows,setButtonRows]=useState<SocialButton[]>([]);
 const accounts=useQuery({queryKey:["social","connector-accounts"],queryFn:async()=>items<ConnectorAccount>((await api.listConnectorAccounts({limit:100})).body),staleTime:10_000});
 const channels=useQuery({queryKey:["social","channels"],queryFn:async()=>items<SocialChannel>((await api.listSocialChannels({limit:100})).body),staleTime:5_000});
 const publications=useQuery({queryKey:["social","publications"],queryFn:async()=>items<SocialPublication>((await api.listSocialPublications({limit:50})).body),refetchInterval:5_000});
 const socialAccounts=useMemo(()=>(accounts.data??[]).filter(value=>value.family==="social"&&value.status==="active"&&value.health_status==="healthy"&&value.capabilities.some(capability=>capability.capability==="social.post.text"&&capability.enabled)),[accounts.data]);
 const activeChannels=(channels.data??[]).filter(value=>value.status==="active");
 const selectedChannel=activeChannels.find(value=>value.id===channelId),selectedAccount=(accounts.data??[]).find(value=>value.id===selectedChannel?.connector_account_id),selectedRuntime=connectorCatalog.find(value=>value.id===selectedAccount?.connector_id)?.runtime;
 const textLimit=selectedRuntime?.socialTextMaxRunes??Math.max(0,...socialAccounts.map(account=>connectorCatalog.find(value=>value.id===account.connector_id)?.runtime.socialTextMaxRunes??0));
 const textRunes=[...text].length;
 const buttonsAllowed=!!selectedChannel?.capabilities.includes("social.post.buttons");
 const buttonsValid=buttonRows.length<=8&&buttonRows.every(button=>button.text.trim().length>0&&button.text.trim().length<=64&&button.url.startsWith("https://")&&!/\s/.test(button.url)&&button.url.length<=2048);
 const connectorName=(connectorId:string)=>connectorCatalog.find(value=>value.id===connectorId)?.name??connectorId;
 const createChannel=useMutation({mutationFn:async()=>{const id=uuidV7();return api.createSocialChannel({idempotencyKey:id,body:{id,connector_account_id:accountId,display_name:channelName.trim(),active:true}})},onSuccess:async()=>{toast.push({kind:"success",title:"Канал готов к публикациям"});setChannelName("Новый канал");await cache.invalidateQueries({queryKey:["social","channels"]})},onError:()=>toast.push({kind:"error",title:"Не удалось создать канал",body:"Проверьте кабинет, права бота и включённую возможность публикации текста."})});
 const toggleChannel=useMutation({mutationFn:(channel:SocialChannel)=>api.updateSocialChannel({channelId:channel.id,idempotencyKey:`social-channel:${channel.id}:${channel.version}`,body:{display_name:channel.display_name,status:channel.status==="active"?"disabled":"active",expected_version:channel.version}}),onSuccess:()=>cache.invalidateQueries({queryKey:["social","channels"]})});
 const publish=useMutation({mutationFn:async()=>{const id=uuidV7(),body:{id:string;channel_account_id:string;text:string;buttons?:SocialButton[];publish_at?:string}={id,channel_account_id:channelId,text:text.trim()};const buttons=buttonRows.map(button=>({text:button.text.trim(),url:button.url.trim()}));if(buttons.length)body.buttons=buttons;if(publishAt)body.publish_at=new Date(publishAt).toISOString();return api.createSocialPublication({idempotencyKey:id,body})},onSuccess:async()=>{toast.push({kind:"success",title:publishAt?"Публикация запланирована":"Публикация поставлена в очередь"});setText("");setPublishAt("");setButtonRows([]);await cache.invalidateQueries({queryKey:["social","publications"]})},onError:()=>toast.push({kind:"error",title:"Публикация не создана",body:"Проверьте канал, текст и HTTPS-ссылки кнопок."})});
 if(accounts.isPending||channels.isPending||publications.isPending)return <Page eyebrow="Публикации" title="Публикации" description="Подготовка каналов и публикаций."><LoadingBlock/></Page>;
 if(accounts.isError||channels.isError||publications.isError)return <Page eyebrow="Публикации" title="Публикации" description="Подготовка каналов и публикаций."><ErrorBlock retry={()=>void Promise.all([accounts.refetch(),channels.refetch(),publications.refetch()])}>Не удалось загрузить публикации.</ErrorBlock></Page>;
 return <Page eyebrow="Публикации" title="Публикации" description="Каноническая очередь текстовых публикаций с безопасной доставкой в Telegram и MAX. Лимит определяется выбранным каналом.">
  {socialAccounts.length===0?<section className="panel social-onboarding"><div><h2>Сначала подключите социальный канал</h2><p>Добавьте Telegram- или MAX-бота, укажите chat_id, выполните проверку, включите возможность публикации текста и активируйте кабинет.</p></div><button className="button primary" onClick={()=>navigate("/integrations")}>Открыть интеграции</button></section>:<section className="panel social-setup"><div className="section-heading"><div><p className="eyebrow">Каналы</p><h2>Подключить канал к публикациям</h2></div></div><div className="social-form-grid"><label className="field"><span>Кабинет</span><select value={accountId} onChange={event=>setAccountId(event.target.value)}><option value="">Выберите кабинет</option>{socialAccounts.map(account=><option key={account.id} value={account.id}>{connectorName(account.connector_id)} · {account.id}</option>)}</select></label><label className="field"><span>Название канала</span><input maxLength={300} value={channelName} onChange={event=>setChannelName(event.target.value)}/></label><button className="button primary" disabled={!accountId||!channelName.trim()||createChannel.isPending} onClick={()=>createChannel.mutate()}>Создать канал</button></div></section>}
  {(channels.data??[]).length?<section className="social-channel-strip">{(channels.data??[]).map(channel=><article className="panel social-channel-card" key={channel.id}><div><strong>{channel.display_name}</strong><small>{channel.connector_account_id}</small></div><StatusBadge value={statusLabels[channel.status]??channel.status}/><button className="button ghost" disabled={toggleChannel.isPending} onClick={()=>toggleChannel.mutate(channel)}>{channel.status==="active"?"Отключить":"Включить"}</button></article>)}</section>:null}
  <section className="panel social-composer"><div className="section-heading"><div><p className="eyebrow">Новая публикация</p><h2>Текстовая публикация</h2><p>Отправка выполняется worker-процессом. При неизвестном исходе автоматический повтор запрещён.</p></div><span className={textLimit>0&&textRunes>textLimit?"danger-text":""}>{textRunes}/{textLimit||"—"}</span></div><label className="field"><span>Канал</span><select value={channelId} onChange={event=>setChannelId(event.target.value)}><option value="">Выберите активный канал</option>{activeChannels.map(channel=><option value={channel.id} key={channel.id}>{channel.display_name}</option>)}</select></label><label className="field"><span>Текст</span><textarea className="social-textarea" value={text} onChange={event=>setText(event.target.value)} placeholder="Текст публикации…"/></label><div className="social-buttons"><div className="social-buttons-heading"><div><strong>Кнопки-ссылки</strong><small>Необязательно. Только HTTPS-ссылки, до 8 кнопок.</small></div><button type="button" className="button ghost" disabled={!buttonsAllowed||buttonRows.length>=8} onClick={()=>setButtonRows(rows=>[...rows,{text:"",url:"https://"}])}>Добавить кнопку</button></div>{!buttonsAllowed?<p className="settings-note">Выберите Telegram-канал с включённой возможностью «Интерактивные кнопки».</p>:null}{buttonRows.map((button,index)=><div className="social-button-row" key={index}><input aria-label={`Текст кнопки ${index+1}`} maxLength={64} value={button.text} placeholder="Например, Открыть товар" onChange={event=>setButtonRows(rows=>rows.map((row,rowIndex)=>rowIndex===index?{...row,text:event.target.value}:row))}/><input aria-label={`URL кнопки ${index+1}`} maxLength={2048} value={button.url} placeholder="https://example.ru" onChange={event=>setButtonRows(rows=>rows.map((row,rowIndex)=>rowIndex===index?{...row,url:event.target.value}:row))}/><button type="button" className="button ghost" aria-label={`Удалить кнопку ${index+1}`} onClick={()=>setButtonRows(rows=>rows.filter((_,rowIndex)=>rowIndex!==index))}>Удалить</button></div>)}{buttonRows.length>0&&!buttonsValid?<small className="danger-text">У каждой кнопки должен быть текст и корректная HTTPS-ссылка.</small>:null}</div><div className="social-publish-row"><label className="field"><span>Опубликовать не раньше</span><input type="datetime-local" value={publishAt} onChange={event=>setPublishAt(event.target.value)}/></label><button className="button primary" disabled={!channelId||!text.trim()||textLimit<1||textRunes>textLimit||!buttonsAllowed&&buttonRows.length>0||!buttonsValid||publish.isPending} onClick={()=>publish.mutate()}>{publishAt?"Запланировать":"Опубликовать"}</button></div></section>
  <section><div className="section-heading"><div><p className="eyebrow">История</p><h2>Последние публикации</h2></div></div>{(publications.data??[]).length===0?<EmptyState title="Публикаций пока нет" text="Создайте первый текст выше."/>:<div className="social-publication-list">{(publications.data??[]).map(item=><article className="panel social-publication-card" key={item.id}><div className="social-publication-meta"><strong>{item.channel_name}</strong><StatusBadge value={statusLabels[item.status]??item.status}/><time>{new Date(item.created_at).toLocaleString("ru-RU")}</time></div><p>{item.text}</p>{item.buttons?.length?<div className="social-publication-buttons">{item.buttons.map(button=><a href={button.url} target="_blank" rel="noreferrer" key={`${button.text}-${button.url}`}>{button.text}</a>)}</div>:null}{item.reason_code?<small className="danger-text">Код: {item.reason_code}</small>:null}</article>)}</div>}</section>
 </Page>
}
