import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {ConnectorBootstrapControls} from "../features/settings/ConnectorBootstrapControls";
import {Page} from "./Page";
import {DataTable} from "../components/DataTable";
import {Drawer} from "../components/Drawer";
import {useToast} from "../components/Toast";
import {labelFor,syncActionLabels,syncModeLabels} from "../components/labels";

type Policy={id:string;connector_account_id:string;entity_type:string;direction:string;source_of_truth:string;enabled:boolean;version:number;updated_at:string};
type Run={id:string;policy_id:string;mode:string;status:string;scanned_count:number;drift_count:number;started_at:string;updated_at:string};
type Drift={id:string;run_id:string;policy_id:string;kind:string;local_entity_id:string;remote_id:string;local_status:string;remote_status:string;status:string;recommended_action:string;version:number;detected_at:string};
type SyncStatus={summary:{enabled_policies:number;active_runs:number;open_drifts:number};policies:Policy[];runs:Run[];drifts:Drift[]};
type Account={id:string;connector_id:string;status:string;health_status:string;version:number};
function decode(value:unknown):SyncStatus{const v=value as SyncStatus;if(!v||!v.summary||!Array.isArray(v.policies)||!Array.isArray(v.runs)||!Array.isArray(v.drifts))throw new Error("invalid sync status");return v}
function decodeAccounts(value:unknown):Account[]{const v=value as {items?:unknown};if(!v||!Array.isArray(v.items))throw new Error("invalid accounts");return v.items as Account[]}
const entityLabels:Record<string,string>={products:"Товары",offers:"Предложения",prices:"Цены",inventory:"Остатки",orders:"Заказы"};
const directionLabels:Record<string,string>={inbound:"Из кабинета в TORGNEXA",outbound:"Из TORGNEXA в кабинет",bidirectional:"В обе стороны"};
const sourceLabels:Record<string,string>={local:"TORGNEXA",remote:"Внешний кабинет",manual:"Ручное разрешение"};

export function SyncPage(){
 const api=useApi(),cache=useQueryClient(),toast=useToast();const [selectedDrift,setSelectedDrift]=useState<Drift|null>(null);const [account,setAccount]=useState(""),[entity,setEntity]=useState("orders"),[direction,setDirection]=useState("inbound"),[source,setSource]=useState("remote");
 const query=useQuery({queryKey:["sync","status"],queryFn:async()=>decode((await api.getSyncStatus()).body),refetchInterval:30_000});
 const accounts=useQuery({queryKey:["connector-accounts"],queryFn:async()=>decodeAccounts((await api.listConnectorAccounts({limit:100})).body)});
 const create=useMutation({mutationFn:async()=>{const id=crypto.randomUUID();await api.createSyncPolicy({idempotencyKey:id,body:{id,connector_account_id:account,entity_type:entity,direction,source_of_truth:source}})},onSuccess:async()=>{toast.push({kind:"success",title:"Политика синхронизации добавлена"});await cache.invalidateQueries({queryKey:["sync","status"]})},onError:()=>toast.push({kind:"error",title:"Не удалось добавить политику",body:"Проверьте кабинет, сущность и направление обмена."})});
 const update=useMutation({mutationFn:async({policy,changes}:{policy:Policy;changes:Partial<Pick<Policy,"direction"|"source_of_truth"|"enabled">>})=>api.updateSyncPolicy({policyId:policy.id,idempotencyKey:crypto.randomUUID(),body:{direction:changes.direction??policy.direction,source_of_truth:changes.source_of_truth??policy.source_of_truth,enabled:changes.enabled??policy.enabled,expected_version:policy.version}}),onSuccess:async()=>{await cache.invalidateQueries({queryKey:["sync","status"]})}});
 const run=useMutation({mutationFn:async(policy:Policy)=>api.runSyncPolicy({policyId:policy.id,idempotencyKey:crypto.randomUUID()}),onSuccess:async()=>{toast.push({kind:"success",title:"Сверка поставлена в очередь"});await cache.invalidateQueries({queryKey:["sync","status"]})},onError:()=>toast.push({kind:"error",title:"Не удалось запустить сверку",body:"Проверьте активность политики и права на синхронизацию."})});
 const reconcile=useMutation({mutationFn:async(policy:Policy)=>api.createReconciliationJob({idempotencyKey:crypto.randomUUID(),body:{policy_id:policy.id,mode:"on_demand"}}),onSuccess:async()=>{toast.push({kind:"success",title:"Полная сверка поставлена в очередь"});await cache.invalidateQueries({queryKey:["sync","status"]})},onError:()=>toast.push({kind:"error",title:"Не удалось поставить полную сверку",body:"Проверьте активную политику и повторите."})});
 const resolve=useMutation({mutationFn:async(drift:Drift)=>api.resolveSyncDrift({driftId:drift.id,idempotencyKey:crypto.randomUUID(),body:{action:"ignore",expected_version:drift.version}}),onSuccess:async()=>{toast.push({kind:"success",title:"Расхождение обработано"});setSelectedDrift(null);await cache.invalidateQueries({queryKey:["sync","status"]})}});
 return <Page eyebrow="Интеграции" title="Синхронизация" description="Политики обмена, запуски сверки и расхождения внешних каналов текущего workspace.">{query.isPending?<LoadingBlock/>:query.isError?<ErrorBlock retry={()=>void query.refetch()}>Не удалось загрузить состояние синхронизации.</ErrorBlock>:<>
 <div className="hero-grid"><article className="metric-card primary-metric"><span>Активные политики</span><strong>{query.data.summary.enabled_policies}</strong><small>правила обмена</small></article><article className="metric-card"><span>Запуски сейчас</span><strong>{query.data.summary.active_runs}</strong><small>выполняются или возобновляются</small></article><article className="metric-card"><span>Открытые расхождения</span><strong>{query.data.summary.open_drifts}</strong><small>требуют решения</small></article></div>
 <section className="panel settings-card"><div className="section-heading"><div><h2>Первоначальный импорт и расписание</h2><p>Сначала выполните безопасный пробный запуск, затем запустите первоначальный импорт и задайте период автоматической синхронизации.</p></div></div>{accounts.isPending?<LoadingBlock/>:accounts.isError?<ErrorBlock retry={()=>void accounts.refetch()}>Не удалось загрузить кабинеты.</ErrorBlock>:accounts.data.length===0?<EmptyState title="Нет подключённых кабинетов" text="Добавьте кабинет в разделе «Интеграции», чтобы настроить импорт и расписание."/>:<div className="bootstrap-account-grid">{accounts.data.map(value=><article className="bootstrap-account-card" key={value.id}><div className="bootstrap-account-heading"><div><strong>{value.connector_id}</strong><small className="mono">{value.id}</small></div><StatusBadge value={value.health_status}/></div><ConnectorBootstrapControls account={value}/></article>)}</div>}</section>
 <section className="panel settings-card"><div className="section-heading"><div><h2>Добавить политику</h2><p>Выберите кабинет, данные и безопасное направление обмена.</p></div></div>{accounts.isPending?<LoadingBlock/>:accounts.isError?<ErrorBlock retry={()=>void accounts.refetch()}>Не удалось загрузить кабинеты.</ErrorBlock>:accounts.data.length===0?<EmptyState title="Сначала добавьте кабинет" text="Кабинеты настраиваются в разделе «Интеграции»."/>:<div className="settings-form"><label className="field"><span>Кабинет</span><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Выберите кабинет</option>{accounts.data.map(v=><option key={v.id} value={v.id}>{v.id} · {v.connector_id}</option>)}</select></label><label className="field"><span>Сущность</span><select value={entity} onChange={e=>setEntity(e.target.value)}>{Object.entries(entityLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>Направление</span><select value={direction} onChange={e=>setDirection(e.target.value)}>{Object.entries(directionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span>Источник истины</span><select value={source} onChange={e=>setSource(e.target.value)}>{Object.entries(sourceLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="button primary" disabled={!account||create.isPending} onClick={()=>create.mutate()}>{create.isPending?"Добавляем…":"Добавить политику"}</button>{create.isError?<ErrorBlock>Не удалось добавить политику. Проверьте, что для этого кабинета и сущности ещё нет правила.</ErrorBlock>:null}</div>}</section>
 <section><div className="section-heading"><div><h2>Политики</h2><p>Изменяйте направление и источник истины, временно отключайте правила или запускайте их вручную.</p></div></div>{query.data.policies.length===0?<EmptyState title="Политики синхронизации не настроены" text="Создайте первое правило в форме выше."/>:<div className="table-wrap"><table><thead><tr><th>Кабинет</th><th>Сущность</th><th>Направление</th><th>Источник истины</th><th>Состояние</th><th>Действия</th></tr></thead><tbody>{query.data.policies.map(v=><tr key={v.id}><td className="mono">{v.connector_account_id}</td><td>{entityLabels[v.entity_type]??v.entity_type}</td><td><select disabled={update.isPending} value={v.direction} onChange={e=>update.mutate({policy:v,changes:{direction:e.target.value}})}>{Object.entries(directionLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td><select disabled={update.isPending} value={v.source_of_truth} onChange={e=>update.mutate({policy:v,changes:{source_of_truth:e.target.value}})}>{Object.entries(sourceLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></td><td><StatusBadge value={v.enabled?"active":"disabled"}/></td><td><div className="integration-actions"><button type="button" className="button ghost" disabled={update.isPending} onClick={()=>update.mutate({policy:v,changes:{enabled:!v.enabled}})}>{v.enabled?"Отключить":"Включить"}</button><button type="button" className="button primary" disabled={!v.enabled||run.isPending} onClick={()=>run.mutate(v)}>Запустить</button><button type="button" className="button ghost" disabled={!v.enabled||reconcile.isPending} onClick={()=>reconcile.mutate(v)}>Полная сверка</button></div></td></tr>)}</tbody></table>{update.isError?<p className="error-text">Не удалось изменить политику: обновите страницу и повторите.</p>:null}{run.isSuccess||reconcile.isSuccess?<p className="success-text">Операция сверки поставлена в очередь.</p>:null}</div>}</section>
 {query.data.runs.length>0?<section><div className="section-heading"><div><h2>Последние запуски</h2></div></div><div className="table-wrap"><table><thead><tr><th>Начало</th><th>Режим</th><th>Статус</th><th>Проверено</th><th>Расхождений</th></tr></thead><tbody>{query.data.runs.map(v=><tr key={v.id}><td>{new Date(v.started_at).toLocaleString("ru-RU")}</td><td>{labelFor(v.mode,syncModeLabels)}</td><td><StatusBadge value={v.status}/></td><td>{v.scanned_count}</td><td>{v.drift_count}</td></tr>)}</tbody></table></div></section>:null}
 {query.data.drifts.length>0?<section><div className="section-heading"><div><h2>Расхождения</h2><p>Откройте drift, сравните локальное и внешнее состояние и только затем выберите действие.</p></div></div><DataTable rows={query.data.drifts} rowKey={v=>v.id} searchPlaceholder="Тип, сущность, статус…" onOpen={setSelectedDrift} columns={[{key:"detected",label:"Обнаружено",value:v=>v.detected_at,render:v=>new Date(v.detected_at).toLocaleString("ru-RU")},{key:"kind",label:"Тип",value:v=>v.kind,render:v=><StatusBadge value={v.kind}/>},{key:"local",label:"Локальная сущность",value:v=>v.local_entity_id||"—",render:v=><span className="mono">{v.local_entity_id||"—"}</span>},{key:"remote",label:"Внешняя сущность",value:v=>v.remote_id||"—",render:v=><span className="mono">{v.remote_id||"—"}</span>},{key:"status",label:"Статус",value:v=>v.status,render:v=><StatusBadge value={v.status}/>} ]}/></section>:null}
 <Drawer open={!!selectedDrift} title="Расхождение синхронизации" subtitle={selectedDrift?.id} onClose={()=>setSelectedDrift(null)}>{selectedDrift?<><div className="drawer-kpis"><div><small>Тип</small><StatusBadge value={selectedDrift.kind}/></div><div><small>Статус</small><StatusBadge value={selectedDrift.status}/></div><div><small>Рекомендация</small><StatusBadge value={labelFor(selectedDrift.recommended_action||"manual",syncActionLabels)}/></div></div><section className="drawer-section"><h3>Сравнение состояния</h3><div className="compare-grid"><article><small>TORGNEXA</small><strong>{selectedDrift.local_status||"—"}</strong><span className="mono">{selectedDrift.local_entity_id||"—"}</span></article><article><small>Внешний канал</small><strong>{selectedDrift.remote_status||"—"}</strong><span className="mono">{selectedDrift.remote_id||"—"}</span></article></div></section>{selectedDrift.status==="open"?<section className="drawer-section action-zone"><h3>Решение оператора</h3><p>Игнорирование закрывает расхождение и сохраняется в аудите. Автоматическое исправление выполняется только по настроенной политике.</p><button type="button" className="button danger" disabled={resolve.isPending} onClick={()=>resolve.mutate(selectedDrift)}>{resolve.isPending?"Сохраняем…":"Игнорировать расхождение"}</button></section>:null}</>:null}</Drawer>
 </>}</Page>
}
