import {useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useApi} from "../api/ApiProvider";
import {ErrorBlock,LoadingBlock} from "../components/ApiState";
import {EmptyState} from "../components/EmptyState";
import {StatusBadge} from "../components/StatusBadge";
import {useToast} from "../components/Toast";
import {Page} from "./Page";

type Workflow={id:string;name:string;description?:string;status:string;current_version:number;version:number;updated_at:string};
type Run={id:string;workflow_id:string;workflow_version:number;status:string;attempt_count:number;available_at:string;last_error_code?:string;version:number};
type Step={id:string;run_id:string;node_id:string;status:string;attempt_count:number;output_digest?:string;error_code?:string;started_at?:string;completed_at?:string;version:number};
type Evidence={id:string;run_id:string;node_id:string;attempt:number;outcome:string;output_digest?:string;error_code?:string;observed_at:string};
const statusLabels:Record<string,string>={draft:"Черновик",published:"Опубликовано",paused:"На паузе",archived:"Архив"};
const runLabels:Record<string,string>={queued:"В очереди",running:"Выполняется",waiting_approval:"Ждёт согласования",waiting_retry:"Ждёт повтора",completed:"Завершено",failed:"Ошибка",cancelled:"Отменено"};
const actionCatalog=[
 {id:"notification.create",title:"Уведомление",risk:"write_safe",description:"Создать уведомление в центре активности"},
 {id:"reconciliation.run",title:"Сверка",risk:"write_safe",description:"Поставить reconciliation в очередь"},
 {id:"approval.request",title:"Согласование",risk:"write_sensitive",description:"Передать действие в Task-017"},
 {id:"sync.dry_run",title:"Предпросмотр",risk:"read",description:"Безопасный dry-run без внешней записи"}
];
function list(v:unknown):Workflow[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid workflows");return root.items as Workflow[]}
function runs(v:unknown):Run[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid workflow runs");return root.items as Run[]}
function steps(v:unknown):Step[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid workflow steps");return root.items as Step[]}
function evidence(v:unknown):Evidence[]{const root=v as {items?:unknown};if(!root||!Array.isArray(root.items))throw new Error("invalid workflow evidence");return root.items as Evidence[]}
function definition(name:string,eventType:string,action:string,title:string,body:string){return {name,trigger:{kind:"event",event_type:eventType,enabled:false},nodes:[{id:"condition",kind:"condition",config:{result:true}},{id:"action",kind:"action",action,config:action==="notification.create"?{recipient_id:"operator",dedupe_key:"workflow.operator",severity:"info",title,body,category:"commerce"}:{mode:"safe"}}],edges:[{from:"condition",to:"action",condition:"always"}]}}

export function WorkflowsPage(){
 const api=useApi(),cache=useQueryClient(),toast=useToast();
 const [name,setName]=useState("Уведомить оператора о событии");
 const [eventType,setEventType]=useState("commerce.catalog.product_changed.v1");
 const [action,setAction]=useState("notification.create");
 const [title,setTitle]=useState("Изменение товара");
 const [body,setBody]=useState("В каталоге произошло изменение.");
 const [selected,setSelected]=useState<Workflow|null>(null);
 const [selectedRun,setSelectedRun]=useState<Run|null>(null);
 const workflows=useQuery({queryKey:["workflows"],queryFn:async()=>list((await api.listWorkflows({limit:100})).body),staleTime:10_000});
 const workflowRuns=useQuery({queryKey:["workflow-runs"],queryFn:async()=>runs((await api.listWorkflowRuns({limit:100})).body),refetchInterval:15_000});
 const workflowSteps=useQuery({queryKey:["workflow-run-steps",selectedRun?.id],enabled:!!selectedRun,queryFn:async()=>steps((await api.listWorkflowRunSteps({runId:selectedRun!.id,limit:200})).body)});
 const workflowEvidence=useQuery({queryKey:["workflow-run-evidence",selectedRun?.id],enabled:!!selectedRun,queryFn:async()=>evidence((await api.listWorkflowRunEvidence({runId:selectedRun!.id,limit:200})).body)});
 const currentDefinition=useMemo(()=>definition(name,eventType,action,title,body),[name,eventType,action,title,body]);
 const refresh=async()=>Promise.all([cache.invalidateQueries({queryKey:["workflows"]}),cache.invalidateQueries({queryKey:["workflow-runs"]})]);
 const validate=useMutation({mutationFn:()=>api.validateWorkflow({body:currentDefinition}),onSuccess:()=>toast.push({kind:"success",title:"Схема корректна",body:"Граф ацикличен, план собран детерминированно."}),onError:()=>toast.push({kind:"error",title:"Проверка не пройдена",body:"Проверьте событие, узлы и ограничения."})});
 const create=useMutation({mutationFn:()=>api.createWorkflow({idempotencyKey:crypto.randomUUID(),body:{definition:currentDefinition}}),onSuccess:async(response)=>{const item=response.body as Workflow;setSelected(item);toast.push({kind:"success",title:"Черновик создан"});await refresh()},onError:()=>toast.push({kind:"error",title:"Не удалось создать черновик"})});
 const publish=useMutation({mutationFn:()=>{if(!selected)throw new Error("select workflow");return api.publishWorkflow({idempotencyKey:crypto.randomUUID(),body:{workflow_id:selected.id,expected_version:selected.version,definition:currentDefinition}})},onSuccess:async()=>{toast.push({kind:"success",title:"Автоматизация опубликована"});await refresh()},onError:()=>toast.push({kind:"error",title:"Публикация отклонена",body:"Обновите версию и повторите проверку."})});
 const run=useMutation({mutationFn:()=>{if(!selected)throw new Error("select workflow");return api.runWorkflow({idempotencyKey:crypto.randomUUID(),body:{workflow_id:selected.id,workflow_version:selected.current_version,trigger_ref:"ui.test-run"}})},onSuccess:async()=>{toast.push({kind:"success",title:"Тестовый запуск поставлен в очередь"});await refresh()},onError:()=>toast.push({kind:"error",title:"Не удалось поставить запуск"})});
 const retry=useMutation({mutationFn:(item:Run)=>api.retryWorkflowRun({idempotencyKey:crypto.randomUUID(),body:{run_id:item.id}}),onSuccess:refresh});
 const cancel=useMutation({mutationFn:(item:Run)=>api.cancelWorkflowRun({idempotencyKey:crypto.randomUUID(),body:{run_id:item.id,expected_version:item.version}}),onSuccess:refresh});
 return <Page eyebrow="Операции" title="Автоматизации" description="Декларативные цепочки событий и действий с проверкой, согласованиями и наблюдаемым запуском.">
  <section className="panel settings-card workflow-builder"><div className="section-heading"><div><h2>Конструктор</h2><p>Схема сохраняет только типизированные поля и не выполняет код, SQL или произвольный HTTP.</p></div><StatusBadge value="bounded"/></div>
   <div className="workflow-builder-grid"><div className="workflow-form"><label className="field"><span>Название</span><input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Событие-триггер</span><input value={eventType} maxLength={160} onChange={e=>setEventType(e.target.value)}/></label><label className="field"><span>Действие</span><select value={action} onChange={e=>setAction(e.target.value)}>{actionCatalog.map(item=><option key={item.id} value={item.id}>{item.title} · {item.risk}</option>)}</select></label>{action==="notification.create"?<><label className="field"><span>Заголовок уведомления</span><input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>Текст уведомления</span><textarea value={body} maxLength={4000} rows={3} onChange={e=>setBody(e.target.value)}/></label></>:null}<div className="button-row"><button className="button ghost" disabled={validate.isPending} onClick={()=>validate.mutate()}>{validate.isPending?"Проверяем…":"Проверить схему"}</button><button className="button primary" disabled={create.isPending||!name||!eventType} onClick={()=>create.mutate()}>{create.isPending?"Сохраняем…":"Создать черновик"}</button></div></div>
   <div className="workflow-canvas" aria-label="Предпросмотр графа"><div className="workflow-node trigger"><span>1</span><div><strong>Событие</strong><small>{eventType||"укажите event type"}</small></div></div><div className="workflow-connector"/><div className="workflow-node condition"><span>2</span><div><strong>Условие</strong><small>status = active</small></div></div><div className="workflow-connector"/><div className="workflow-node action"><span>3</span><div><strong>{actionCatalog.find(item=>item.id===action)?.title}</strong><small>{action}</small></div></div><p className="workflow-canvas-note">Лимит v1: до 64 узлов и 128 связей, только allowlist действий.</p></div></div>
  </section>
  <section><div className="section-heading"><div><h2>Черновики и версии</h2><p>Публикация создаёт immutable версию. Запуск доступен после выбора workflow.</p></div><div className="button-row">{selected?<><button className="button ghost" disabled={publish.isPending} onClick={()=>publish.mutate()}>Опубликовать v{selected.current_version+1}</button><button className="button primary" disabled={run.isPending||selected.status!=="published"} onClick={()=>run.mutate()}>Тестовый запуск</button></>:null}</div></div>{workflows.isPending?<LoadingBlock/>:workflows.isError?<ErrorBlock retry={()=>void workflows.refetch()}>Не удалось загрузить автоматизации.</ErrorBlock>:workflows.data.length===0?<EmptyState title="Автоматизаций пока нет" text="Соберите схему и сохраните первый черновик."/>:<div className="table-wrap"><table><thead><tr><th>Название</th><th>Состояние</th><th>Версия</th><th>Изменено</th><th></th></tr></thead><tbody>{workflows.data.map(item=><tr key={item.id} className={selected?.id===item.id?"selected-row":undefined}><td><button className="table-link" onClick={()=>setSelected(item)}>{item.name}</button><br/><span className="mono">{item.id}</span></td><td><StatusBadge value={statusLabels[item.status]??item.status}/></td><td>v{item.current_version} · rev {item.version}</td><td>{new Date(item.updated_at).toLocaleString("ru-RU")}</td><td>{selected?.id===item.id?<span className="muted">Выбрано</span>:<button className="button ghost" onClick={()=>setSelected(item)}>Открыть</button>}</td></tr>)}</tbody></table></div>}</section>
  <section><div className="section-heading"><div><h2>Последние запуски</h2><p>Payload не отображается: только идентификаторы, статус, попытки и машинный код ошибки.</p></div></div>{workflowRuns.isPending?<LoadingBlock/>:workflowRuns.isError?<ErrorBlock retry={()=>void workflowRuns.refetch()}>Не удалось загрузить запуски.</ErrorBlock>:workflowRuns.data.length===0?<EmptyState title="Запусков пока нет" text="Опубликуйте workflow и выполните тестовый запуск."/>:<div className="table-wrap"><table><thead><tr><th>Запуск</th><th>Workflow</th><th>Состояние</th><th>Попытки</th><th>Когда</th><th>Восстановление</th></tr></thead><tbody>{workflowRuns.data.map(item=><tr key={item.id}><td><button className="table-link mono" onClick={()=>setSelectedRun(item)}>{item.id}</button></td><td>{item.workflow_id}<br/><span className="muted">v{item.workflow_version}</span></td><td><StatusBadge value={runLabels[item.status]??item.status}/>{item.last_error_code?<small className="error-text">{item.last_error_code}</small>:null}</td><td>{item.attempt_count}</td><td>{new Date(item.available_at).toLocaleString("ru-RU")}</td><td><div className="button-row">{item.status==="failed"||item.status==="cancelled"?<button className="button ghost" disabled={retry.isPending} onClick={()=>retry.mutate(item)}>Повторить</button>:null}{item.status!=="completed"&&item.status!=="failed"&&item.status!=="cancelled"?<button className="button danger" disabled={cancel.isPending} onClick={()=>cancel.mutate(item)}>Отменить</button>:null}</div></td></tr>)}</tbody></table></div>}</section>
  {selectedRun?<section className="panel workflow-timeline"><div className="section-heading"><div><h2>Хронология запуска</h2><p className="mono">{selectedRun.id} · {selectedRun.workflow_id} · версия {selectedRun.workflow_version}</p></div><button className="button ghost" onClick={()=>setSelectedRun(null)}>Закрыть</button></div>{workflowSteps.isPending||workflowEvidence.isPending?<LoadingBlock/>:workflowSteps.isError||workflowEvidence.isError?<ErrorBlock retry={()=>{void workflowSteps.refetch();void workflowEvidence.refetch()}}>Не удалось загрузить хронологию.</ErrorBlock>:<><h3>Шаги</h3>{workflowSteps.data.length===0?<p className="muted">Шаги ещё не созданы worker.</p>:<div className="table-wrap"><table><thead><tr><th>Узел</th><th>Состояние</th><th>Попытки</th><th>Код</th><th>Завершён</th></tr></thead><tbody>{workflowSteps.data.map(step=><tr key={step.id}><td className="mono">{step.node_id}</td><td><StatusBadge value={runLabels[step.status]??step.status}/></td><td>{step.attempt_count}</td><td className="mono">{step.error_code||"—"}</td><td>{step.completed_at?new Date(step.completed_at).toLocaleString("ru-RU"):"—"}</td></tr>)}</tbody></table></div>}<h3>Свидетельства</h3>{workflowEvidence.data.length===0?<p className="muted">Свидетельств ещё нет.</p>:<div className="table-wrap"><table><thead><tr><th>Узел</th><th>Попытка</th><th>Результат</th><th>Код</th><th>Наблюдено</th></tr></thead><tbody>{workflowEvidence.data.map(item=><tr key={item.id}><td className="mono">{item.node_id}</td><td>{item.attempt}</td><td><StatusBadge value={runLabels[item.outcome]??item.outcome}/></td><td className="mono">{item.error_code||"—"}</td><td>{new Date(item.observed_at).toLocaleString("ru-RU")}</td></tr>)}</tbody></table></div>}</>}</section>:null}
 </Page>
}
