import {useEffect,useState} from "react";
import {useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {useApi} from "../../api/ApiProvider";
import {decodeProductPage} from "../../api/decoders";
import type {ProductPrice} from "../../api/decoders";
import {ErrorBlock, LoadingBlock} from "../../components/ApiState";
import {StatusBadge} from "../../components/StatusBadge";
import {ServerDataGrid} from "../../components/ServerDataGrid";
import {navigate} from "../../shell/useLocationPath";
import {Drawer} from "../../components/Drawer";
import {useToast} from "../../components/Toast";
import {Icon} from "../../components/Icon";
import {ProductImage} from "../../components/ProductImage";
import {LineageTimeline} from "../../components/LineageTimeline";

type R={body:any;headers:Headers}; type Client={listProducts(x?:object):Promise<R>;getProduct(x:object):Promise<R>;createProduct(x:object):Promise<R>;updateProduct(x:object):Promise<R>;createProductOffer(x:object):Promise<R>;updateProductOffer(x:object):Promise<R>;createOfferPrice(x:object):Promise<R>;updateOfferPrice(x:object):Promise<R>;listCatalogCategories():Promise<R>;createCatalogCategory(x:object):Promise<R>;assignProductCategory(x:object):Promise<R>;createProductImage(x:object):Promise<R>;updateProductImage(x:object):Promise<R>;deleteProductImage(x:object):Promise<R>;createUpload(x:object):Promise<R>;getUpload(x:object):Promise<R>;
getUploadContent(x:object):Promise<R>};
type Detail={product:any;offers:any[];categories:any[];images:any[]};
const val=(o:any,k:string)=>o?.[k]??o?.[k[0].toUpperCase()+k.slice(1)]??"";
const normalized=(b:any):Detail=>({product:{id:val(b.product,"id"),code:val(b.product,"code"),title:val(b.product,"title"),description:val(b.product,"description"),status:val(b.product,"status"),version:val(b.product,"version")},offers:b.offers??[],categories:(b.categories??[]).map((x:any)=>({id:val(x,"id"),name:val(x,"name"),code:val(x,"code")})),images:(b.images??[]).map((x:any)=>({id:val(x,"id"),url:val(x,"uRL")||val(x,"url"),alt_text:val(x,"altText")||x.alt_text,position:val(x,"position"),version:val(x,"version")}))});
function ProductListThumbnail({api,src}:{api:Client;src?:string}){return src?<ProductImage api={api} src={src} alt="" className="catalog-product-thumbnail"/>:<span className="catalog-product-thumbnail catalog-product-thumbnail-empty" aria-hidden="true"><Icon name="catalog" size={18}/></span>}
function productMoney(price?:ProductPrice){if(!price)return "—";try{return new Intl.NumberFormat("ru-RU",{style:"currency",currency:price.currency}).format(price.minor_units/100)}catch{return `${(price.minor_units/100).toLocaleString("ru-RU")} ${price.currency}`}}

async function uploadAndAttachImage(api:Client,product:string,file:File,alt:string,position:number){
  const bytes=new Uint8Array(await file.arrayBuffer());
  let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);
  const created=(await api.createUpload({idempotencyKey:crypto.randomUUID(),body:{filename:file.name,declared_media_type:file.type||undefined,content_base64:btoa(binary)}})).body as {id?:unknown};
  if(typeof created.id!=="string")throw new Error("invalid upload response");
  for(let attempt=0;;attempt++){
    if(attempt>=30)throw new Error("upload scan timed out");
    const uploadStatus=(await api.getUpload({uploadId:created.id})).body as {state?:unknown;State?:unknown};
    const state=String(uploadStatus.state??uploadStatus.State??"").toLowerCase();
    if(state==="released")break;
    if(state==="rejected")throw new Error("upload rejected by security scan");
    await new Promise(resolve=>window.setTimeout(resolve,1000));
  }
  await api.createProductImage({productId:product,body:{upload_id:created.id,alt_text:alt,position}});
}

export function ProductList({initialId}:{initialId?:string}) {
  const api=useApi() as unknown as Client,qc=useQueryClient(),toast=useToast();
  const [id,setId]=useState(initialId??""),[creating,setCreating]=useState(false),[q,setQ]=useState(""),[status,setStatus]=useState(""),[cursor,setCursor]=useState(""),[history,setHistory]=useState<string[]>([]);
  const list=useQuery({queryKey:["products","catalog",q,status,cursor],queryFn:async()=>decodeProductPage((await api.listProducts({limit:25,q:q||undefined,status:status||undefined,cursor:cursor||undefined})).body)});
  const detail=useQuery({queryKey:["product",id],enabled:!!id,queryFn:async()=>normalized((await api.getProduct({productId:id})).body)});
  const refresh=async()=>{await qc.invalidateQueries({queryKey:["products"]});if(id)await qc.invalidateQueries({queryKey:["product",id]})};
  const changeQuery=(value:string)=>{setQ(value);setCursor("");setHistory([])};
  const changeStatus=(value:string)=>{setStatus(value);setCursor("");setHistory([])};
  if(list.isPending&&!list.data)return <LoadingBlock/>;
  if(list.isError&&!list.data)return <ErrorBlock retry={()=>void list.refetch()}>Не удалось загрузить каталог.</ErrorBlock>;
  const page=list.data??{items:[]};
  const columns=[
    {key:"product",label:"Товар",render:(x:any)=><span className="catalog-product-cell"><ProductListThumbnail api={api} src={x.image_url}/><span className="catalog-product-copy"><strong>{x.title}</strong><small className="mono">{x.code}</small></span></span>},
    {key:"description",label:"Описание",render:(x:any)=><span className="catalog-table-description" title={x.description||undefined}>{x.description||"—"}</span>},
    {key:"price",label:"Цена",render:(x:any)=><strong className="catalog-table-price">{productMoney(x.price)}</strong>,align:"end" as const},
    {key:"status",label:"Статус",render:(x:any)=><StatusBadge value={x.status}/>},
    {key:"updated",label:"Обновлён",render:(x:any)=><time>{new Date(x.updated_at).toLocaleString("ru-RU")}</time>},
  ];
  return <>
    <div className="list-heading-actions"><span>Каталог · до 25 строк на страницу</span><div className="button-row"><button className="button primary" onClick={()=>{setId("");setCreating(true)}}>Создать товар</button></div></div>
    <ServerDataGrid rows={page.items as any[]} columns={columns} rowKey={x=>x.id} query={q} onQuery={changeQuery} filter={status} filterOptions={[{value:"draft",label:"Черновики"},{value:"active",label:"Активные"},{value:"archived",label:"Архив"}]} onFilter={changeStatus} loading={list.isFetching} hasPrevious={history.length>0} hasNext={!!page.next_cursor} onPrevious={()=>{const prev=[...history];setCursor(prev.pop()??"");setHistory(prev)}} onNext={()=>{if(page.next_cursor){setHistory(v=>[...v,cursor]);setCursor(page.next_cursor)}}} onOpen={x=>{setCreating(false);setId(x.id);navigate(`/catalog/${encodeURIComponent(x.id)}`)}}/>
    <Drawer open={creating||!!id} title={creating?"Новый товар":detail.data?.product.title??"Карточка товара"} subtitle={creating?"Создание канонической карточки":detail.data?.product.code} onClose={()=>{setCreating(false);setId("");navigate("/catalog")}}><>{creating?<Create api={api} done={async x=>{toast.push({kind:"success",title:"Товар создан"});setCreating(false);await refresh();setId(x);navigate(`/catalog/${encodeURIComponent(x)}`)}}/>:!id?null:detail.isPending?<LoadingBlock/>:detail.isError?<ErrorBlock retry={()=>void detail.refetch()}>Не удалось открыть карточку товара.</ErrorBlock>:<Card api={api} data={detail.data!} refresh={refresh}/>}</></Drawer>
  </>;
}
function Create({api,done}:{api:Client;done:(id:string)=>void}){const [tab,setTab]=useState("main"),[code,setCode]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[imageURL,setImageURL]=useState(""),[imageAlt,setImageAlt]=useState(""),[imageFile,setImageFile]=useState<File|null>(null),[filePreview,setFilePreview]=useState("");useEffect(()=>{if(!imageFile){setFilePreview("");return}const preview=URL.createObjectURL(imageFile);setFilePreview(preview);return()=>URL.revokeObjectURL(preview)},[imageFile]);const m=useMutation({mutationFn:async()=>{const created=await api.createProduct({body:{code,title,description}}),productID=val(created.body,"id");if(!productID)throw new Error("created product id is missing");if(imageFile)await uploadAndAttachImage(api,productID,imageFile,imageAlt.trim(),0);else if(imageURL.trim())await api.createProductImage({productId:productID,body:{url:imageURL.trim(),alt_text:imageAlt.trim(),position:0}});return productID},onSuccess:done});return <form className="product-create-card" onSubmit={e=>{e.preventDefault();m.mutate()}}>
 <header className="product-create-card-header"><div className="product-create-card-identity"><span className="product-create-card-mark"><Icon name="catalog"/></span><div className="product-create-card-copy"><span className="eyebrow">Карточка товара</span><h3>{title.trim()||"Новый товар"}</h3><small>{code.trim()||"Код будет задан при сохранении"}</small></div></div><span className="status status-draft">Черновик</span></header>
 <nav className="product-create-card-tabs" role="tablist" aria-label="Разделы карточки товара">{[["main","Основные данные"],["offers","Предложения и цены"],["categories","Категории"]].map(x=><button type="button" role="tab" aria-selected={tab===x[0]} key={x[0]} className={`product-create-card-tab${tab===x[0]?" active":""}`} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>
 {tab==="main"&&<section className="product-create-card-body"><div className="product-create-image-section product-create-image-first"><div className="product-create-section-heading"><div><p className="eyebrow">Первый шаг</p><h3>Главное изображение товара</h3></div><span className="product-create-section-caption">Файл или HTTPS-ссылка</span></div><div className="product-create-image-form"><label className="field product-create-image-file"><span>Загрузить файл</span><input type="file" accept="image/*" onChange={e=>{const target=e.target as unknown as HTMLInputElement;const file=target.files?.[0]??null;setImageFile(file);if(file)setImageURL("");target.value=""}}/></label><label className="field product-create-image-url"><span>Или ссылка на изображение</span><input type="url" placeholder="https://…" value={imageURL} onChange={e=>{setImageURL(e.target.value);if(e.target.value.trim())setImageFile(null)}}/></label><label className="field"><span>Описание изображения</span><input placeholder="Например, вид спереди" value={imageAlt} onChange={e=>setImageAlt(e.target.value)}/></label>{(filePreview||imageURL.trim())?<div className="product-create-image-preview"><img src={filePreview||imageURL} alt={imageAlt||"Предпросмотр изображения"}/><small>{imageFile?"Файл будет проверен и прикреплён к карточке после сохранения.":"Изображение будет прикреплено к карточке после сохранения."}</small></div>:<div className="product-create-image-empty"><Icon name="catalog"/><span>Выберите изображение или добавьте HTTPS-ссылку — здесь появится предпросмотр.</span></div>}</div></div><div className="product-create-section-heading"><div><p className="eyebrow">Основное</p><h3>Идентификация товара</h3></div><span className="product-create-section-caption">Обязательны код и название</span></div><div className="product-create-form"><Field label="Код" value={code} set={setCode}/><Field label="Название" value={title} set={setTitle}/><Field className="product-create-description" label="Описание" value={description} set={setDescription} multiline required={false}/></div></section>}
 {tab==="offers"&&<CreateTabPlaceholder title="Предложения и цены" text="Сначала сохраните карточку, затем добавьте SKU, цены и остатки."/>}{tab==="categories"&&<CreateTabPlaceholder title="Категории" text="Сначала сохраните карточку, затем назначьте ей категорию."/>}
 <footer className="product-create-card-footer"><p>{imageFile||imageURL.trim()?"Изображение будет проверено и привязано к карточке автоматически.":"Код, название и изображение добавляются во вкладке «Основные данные»."}</p><div className="account-actions"><button type="submit" className="button primary" disabled={m.isPending}>{m.isPending?"Создаём карточку…":"Создать карточку"}</button>{m.isError&&<span className="error-text" role="alert">Не удалось создать карточку или добавить изображение.</span>}</div></footer>
 </form>}
function CreateTabPlaceholder({title,text}:{title:string;text:string}){return <section className="product-create-tab-placeholder"><Icon name="catalog"/><div><h3>{title}</h3><p>{text}</p></div></section>}
function Card({api,data,refresh}:{api:Client;data:Detail;refresh:()=>Promise<void>}){const p=data.product,[tab,setTab]=useState("main"),[title,setTitle]=useState(p.title),[description,setDescription]=useState(p.description),primaryImage=data.images[0];const save=useMutation({mutationFn:(body:object)=>api.updateProduct({productId:p.id,body}),onSuccess:refresh});return <><div className="catalog-card-head"><div><span className="mono">{p.code}</span><h2>{p.title}</h2><StatusBadge value={p.status}/></div><select value={p.status} onChange={e=>save.mutate({version:p.version,status:e.target.value})}><option value="draft">Черновик</option><option value="active">Активен</option><option value="archived">Архив</option></select></div><div className="catalog-tabs">{[["main","Карточка"],["offers","Предложения и цены"],["categories","Категории"],["images","Изображения"]].map(x=><button type="button" key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>{tab==="main"&&<div className="catalog-main-layout"><section className="catalog-primary-image">{primaryImage?<ProductImage api={api} src={primaryImage.url} alt={primaryImage.alt_text||p.title}/>:<div className="catalog-primary-image-empty"><Icon name="catalog"/><span>Главное изображение ещё не добавлено.</span></div>}{primaryImage?.alt_text?<small>{primaryImage.alt_text}</small>:null}<button type="button" className="button ghost" onClick={()=>setTab("images")}>{primaryImage?"Изменить изображения":"Добавить изображение"}</button></section><form className="catalog-form" onSubmit={e=>{e.preventDefault();save.mutate({version:p.version,title,description})}}><Field label="Название" value={title} set={setTitle}/><Field label="Описание" value={description} set={setDescription}/><button className="button primary">Сохранить изменения</button></form></div>}{tab==="offers"&&<Offers api={api} product={p.id} items={data.offers} refresh={refresh}/>} {tab==="categories"&&<Categories api={api} product={p.id} assigned={data.categories} refresh={refresh}/>} {tab==="images"&&<Images api={api} product={p.id} items={data.images} refresh={refresh}/>}<LineageTimeline system="catalog" entityType="product" entityId={p.id}/></>}
function Field({label,value,set,className="",multiline=false,required=true}:{label:string;value:string;set:(x:string)=>void;className?:string;multiline?:boolean;required?:boolean}){return <label className={`field${className?` ${className}`:""}`}><span>{label}</span>{multiline?<textarea required={required} rows={4} value={value} onChange={e=>set(e.target.value)}/>:<input required={required} value={value} onChange={e=>set(e.target.value)}/>}</label>}
function Offers({api,product,items,refresh}:{api:Client;product:string;items:any[];refresh:()=>Promise<void>}){const [sku,setSku]=useState(""),[gtin,setGtin]=useState("");const add=useMutation({mutationFn:()=>api.createProductOffer({productId:product,body:{sku,gtin}}),onSuccess:refresh});return <div className="catalog-stack"><form className="catalog-inline" onSubmit={e=>{e.preventDefault();add.mutate()}}><input required placeholder="SKU" value={sku} onChange={e=>setSku(e.target.value)}/><input placeholder="GTIN" value={gtin} onChange={e=>setGtin(e.target.value)}/><button className="button primary">Добавить предложение</button></form>{add.isError?<ErrorBlock>Не удалось добавить предложение. Проверьте SKU и GTIN.</ErrorBlock>:null}{items.map(o=><Offer key={o.id} api={api} product={product} item={o} refresh={refresh}/>)}</div>}
function Offer({api,product,item,refresh}:{api:Client;product:string;item:any;refresh:()=>Promise<void>}){const [amount,setAmount]=useState(""),[kind,setKind]=useState("regular"),[gtin,setGtin]=useState(item.gtin??"");const add=useMutation({mutationFn:()=>api.createOfferPrice({productId:product,offerOrPriceId:item.id,body:{kind,currency:"RUB",minor_units:Math.round(Number(amount)*100)}}),onSuccess:refresh});const edit=useMutation({mutationFn:(body:object)=>api.updateProductOffer({productId:product,offerId:item.id,body}),onSuccess:refresh});return <article className="offer-card"><strong>{item.sku}</strong><form className="catalog-inline" onSubmit={e=>{e.preventDefault();edit.mutate({version:item.version,gtin})}}><input placeholder="GTIN" value={gtin} onChange={e=>setGtin(e.target.value)}/><button className="button ghost">Сохранить предложение</button><select value={item.status} onChange={e=>edit.mutate({version:item.version,status:e.target.value})}><option value="draft">Черновик</option><option value="active">Активно</option><option value="archived">Архив</option></select></form>{edit.isError?<ErrorBlock>Не удалось сохранить предложение. Обновите карточку и повторите.</ErrorBlock>:null}<div className="catalog-stack">{(item.prices??[]).map((x:any)=><Price key={x.id} api={api} product={product} price={x} refresh={refresh}/>)}</div><form className="catalog-inline" onSubmit={e=>{e.preventDefault();add.mutate()}}><select value={kind} onChange={e=>setKind(e.target.value)}><option value="regular">Цена</option><option value="compare_at">Старая цена</option><option value="cost">Себестоимость</option></select><input required type="number" min="0" step="0.01" placeholder="Сумма" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="button ghost">Добавить цену</button></form>{add.isError?<ErrorBlock>Не удалось добавить цену. Проверьте сумму и актуальность предложения.</ErrorBlock>:null}</article>}
function Price({api,product,price,refresh}:{api:Client;product:string;price:any;refresh:()=>Promise<void>}){const [amount,setAmount]=useState(String(price.minor_units/100));const edit=useMutation({mutationFn:()=>api.updateOfferPrice({productId:product,offerOrPriceId:price.id,body:{version:price.version,minor_units:Math.round(Number(amount)*100)}}),onSuccess:refresh});return <form className="catalog-inline" onSubmit={e=>{e.preventDefault();edit.mutate()}}><span className="chip">{price.kind} · {price.currency}</span><input required type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="button ghost">Изменить цену</button>{edit.isError?<ErrorBlock>Не удалось изменить цену. Обновите карточку товара и повторите.</ErrorBlock>:null}</form>}
function Categories({api,product,assigned,refresh}:{api:Client;product:string;assigned:any[];refresh:()=>Promise<void>}){const q=useQuery({queryKey:["catalog-categories"],queryFn:async()=>normalized({categories:(await api.listCatalogCategories()).body.items}).categories});const [selected,setSelected]=useState(""),[code,setCode]=useState(""),[name,setName]=useState("");const assign=useMutation({mutationFn:()=>api.assignProductCategory({productId:product,categoryId:selected}),onSuccess:refresh});const create=useMutation({mutationFn:()=>api.createCatalogCategory({body:{code,name}}),onSuccess:()=>q.refetch()});return <div className="catalog-stack"><div className="chip-list">{assigned.map(x=><span className="chip" key={x.id}>{x.name}</span>)}</div>{q.isError?<ErrorBlock retry={()=>void q.refetch()}>Не удалось загрузить категории.</ErrorBlock>:null}<form className="catalog-inline" onSubmit={e=>{e.preventDefault();assign.mutate()}}><select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите категорию</option>{q.data?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button primary">Назначить</button></form>{assign.isError?<ErrorBlock>Не удалось назначить категорию. Проверьте товар и выбранную категорию.</ErrorBlock>:null}<form className="catalog-inline" onSubmit={e=>{e.preventDefault();create.mutate()}}><input required placeholder="Код" value={code} onChange={e=>setCode(e.target.value)}/><input required placeholder="Название" value={name} onChange={e=>setName(e.target.value)}/><button className="button ghost">Создать категорию</button></form>{create.isError?<ErrorBlock>Не удалось создать категорию. Проверьте код и название.</ErrorBlock>:null}</div>}
function Images({api,product,items,refresh}:{api:Client;product:string;items:any[];refresh:()=>Promise<void>}){
 const toast=useToast();
 const [url,setUrl]=useState(""),[alt,setAlt]=useState(""),[uploading,setUploading]=useState(false);
 const addByUrl=useMutation({mutationFn:()=>api.createProductImage({productId:product,body:{url,alt_text:alt,position:items.length}}),onSuccess:async()=>{setUrl("");setAlt("");await refresh()},onError:()=>toast.push({kind:"error",title:"Не удалось добавить изображение",body:"Проверьте, что ссылка начинается с https://."})});
 const uploadFile=useMutation({mutationFn:(file:File)=>{setUploading(true);return uploadAndAttachImage(api,product,file,alt,items.length)},onSuccess:async()=>{setAlt("");setUploading(false);await refresh()},onError:()=>{setUploading(false);toast.push({kind:"error",title:"Не удалось загрузить изображение",body:"Файл отклонён проверкой безопасности или превышен предел размера."})}});
 return <div className="catalog-stack">
  <form className="catalog-inline" onSubmit={e=>{e.preventDefault();addByUrl.mutate()}}>
   <input type="url" placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/>
   <input placeholder="Описание" value={alt} onChange={e=>setAlt(e.target.value)}/>
   <button className="button primary" disabled={!url||addByUrl.isPending}>Добавить по ссылке</button>
  </form>
  <label className="catalog-inline">
   <input type="file" accept="image/*" disabled={uploading} onChange={e=>{const target=e.target as unknown as HTMLInputElement;const file=target.files?.[0];if(file)uploadFile.mutate(file);target.value=""}}/>
   {uploading?<small>Загружаем и проверяем файл…</small>:null}
  </label>
  <div className="image-grid">{items.map((x,index)=><ImageEditor key={x.id} api={api} product={product} item={x} index={index} refresh={refresh}/>)}</div>
  <small>Ссылка должна быть HTTPS. Загруженный файл сначала проходит проверку безопасности — это может занять несколько секунд, прежде чем он появится на карточке.</small>
 </div>
}

function ImageEditor({api,product,item,index,refresh}:{api:Client;product:string;item:any;index:number;refresh:()=>Promise<void>}){
 const toast=useToast();
 const [alt,setAlt]=useState(String(item.alt_text??"")),[position,setPosition]=useState(String(item.position??index));
 const save=useMutation({mutationFn:(nextPosition?:number)=>{const uploadMatch=String(item.url).match(/^\/api\/v1\/uploads\/(upl_[0-9a-f]{32})\/content$/);const imageRef=uploadMatch?{upload_id:uploadMatch[1]}:{url:item.url};return api.updateProductImage({productId:product,imageId:item.id,idempotencyKey:crypto.randomUUID(),body:{...imageRef,alt_text:alt.trim(),position:nextPosition??Number(position),version:item.version}})},onSuccess:()=>{void refresh()},onError:()=>toast.push({kind:"error",title:"Не удалось обновить изображение",body:"Изображение уже изменилось в другой сессии или указаны некорректные данные."})});
 const remove=useMutation({mutationFn:()=>api.deleteProductImage({productId:product,imageId:item.id,idempotencyKey:crypto.randomUUID()}),onSuccess:async()=>{await refresh();toast.push({kind:"success",title:"Изображение удалено"})},onError:()=>toast.push({kind:"error",title:"Не удалось удалить изображение",body:"Обновите карточку и повторите попытку."})});
 const deleteImage=()=>{if(window.confirm("Удалить это изображение из карточки товара?"))remove.mutate()};
 return <figure className="catalog-image-editor"><ProductImage api={api} src={item.url} alt={alt||"Изображение товара"}/><figcaption><label className="field"><span>Описание</span><input value={alt} maxLength={300} onChange={event=>setAlt(event.target.value)}/></label><label className="field"><span>Позиция</span><input type="number" min="0" max="255" value={position} onChange={event=>setPosition(event.target.value)}/></label><div className="button-row"><button type="button" className="button ghost" disabled={save.isPending||remove.isPending} onClick={()=>save.mutate(Number(position))}>{save.isPending?"Сохраняем…":"Сохранить"}</button>{Number(position)!==0?<button type="button" className="button ghost" disabled={save.isPending||remove.isPending} onClick={()=>{setPosition("0");save.mutate(0)}}>Сделать главным</button>:<span className="status status-active">Главное</span>}<button type="button" className="button danger" disabled={save.isPending||remove.isPending} onClick={deleteImage}>{remove.isPending?"Удаляем…":"Удалить"}</button></div>{remove.isError?<ErrorBlock retry={()=>remove.mutate()}>Не удалось удалить изображение. Повторите попытку.</ErrorBlock>:null}</figcaption></figure>;
}
