// Code generated by torgnexa-sdkgen/v1; DO NOT EDIT.
// Source: contracts/openapi/torgnexa-v1.yaml sha256=28a3456f8045536742ba829482a7a14008839b1c4f994bfcb9f70a984d81bc94

package torgnexa

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

const (
	APIVersion        = "0.16.0"
	OpenAPIVersion    = "3.1.0"
	DefaultServerPath = "/api/v1"
	GeneratorVersion  = "torgnexa-sdkgen/v1"
)

type Client struct {
	baseURL     string
	bearerToken string
	httpClient  *http.Client
	userAgent   string
}

type Config struct {
	BaseURL     string
	BearerToken string
	HTTPClient  *http.Client
	UserAgent   string
}

type Response struct {
	StatusCode int
	Header     http.Header
	Body       json.RawMessage
}

type APIError struct {
	StatusCode int
	Body       json.RawMessage
}

func (e *APIError) Error() string { return fmt.Sprintf("torgnexa API returned HTTP %d", e.StatusCode) }

func NewClient(config Config) (*Client, error) {
	base := strings.TrimSpace(config.BaseURL)
	if base == "" {
		return nil, errors.New("base URL is required")
	}
	parsed, err := url.Parse(base)
	if err != nil {
		return nil, fmt.Errorf("parse base URL: %w", err)
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return nil, errors.New("base URL must use http or https")
	}
	if parsed.Host == "" {
		return nil, errors.New("base URL host is required")
	}
	parsed.RawQuery = ""
	parsed.Fragment = ""
	client := config.HTTPClient
	if client == nil {
		client = http.DefaultClient
	}
	userAgent := strings.TrimSpace(config.UserAgent)
	if userAgent == "" {
		userAgent = "torgnexa-go-sdk/" + APIVersion
	}
	return &Client{baseURL: strings.TrimRight(parsed.String(), "/"), bearerToken: config.BearerToken, httpClient: client, userAgent: userAgent}, nil
}

func (c *Client) do(ctx context.Context, method, path string, query url.Values, requestHeaders http.Header, body any) (*Response, error) {
	endpoint := c.baseURL + path
	if len(query) != 0 {
		endpoint += "?" + query.Encode()
	}
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		reader = bytes.NewReader(encoded)
	}
	req, err := http.NewRequestWithContext(ctx, method, endpoint, reader)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", c.userAgent)
	for name, values := range requestHeaders {
		for _, value := range values {
			req.Header.Add(name, value)
		}
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if strings.TrimSpace(c.bearerToken) != "" {
		req.Header.Set("Authorization", "Bearer "+c.bearerToken)
	}
	raw, err := c.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer raw.Body.Close()
	payload, err := io.ReadAll(io.LimitReader(raw.Body, 16<<20))
	if err != nil {
		return nil, err
	}
	response := &Response{StatusCode: raw.StatusCode, Header: raw.Header.Clone(), Body: json.RawMessage(payload)}
	if raw.StatusCode < 200 || raw.StatusCode >= 300 {
		return response, &APIError{StatusCode: raw.StatusCode, Body: response.Body}
	}
	return response, nil
}

type ActivateSettingsIdentityProviderRequest struct {
	ProviderId     string
	IdempotencyKey string
	Body           any
}

func (c *Client) ActivateSettingsIdentityProvider(ctx context.Context, input ActivateSettingsIdentityProviderRequest) (*Response, error) {
	path := "/settings/identity-providers/{provider_id}:activate"
	if strings.TrimSpace(input.ProviderId) == "" {
		return nil, errors.New("provider_id is required")
	}
	path = strings.ReplaceAll(path, "{provider_id}", url.PathEscape(input.ProviderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type AdjustInventoryPositionRequest struct {
	PositionId string
	Body       any
}

func (c *Client) AdjustInventoryPosition(ctx context.Context, input AdjustInventoryPositionRequest) (*Response, error) {
	path := "/inventory/positions/{position_id}/adjustments"
	if strings.TrimSpace(input.PositionId) == "" {
		return nil, errors.New("position_id is required")
	}
	path = strings.ReplaceAll(path, "{position_id}", url.PathEscape(input.PositionId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type AnalyzeWithAIProviderRequest struct {
	Body any
}

func (c *Client) AnalyzeWithAIProvider(ctx context.Context, input AnalyzeWithAIProviderRequest) (*Response, error) {
	path := "/settings/ai-providers:analyze"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type AssignProductCategoryRequest struct {
	ProductId  string
	CategoryId string
}

func (c *Client) AssignProductCategory(ctx context.Context, input AssignProductCategoryRequest) (*Response, error) {
	path := "/products/{product_id}/categories/{category_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	if strings.TrimSpace(input.CategoryId) == "" {
		return nil, errors.New("category_id is required")
	}
	path = strings.ReplaceAll(path, "{category_id}", url.PathEscape(input.CategoryId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type CheckConnectorAccountRequest struct {
	Body any
}

func (c *Client) CheckConnectorAccount(ctx context.Context, input CheckConnectorAccountRequest) (*Response, error) {
	path := "/connector-accounts:check"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CompleteConnectorOAuthRequest struct {
	Body any
}

func (c *Client) CompleteConnectorOAuth(ctx context.Context, input CompleteConnectorOAuthRequest) (*Response, error) {
	path := "/connector-accounts:oauth-callback"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateAIProviderAccountRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateAIProviderAccount(ctx context.Context, input CreateAIProviderAccountRequest) (*Response, error) {
	path := "/settings/ai-providers"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateApprovalPolicyRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateApprovalPolicy(ctx context.Context, input CreateApprovalPolicyRequest) (*Response, error) {
	path := "/approval-policies"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateApprovalRequestRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateApprovalRequest(ctx context.Context, input CreateApprovalRequestRequest) (*Response, error) {
	path := "/approvals/requests"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateCatalogCategoryRequest struct {
	Body any
}

func (c *Client) CreateCatalogCategory(ctx context.Context, input CreateCatalogCategoryRequest) (*Response, error) {
	path := "/catalog/categories"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateConnectorAccountRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateConnectorAccount(ctx context.Context, input CreateConnectorAccountRequest) (*Response, error) {
	path := "/connector-accounts"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateDemoApprovalRequest struct {
	IdempotencyKey string
}

func (c *Client) CreateDemoApproval(ctx context.Context, input CreateDemoApprovalRequest) (*Response, error) {
	path := "/approvals/demo"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type CreateDemoOrdersRequest struct {
	IdempotencyKey string
}

func (c *Client) CreateDemoOrders(ctx context.Context, input CreateDemoOrdersRequest) (*Response, error) {
	path := "/orders/demo"
	query := url.Values{}
	requestHeaders := http.Header{}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type CreateInventoryWarehouseRequest struct {
	Body any
}

func (c *Client) CreateInventoryWarehouse(ctx context.Context, input CreateInventoryWarehouseRequest) (*Response, error) {
	path := "/inventory/warehouses"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateOfferPriceRequest struct {
	ProductId      string
	OfferOrPriceId string
	Body           any
}

func (c *Client) CreateOfferPrice(ctx context.Context, input CreateOfferPriceRequest) (*Response, error) {
	path := "/products/{product_id}/prices/{offer_or_price_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	if strings.TrimSpace(input.OfferOrPriceId) == "" {
		return nil, errors.New("offer_or_price_id is required")
	}
	path = strings.ReplaceAll(path, "{offer_or_price_id}", url.PathEscape(input.OfferOrPriceId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreatePrivacyRequestRequest struct {
	Body any
}

func (c *Client) CreatePrivacyRequest(ctx context.Context, input CreatePrivacyRequestRequest) (*Response, error) {
	path := "/privacy/requests"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateProductRequest struct {
	Body any
}

func (c *Client) CreateProduct(ctx context.Context, input CreateProductRequest) (*Response, error) {
	path := "/products"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateProductImageRequest struct {
	ProductId string
	Body      any
}

func (c *Client) CreateProductImage(ctx context.Context, input CreateProductImageRequest) (*Response, error) {
	path := "/products/{product_id}/images"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateProductOfferRequest struct {
	ProductId string
	Body      any
}

func (c *Client) CreateProductOffer(ctx context.Context, input CreateProductOfferRequest) (*Response, error) {
	path := "/products/{product_id}/offers"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateReconciliationJobRequest struct {
	Body any
}

func (c *Client) CreateReconciliationJob(ctx context.Context, input CreateReconciliationJobRequest) (*Response, error) {
	path := "/reconciliation/jobs"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateSyncPolicyRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateSyncPolicy(ctx context.Context, input CreateSyncPolicyRequest) (*Response, error) {
	path := "/sync/policies"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateUploadRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) CreateUpload(ctx context.Context, input CreateUploadRequest) (*Response, error) {
	path := "/uploads"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type CreateWebhookSubscriptionRequest struct {
	Body any
}

func (c *Client) CreateWebhookSubscription(ctx context.Context, input CreateWebhookSubscriptionRequest) (*Response, error) {
	path := "/webhook-subscriptions"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type DecideApprovalRequest struct {
	RequestId      string
	IdempotencyKey string
	Body           any
}

func (c *Client) DecideApproval(ctx context.Context, input DecideApprovalRequest) (*Response, error) {
	path := "/approvals/{request_id}/decision"
	if strings.TrimSpace(input.RequestId) == "" {
		return nil, errors.New("request_id is required")
	}
	path = strings.ReplaceAll(path, "{request_id}", url.PathEscape(input.RequestId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type DeleteDemoOrdersRequest struct {
	IdempotencyKey string
}

func (c *Client) DeleteDemoOrders(ctx context.Context, input DeleteDemoOrdersRequest) (*Response, error) {
	path := "/orders/demo"
	query := url.Values{}
	requestHeaders := http.Header{}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "DELETE", path, query, requestHeaders, nil)
}

type DisableAIProviderAccountRequest struct {
	Body any
}

func (c *Client) DisableAIProviderAccount(ctx context.Context, input DisableAIProviderAccountRequest) (*Response, error) {
	path := "/settings/ai-providers:disable"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type DisableConnectorAccountRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) DisableConnectorAccount(ctx context.Context, input DisableConnectorAccountRequest) (*Response, error) {
	path := "/connector-accounts:disable"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type DisableSettingsIdentityProviderRequest struct {
	ProviderId     string
	IdempotencyKey string
	Body           any
}

func (c *Client) DisableSettingsIdentityProvider(ctx context.Context, input DisableSettingsIdentityProviderRequest) (*Response, error) {
	path := "/settings/identity-providers/{provider_id}:disable"
	if strings.TrimSpace(input.ProviderId) == "" {
		return nil, errors.New("provider_id is required")
	}
	path = strings.ReplaceAll(path, "{provider_id}", url.PathEscape(input.ProviderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type DisableWebhookSubscriptionRequest struct {
	SubscriptionId string
}

func (c *Client) DisableWebhookSubscription(ctx context.Context, input DisableWebhookSubscriptionRequest) (*Response, error) {
	path := "/webhook-subscriptions/{subscription_id}"
	if strings.TrimSpace(input.SubscriptionId) == "" {
		return nil, errors.New("subscription_id is required")
	}
	path = strings.ReplaceAll(path, "{subscription_id}", url.PathEscape(input.SubscriptionId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "DELETE", path, query, requestHeaders, nil)
}

type EnableConnectorAccountRequest struct {
	Body any
}

func (c *Client) EnableConnectorAccount(ctx context.Context, input EnableConnectorAccountRequest) (*Response, error) {
	path := "/connector-accounts:enable"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type EnrollConnectorCredentialsRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) EnrollConnectorCredentials(ctx context.Context, input EnrollConnectorCredentialsRequest) (*Response, error) {
	path := "/connector-accounts:credentials"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type EvaluateEntitlementRequest struct {
	Body any
}

func (c *Client) EvaluateEntitlement(ctx context.Context, input EvaluateEntitlementRequest) (*Response, error) {
	path := "/entitlements/evaluate"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type EvaluateProductComplianceRequest struct {
	Body any
}

func (c *Client) EvaluateProductCompliance(ctx context.Context, input EvaluateProductComplianceRequest) (*Response, error) {
	path := "/compliance/evaluate"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type ExecuteApprovalRequest struct {
	RequestId      string
	IdempotencyKey string
}

func (c *Client) ExecuteApproval(ctx context.Context, input ExecuteApprovalRequest) (*Response, error) {
	path := "/approvals/{request_id}/execute"
	if strings.TrimSpace(input.RequestId) == "" {
		return nil, errors.New("request_id is required")
	}
	path = strings.ReplaceAll(path, "{request_id}", url.PathEscape(input.RequestId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

func (c *Client) GetCloudSubscription(ctx context.Context) (*Response, error) {
	path := "/cloud/subscription"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) GetConnectorBootstrapState(ctx context.Context) (*Response, error) {
	path := "/connector-accounts:bootstrap"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetConnectorRuntimeConfigRequest struct {
	AccountId string
}

func (c *Client) GetConnectorRuntimeConfig(ctx context.Context, input GetConnectorRuntimeConfigRequest) (*Response, error) {
	path := "/connector-accounts:runtime-config"
	query := url.Values{}
	if strings.TrimSpace(input.AccountId) == "" {
		return nil, errors.New("account_id is required")
	}
	if input.AccountId != "" {
		query.Set("account_id", input.AccountId)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetFulfillmentAllocationRequest struct {
	AllocationId string
}

func (c *Client) GetFulfillmentAllocation(ctx context.Context, input GetFulfillmentAllocationRequest) (*Response, error) {
	path := "/inventory/fulfillment-allocations/{allocation_id}"
	if strings.TrimSpace(input.AllocationId) == "" {
		return nil, errors.New("allocation_id is required")
	}
	path = strings.ReplaceAll(path, "{allocation_id}", url.PathEscape(input.AllocationId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) GetHealth(ctx context.Context) (*Response, error) {
	path := "/health"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetInventoryPositionRequest struct {
	PositionId string
}

func (c *Client) GetInventoryPosition(ctx context.Context, input GetInventoryPositionRequest) (*Response, error) {
	path := "/inventory/positions/{position_id}"
	if strings.TrimSpace(input.PositionId) == "" {
		return nil, errors.New("position_id is required")
	}
	path = strings.ReplaceAll(path, "{position_id}", url.PathEscape(input.PositionId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetLineageTimelineRequest struct {
	System     string
	EntityType string
	EntityId   string
	Field      string
	Limit      int
	BeforeAt   string
	BeforeId   string
}

func (c *Client) GetLineageTimeline(ctx context.Context, input GetLineageTimelineRequest) (*Response, error) {
	path := "/lineage/timeline"
	query := url.Values{}
	if strings.TrimSpace(input.System) == "" {
		return nil, errors.New("system is required")
	}
	if input.System != "" {
		query.Set("system", input.System)
	}
	if strings.TrimSpace(input.EntityType) == "" {
		return nil, errors.New("entity_type is required")
	}
	if input.EntityType != "" {
		query.Set("entity_type", input.EntityType)
	}
	if strings.TrimSpace(input.EntityId) == "" {
		return nil, errors.New("entity_id is required")
	}
	if input.EntityId != "" {
		query.Set("entity_id", input.EntityId)
	}
	if input.Field != "" {
		query.Set("field", input.Field)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.BeforeAt != "" {
		query.Set("before_at", input.BeforeAt)
	}
	if input.BeforeId != "" {
		query.Set("before_id", input.BeforeId)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetNotificationPreferenceRequest struct {
	Channel string
}

func (c *Client) GetNotificationPreference(ctx context.Context, input GetNotificationPreferenceRequest) (*Response, error) {
	path := "/notification-preferences/{channel}"
	if strings.TrimSpace(input.Channel) == "" {
		return nil, errors.New("channel is required")
	}
	path = strings.ReplaceAll(path, "{channel}", url.PathEscape(input.Channel))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetOrderRequest struct {
	OrderId string
}

func (c *Client) GetOrder(ctx context.Context, input GetOrderRequest) (*Response, error) {
	path := "/orders/{order_id}"
	if strings.TrimSpace(input.OrderId) == "" {
		return nil, errors.New("order_id is required")
	}
	path = strings.ReplaceAll(path, "{order_id}", url.PathEscape(input.OrderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetProductRequest struct {
	ProductId string
}

func (c *Client) GetProduct(ctx context.Context, input GetProductRequest) (*Response, error) {
	path := "/products/{product_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetReportDataRequest struct {
	ReportId string
	From     string
	To       string
	Q        string
	Currency string
	Status   string
	Limit    int
	Format   string
}

func (c *Client) GetReportData(ctx context.Context, input GetReportDataRequest) (*Response, error) {
	path := "/reports/{report_id}"
	if strings.TrimSpace(input.ReportId) == "" {
		return nil, errors.New("report_id is required")
	}
	path = strings.ReplaceAll(path, "{report_id}", url.PathEscape(input.ReportId))
	query := url.Values{}
	if input.From != "" {
		query.Set("from", input.From)
	}
	if input.To != "" {
		query.Set("to", input.To)
	}
	if input.Q != "" {
		query.Set("q", input.Q)
	}
	if input.Currency != "" {
		query.Set("currency", input.Currency)
	}
	if input.Status != "" {
		query.Set("status", input.Status)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Format != "" {
		query.Set("format", input.Format)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) GetSettingsSecurityConfiguration(ctx context.Context) (*Response, error) {
	path := "/settings/security/configuration"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) GetSyncStatus(ctx context.Context) (*Response, error) {
	path := "/sync/status"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetWarehouseIncidentRequest struct {
	IncidentId string
}

func (c *Client) GetWarehouseIncident(ctx context.Context, input GetWarehouseIncidentRequest) (*Response, error) {
	path := "/inventory/warehouse-incidents/{incident_id}"
	if strings.TrimSpace(input.IncidentId) == "" {
		return nil, errors.New("incident_id is required")
	}
	path = strings.ReplaceAll(path, "{incident_id}", url.PathEscape(input.IncidentId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetWarehouseOperationalStateRequest struct {
	WarehouseId string
}

func (c *Client) GetWarehouseOperationalState(ctx context.Context, input GetWarehouseOperationalStateRequest) (*Response, error) {
	path := "/inventory/warehouses/{warehouse_id}/operational-state"
	if strings.TrimSpace(input.WarehouseId) == "" {
		return nil, errors.New("warehouse_id is required")
	}
	path = strings.ReplaceAll(path, "{warehouse_id}", url.PathEscape(input.WarehouseId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type GetWebhookDeliveryHistoryRequest struct {
	DeliveryId string
	Limit      int
}

func (c *Client) GetWebhookDeliveryHistory(ctx context.Context, input GetWebhookDeliveryHistoryRequest) (*Response, error) {
	path := "/webhook-deliveries/{delivery_id}/history"
	if strings.TrimSpace(input.DeliveryId) == "" {
		return nil, errors.New("delivery_id is required")
	}
	path = strings.ReplaceAll(path, "{delivery_id}", url.PathEscape(input.DeliveryId))
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) GetWorkspaceSettings(ctx context.Context) (*Response, error) {
	path := "/settings/workspace"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ImportInventoryRequest struct {
	Body any
}

func (c *Client) ImportInventory(ctx context.Context, input ImportInventoryRequest) (*Response, error) {
	path := "/inventory/import"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type InviteWorkspaceMemberRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) InviteWorkspaceMember(ctx context.Context, input InviteWorkspaceMemberRequest) (*Response, error) {
	path := "/settings/members"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

func (c *Client) ListAIProviderAccounts(ctx context.Context) (*Response, error) {
	path := "/settings/ai-providers"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListApprovalPolicies(ctx context.Context) (*Response, error) {
	path := "/approval-policies"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListApprovals(ctx context.Context) (*Response, error) {
	path := "/approvals"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListAuditRecordsRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListAuditRecords(ctx context.Context, input ListAuditRecordsRequest) (*Response, error) {
	path := "/audit"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListCatalogCategories(ctx context.Context) (*Response, error) {
	path := "/catalog/categories"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListComplianceDocuments(ctx context.Context) (*Response, error) {
	path := "/compliance/documents"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListConnectorAccountHealthHistoryRequest struct {
	AccountId string
	Limit     int
}

func (c *Client) ListConnectorAccountHealthHistory(ctx context.Context, input ListConnectorAccountHealthHistoryRequest) (*Response, error) {
	path := "/connector-accounts:health-history"
	query := url.Values{}
	if strings.TrimSpace(input.AccountId) == "" {
		return nil, errors.New("account_id is required")
	}
	if input.AccountId != "" {
		query.Set("account_id", input.AccountId)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListConnectorAccountsRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListConnectorAccounts(ctx context.Context, input ListConnectorAccountsRequest) (*Response, error) {
	path := "/connector-accounts"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListConnectors(ctx context.Context) (*Response, error) {
	path := "/connectors"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListCounterparties(ctx context.Context) (*Response, error) {
	path := "/counterparties"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListFXRates(ctx context.Context) (*Response, error) {
	path := "/fx/rates"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListFulfillmentAllocations(ctx context.Context) (*Response, error) {
	path := "/inventory/fulfillment-allocations"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListInventoryPositions(ctx context.Context) (*Response, error) {
	path := "/inventory/positions"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListInventoryWarehouses(ctx context.Context) (*Response, error) {
	path := "/inventory/warehouses"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListNotificationDeliveriesRequest struct {
	NotificationId string
}

func (c *Client) ListNotificationDeliveries(ctx context.Context, input ListNotificationDeliveriesRequest) (*Response, error) {
	path := "/notifications/{notification_id}/deliveries"
	if strings.TrimSpace(input.NotificationId) == "" {
		return nil, errors.New("notification_id is required")
	}
	path = strings.ReplaceAll(path, "{notification_id}", url.PathEscape(input.NotificationId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListNotificationsRequest struct {
	Limit int
}

func (c *Client) ListNotifications(ctx context.Context, input ListNotificationsRequest) (*Response, error) {
	path := "/notifications"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListOrdersRequest struct {
	Q          string
	Status     string
	PlacedFrom string
	PlacedTo   string
	Limit      int
	Cursor     string
}

func (c *Client) ListOrders(ctx context.Context, input ListOrdersRequest) (*Response, error) {
	path := "/orders"
	query := url.Values{}
	if input.Q != "" {
		query.Set("q", input.Q)
	}
	if input.Status != "" {
		query.Set("status", input.Status)
	}
	if input.PlacedFrom != "" {
		query.Set("placed_from", input.PlacedFrom)
	}
	if input.PlacedTo != "" {
		query.Set("placed_to", input.PlacedTo)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListPlugins(ctx context.Context) (*Response, error) {
	path := "/plugins"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListProductsRequest struct {
	Q      string
	Status string
	Limit  int
	Cursor string
}

func (c *Client) ListProducts(ctx context.Context, input ListProductsRequest) (*Response, error) {
	path := "/products"
	query := url.Values{}
	if input.Q != "" {
		query.Set("q", input.Q)
	}
	if input.Status != "" {
		query.Set("status", input.Status)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListReports(ctx context.Context) (*Response, error) {
	path := "/reports"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListSettingsIdentityProviders(ctx context.Context) (*Response, error) {
	path := "/settings/identity-providers"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListSettingsSecurityAuditRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListSettingsSecurityAudit(ctx context.Context, input ListSettingsSecurityAuditRequest) (*Response, error) {
	path := "/settings/security/audit"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListSettingsSecurityLoginsRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListSettingsSecurityLogins(ctx context.Context, input ListSettingsSecurityLoginsRequest) (*Response, error) {
	path := "/settings/security/logins"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListSettingsSecuritySessionsRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListSettingsSecuritySessions(ctx context.Context, input ListSettingsSecuritySessionsRequest) (*Response, error) {
	path := "/settings/security/sessions"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListSettlementEntriesRequest struct {
	Cursor string
}

func (c *Client) ListSettlementEntries(ctx context.Context, input ListSettlementEntriesRequest) (*Response, error) {
	path := "/settlements"
	query := url.Values{}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListWarehouseIncidents(ctx context.Context) (*Response, error) {
	path := "/inventory/warehouse-incidents"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

func (c *Client) ListWebhookSubscriptions(ctx context.Context) (*Response, error) {
	path := "/webhook-subscriptions"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type ListWorkspaceMembersRequest struct {
	Limit  int
	Cursor string
}

func (c *Client) ListWorkspaceMembers(ctx context.Context, input ListWorkspaceMembersRequest) (*Response, error) {
	path := "/settings/members"
	query := url.Values{}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	if input.Cursor != "" {
		query.Set("cursor", input.Cursor)
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type MarkNotificationReadRequest struct {
	NotificationId string
}

func (c *Client) MarkNotificationRead(ctx context.Context, input MarkNotificationReadRequest) (*Response, error) {
	path := "/notifications/{notification_id}/read"
	if strings.TrimSpace(input.NotificationId) == "" {
		return nil, errors.New("notification_id is required")
	}
	path = strings.ReplaceAll(path, "{notification_id}", url.PathEscape(input.NotificationId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type PreviewConnectorBootstrapRequest struct {
	Body any
}

func (c *Client) PreviewConnectorBootstrap(ctx context.Context, input PreviewConnectorBootstrapRequest) (*Response, error) {
	path := "/connector-accounts:bootstrap-preview"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type PutConnectorRuntimeConfigRequest struct {
	Body any
}

func (c *Client) PutConnectorRuntimeConfig(ctx context.Context, input PutConnectorRuntimeConfigRequest) (*Response, error) {
	path := "/connector-accounts:runtime-config"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type PutConnectorSyncScheduleRequest struct {
	Body any
}

func (c *Client) PutConnectorSyncSchedule(ctx context.Context, input PutConnectorSyncScheduleRequest) (*Response, error) {
	path := "/connector-accounts:schedule"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type PutNotificationPreferenceRequest struct {
	Channel string
	Body    any
}

func (c *Client) PutNotificationPreference(ctx context.Context, input PutNotificationPreferenceRequest) (*Response, error) {
	path := "/notification-preferences/{channel}"
	if strings.TrimSpace(input.Channel) == "" {
		return nil, errors.New("channel is required")
	}
	path = strings.ReplaceAll(path, "{channel}", url.PathEscape(input.Channel))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type PutWarehouseFailoverRouteRequest struct {
	WarehouseId            string
	DestinationWarehouseId string
	Body                   any
}

func (c *Client) PutWarehouseFailoverRoute(ctx context.Context, input PutWarehouseFailoverRouteRequest) (*Response, error) {
	path := "/inventory/warehouses/{warehouse_id}/failover-routes/{destination_warehouse_id}"
	if strings.TrimSpace(input.WarehouseId) == "" {
		return nil, errors.New("warehouse_id is required")
	}
	path = strings.ReplaceAll(path, "{warehouse_id}", url.PathEscape(input.WarehouseId))
	if strings.TrimSpace(input.DestinationWarehouseId) == "" {
		return nil, errors.New("destination_warehouse_id is required")
	}
	path = strings.ReplaceAll(path, "{destination_warehouse_id}", url.PathEscape(input.DestinationWarehouseId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type ReplaceConnectorAccountCapabilitiesRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) ReplaceConnectorAccountCapabilities(ctx context.Context, input ReplaceConnectorAccountCapabilitiesRequest) (*Response, error) {
	path := "/connector-accounts:capabilities"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type ReplayWebhookDeliveryRequest struct {
	DeliveryId string
}

func (c *Client) ReplayWebhookDelivery(ctx context.Context, input ReplayWebhookDeliveryRequest) (*Response, error) {
	path := "/webhook-deliveries/{delivery_id}/replay"
	if strings.TrimSpace(input.DeliveryId) == "" {
		return nil, errors.New("delivery_id is required")
	}
	path = strings.ReplaceAll(path, "{delivery_id}", url.PathEscape(input.DeliveryId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type ReserveFulfillmentAllocationRequest struct {
	Body any
}

func (c *Client) ReserveFulfillmentAllocation(ctx context.Context, input ReserveFulfillmentAllocationRequest) (*Response, error) {
	path := "/inventory/fulfillment-allocations"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type ResolveSyncDriftRequest struct {
	DriftId        string
	IdempotencyKey string
	Body           any
}

func (c *Client) ResolveSyncDrift(ctx context.Context, input ResolveSyncDriftRequest) (*Response, error) {
	path := "/sync/drifts/{drift_id}/actions"
	if strings.TrimSpace(input.DriftId) == "" {
		return nil, errors.New("drift_id is required")
	}
	path = strings.ReplaceAll(path, "{drift_id}", url.PathEscape(input.DriftId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type RetireApprovalPolicyRequest struct {
	PolicyId        string
	ExpectedVersion int
	IdempotencyKey  string
}

func (c *Client) RetireApprovalPolicy(ctx context.Context, input RetireApprovalPolicyRequest) (*Response, error) {
	path := "/approval-policies/{policy_id}"
	if strings.TrimSpace(input.PolicyId) == "" {
		return nil, errors.New("policy_id is required")
	}
	path = strings.ReplaceAll(path, "{policy_id}", url.PathEscape(input.PolicyId))
	query := url.Values{}
	if input.ExpectedVersion == 0 {
		return nil, errors.New("expected_version is required")
	}
	if input.ExpectedVersion != 0 {
		query.Set("expected_version", strconv.Itoa(input.ExpectedVersion))
	}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "DELETE", path, query, requestHeaders, nil)
}

type RevokeSettingsSecuritySessionRequest struct {
	SessionRef     string
	IdempotencyKey string
}

func (c *Client) RevokeSettingsSecuritySession(ctx context.Context, input RevokeSettingsSecuritySessionRequest) (*Response, error) {
	path := "/settings/security/sessions/{session_ref}:revoke"
	if strings.TrimSpace(input.SessionRef) == "" {
		return nil, errors.New("session_ref is required")
	}
	path = strings.ReplaceAll(path, "{session_ref}", url.PathEscape(input.SessionRef))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type RollbackSettingsIdentityProviderRequest struct {
	ProviderId     string
	IdempotencyKey string
	Body           any
}

func (c *Client) RollbackSettingsIdentityProvider(ctx context.Context, input RollbackSettingsIdentityProviderRequest) (*Response, error) {
	path := "/settings/identity-providers/{provider_id}:rollback"
	if strings.TrimSpace(input.ProviderId) == "" {
		return nil, errors.New("provider_id is required")
	}
	path = strings.ReplaceAll(path, "{provider_id}", url.PathEscape(input.ProviderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type RotateWebhookSigningSecretRequest struct {
	SubscriptionId string
	Body           any
}

func (c *Client) RotateWebhookSigningSecret(ctx context.Context, input RotateWebhookSigningSecretRequest) (*Response, error) {
	path := "/webhook-subscriptions/{subscription_id}/rotate-secret"
	if strings.TrimSpace(input.SubscriptionId) == "" {
		return nil, errors.New("subscription_id is required")
	}
	path = strings.ReplaceAll(path, "{subscription_id}", url.PathEscape(input.SubscriptionId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type RunSyncPolicyRequest struct {
	PolicyId       string
	IdempotencyKey string
}

func (c *Client) RunSyncPolicy(ctx context.Context, input RunSyncPolicyRequest) (*Response, error) {
	path := "/sync/policies/{policy_id}/run"
	if strings.TrimSpace(input.PolicyId) == "" {
		return nil, errors.New("policy_id is required")
	}
	path = strings.ReplaceAll(path, "{policy_id}", url.PathEscape(input.PolicyId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, nil)
}

type SaveSettingsIdentityProviderDraftRequest struct {
	ProviderId     string
	IdempotencyKey string
	Body           any
}

func (c *Client) SaveSettingsIdentityProviderDraft(ctx context.Context, input SaveSettingsIdentityProviderDraftRequest) (*Response, error) {
	path := "/settings/identity-providers/{provider_id}"
	if strings.TrimSpace(input.ProviderId) == "" {
		return nil, errors.New("provider_id is required")
	}
	path = strings.ReplaceAll(path, "{provider_id}", url.PathEscape(input.ProviderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type SearchLegalPartiesRequest struct {
	Q              string
	Inn            string
	RegistrationId string
	PartyType      string
	Limit          int
}

func (c *Client) SearchLegalParties(ctx context.Context, input SearchLegalPartiesRequest) (*Response, error) {
	path := "/counterparties/search"
	query := url.Values{}
	if input.Q != "" {
		query.Set("q", input.Q)
	}
	if input.Inn != "" {
		query.Set("inn", input.Inn)
	}
	if input.RegistrationId != "" {
		query.Set("registration_id", input.RegistrationId)
	}
	if input.PartyType != "" {
		query.Set("party_type", input.PartyType)
	}
	if input.Limit != 0 {
		query.Set("limit", strconv.Itoa(input.Limit))
	}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type StartConnectorBootstrapRequest struct {
	Body any
}

func (c *Client) StartConnectorBootstrap(ctx context.Context, input StartConnectorBootstrapRequest) (*Response, error) {
	path := "/connector-accounts:bootstrap"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type StartConnectorOAuthRequest struct {
	Body any
}

func (c *Client) StartConnectorOAuth(ctx context.Context, input StartConnectorOAuthRequest) (*Response, error) {
	path := "/connector-accounts:oauth-start"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

func (c *Client) StreamRealtimeInvalidations(ctx context.Context) (*Response, error) {
	path := "/realtime"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "GET", path, query, requestHeaders, nil)
}

type SyncConnectorAccountRequest struct {
	Body any
}

func (c *Client) SyncConnectorAccount(ctx context.Context, input SyncConnectorAccountRequest) (*Response, error) {
	path := "/connector-accounts:sync"
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}

type UpdateInventoryWarehouseRequest struct {
	WarehouseId string
	Body        any
}

func (c *Client) UpdateInventoryWarehouse(ctx context.Context, input UpdateInventoryWarehouseRequest) (*Response, error) {
	path := "/inventory/warehouses/{warehouse_id}"
	if strings.TrimSpace(input.WarehouseId) == "" {
		return nil, errors.New("warehouse_id is required")
	}
	path = strings.ReplaceAll(path, "{warehouse_id}", url.PathEscape(input.WarehouseId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateOfferPriceRequest struct {
	ProductId      string
	OfferOrPriceId string
	Body           any
}

func (c *Client) UpdateOfferPrice(ctx context.Context, input UpdateOfferPriceRequest) (*Response, error) {
	path := "/products/{product_id}/prices/{offer_or_price_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	if strings.TrimSpace(input.OfferOrPriceId) == "" {
		return nil, errors.New("offer_or_price_id is required")
	}
	path = strings.ReplaceAll(path, "{offer_or_price_id}", url.PathEscape(input.OfferOrPriceId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateProductRequest struct {
	ProductId string
	Body      any
}

func (c *Client) UpdateProduct(ctx context.Context, input UpdateProductRequest) (*Response, error) {
	path := "/products/{product_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateProductImageRequest struct {
	ProductId string
	ImageId   string
	Body      any
}

func (c *Client) UpdateProductImage(ctx context.Context, input UpdateProductImageRequest) (*Response, error) {
	path := "/products/{product_id}/images/{image_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	if strings.TrimSpace(input.ImageId) == "" {
		return nil, errors.New("image_id is required")
	}
	path = strings.ReplaceAll(path, "{image_id}", url.PathEscape(input.ImageId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateProductOfferRequest struct {
	ProductId string
	OfferId   string
	Body      any
}

func (c *Client) UpdateProductOffer(ctx context.Context, input UpdateProductOfferRequest) (*Response, error) {
	path := "/products/{product_id}/offers/{offer_id}"
	if strings.TrimSpace(input.ProductId) == "" {
		return nil, errors.New("product_id is required")
	}
	path = strings.ReplaceAll(path, "{product_id}", url.PathEscape(input.ProductId))
	if strings.TrimSpace(input.OfferId) == "" {
		return nil, errors.New("offer_id is required")
	}
	path = strings.ReplaceAll(path, "{offer_id}", url.PathEscape(input.OfferId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateSyncPolicyRequest struct {
	PolicyId       string
	IdempotencyKey string
	Body           any
}

func (c *Client) UpdateSyncPolicy(ctx context.Context, input UpdateSyncPolicyRequest) (*Response, error) {
	path := "/sync/policies/{policy_id}"
	if strings.TrimSpace(input.PolicyId) == "" {
		return nil, errors.New("policy_id is required")
	}
	path = strings.ReplaceAll(path, "{policy_id}", url.PathEscape(input.PolicyId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateWarehouseOperationalStateRequest struct {
	WarehouseId string
	Body        any
}

func (c *Client) UpdateWarehouseOperationalState(ctx context.Context, input UpdateWarehouseOperationalStateRequest) (*Response, error) {
	path := "/inventory/warehouses/{warehouse_id}/operational-state"
	if strings.TrimSpace(input.WarehouseId) == "" {
		return nil, errors.New("warehouse_id is required")
	}
	path = strings.ReplaceAll(path, "{warehouse_id}", url.PathEscape(input.WarehouseId))
	query := url.Values{}
	requestHeaders := http.Header{}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateWorkspaceMemberRequest struct {
	MemberId       string
	IdempotencyKey string
	Body           any
}

func (c *Client) UpdateWorkspaceMember(ctx context.Context, input UpdateWorkspaceMemberRequest) (*Response, error) {
	path := "/settings/members/{member_id}"
	if strings.TrimSpace(input.MemberId) == "" {
		return nil, errors.New("member_id is required")
	}
	path = strings.ReplaceAll(path, "{member_id}", url.PathEscape(input.MemberId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "PATCH", path, query, requestHeaders, input.Body)
}

type UpdateWorkspaceSettingsRequest struct {
	IdempotencyKey string
	Body           any
}

func (c *Client) UpdateWorkspaceSettings(ctx context.Context, input UpdateWorkspaceSettingsRequest) (*Response, error) {
	path := "/settings/workspace"
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "PUT", path, query, requestHeaders, input.Body)
}

type ValidateSettingsIdentityProviderRequest struct {
	ProviderId     string
	IdempotencyKey string
	Body           any
}

func (c *Client) ValidateSettingsIdentityProvider(ctx context.Context, input ValidateSettingsIdentityProviderRequest) (*Response, error) {
	path := "/settings/identity-providers/{provider_id}:validate"
	if strings.TrimSpace(input.ProviderId) == "" {
		return nil, errors.New("provider_id is required")
	}
	path = strings.ReplaceAll(path, "{provider_id}", url.PathEscape(input.ProviderId))
	query := url.Values{}
	requestHeaders := http.Header{}
	if strings.TrimSpace(input.IdempotencyKey) == "" {
		return nil, errors.New("Idempotency-Key is required")
	}
	if input.IdempotencyKey != "" {
		requestHeaders.Set("Idempotency-Key", input.IdempotencyKey)
	}
	return c.do(ctx, "POST", path, query, requestHeaders, input.Body)
}
