#!/usr/bin/env python3
"""Generate the non-secret frontend connector catalog from canonical manifests."""

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "frontend/src/generated/connector-catalog.ts"
GO_OUTPUT = ROOT / "internal/platform/connectors/catalog_generated.go"


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


entries = []
manifest_documents = []
for path in sorted((ROOT / "connectors").glob("*/manifest.json")):
    document = json.loads(path.read_text(encoding="utf-8"))
    required = ("id", "name", "family", "version", "capabilities", "auth")
    if any(key not in document for key in required):
        raise SystemExit(f"incomplete connector manifest: {path.relative_to(ROOT)}")
    if path.parent.name != document["id"]:
        raise SystemExit(f"connector directory/id mismatch: {path.relative_to(ROOT)}")
    entries.append({
        "id": document["id"],
        "name": document["name"],
        "family": document["family"],
        "version": document["version"],
        "capabilities": sorted(set(document["capabilities"])),
        "authKinds": sorted({requirement["kind"] for requirement in document["auth"]}),
        "oauthGrantType": next((requirement.get("oauth2", {}).get("grant_type") for requirement in document["auth"] if requirement["kind"] == "oauth2"), None),
    })
    manifest_documents.append(document)

lines = [
    "// Code generated by scripts/generate-frontend-connector-catalog.py; DO NOT EDIT.\n",
    "export interface ConnectorCatalogEntry {\n",
    "  readonly id: string;\n",
    "  readonly name: string;\n",
    "  readonly family: string;\n",
    "  readonly version: string;\n",
    "  readonly capabilities: readonly string[];\n",
    "  readonly authKinds: readonly string[];\n",
    "  readonly oauthGrantType?: \"authorization_code\" | \"client_credentials\";\n",
    "}\n\n",
    "export const connectorCatalog: readonly ConnectorCatalogEntry[] = [\n",
]
for entry in entries:
    lines.extend([
        "  {\n",
        f"    id: {quoted(entry['id'])},\n",
        f"    name: {quoted(entry['name'])},\n",
        f"    family: {quoted(entry['family'])},\n",
        f"    version: {quoted(entry['version'])},\n",
        f"    capabilities: [{', '.join(quoted(value) for value in entry['capabilities'])}],\n",
        f"    authKinds: [{', '.join(quoted(value) for value in entry['authKinds'])}],\n",
        *(([f"    oauthGrantType: {quoted(entry['oauthGrantType'])},\n"] if entry["oauthGrantType"] else [])),
        "  },\n",
    ])
lines.append("] as const;\n")
rendered = "".join(lines)
catalog_json = json.dumps(manifest_documents, ensure_ascii=False, separators=(",", ":"))
go_rendered = f'''// Code generated by scripts/generate-frontend-connector-catalog.py; DO NOT EDIT.
package connectors

import (
\t"encoding/json"
\t"sync"
)

const generatedCatalogJSON = `{catalog_json}`

var generatedCatalog struct {{
\tsync.Once
\tmanifests []Manifest
\tbyID      map[string]Manifest
\terr       error
}}

func loadGeneratedCatalog() {{
\tgeneratedCatalog.err = json.Unmarshal([]byte(generatedCatalogJSON), &generatedCatalog.manifests)
\tgeneratedCatalog.byID = make(map[string]Manifest, len(generatedCatalog.manifests))
\tif generatedCatalog.err != nil {{
\t\treturn
\t}}
\tfor index, manifest := range generatedCatalog.manifests {{
\t\tif err := manifest.Validate(); err != nil {{
\t\t\tgeneratedCatalog.err = err
\t\t\treturn
\t\t}}
\t\tmanifest = manifest.Canonical()
\t\tgeneratedCatalog.manifests[index] = manifest
\t\tgeneratedCatalog.byID[manifest.ID] = manifest
\t}}
}}

// CatalogManifests returns the reviewed provider-neutral connector metadata.
func CatalogManifests() ([]Manifest, error) {{
\tgeneratedCatalog.Do(loadGeneratedCatalog)
\tif generatedCatalog.err != nil {{
\t\treturn nil, generatedCatalog.err
\t}}
\treturn append([]Manifest(nil), generatedCatalog.manifests...), nil
}}

// CatalogManifest resolves one canonical manifest without importing providers.
func CatalogManifest(id string) (Manifest, error) {{
\tgeneratedCatalog.Do(loadGeneratedCatalog)
\tif generatedCatalog.err != nil {{
\t\treturn Manifest{{}}, generatedCatalog.err
\t}}
\tmanifest, ok := generatedCatalog.byID[id]
\tif !ok {{
\t\treturn Manifest{{}}, ErrConnectorNotFound
\t}}
\treturn manifest, nil
}}
'''
if "--check" in sys.argv[1:]:
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
        raise SystemExit("frontend connector catalog is stale; run scripts/generate-frontend-connector-catalog.py")
    if not GO_OUTPUT.is_file() or GO_OUTPUT.read_text(encoding="utf-8") != go_rendered:
        raise SystemExit("Go connector catalog is stale; run scripts/generate-frontend-connector-catalog.py")
    print(f"Frontend connector catalog: PASS ({len(entries)} connectors)")
else:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    GO_OUTPUT.write_text(go_rendered, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(entries)} connectors")
